; ..\LIB\OLEDLG.LIB PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

OleUIAddVerbMenuA PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
OleUIAddVerbMenu equ <OleUIAddVerbMenuA>

OleUIBusyA PROTO :DWORD
OleUIBusy equ <OleUIBusyA>

OleUICanConvertOrActivateAs PROTO :DWORD,:DWORD,:DWORD
OleUIChangeIconA PROTO :DWORD
OleUIChangeIcon equ <OleUIChangeIconA>

OleUIChangeSourceA PROTO :DWORD
OleUIChangeSource equ <OleUIChangeSourceA>

OleUIConvertA PROTO :DWORD
OleUIConvert equ <OleUIConvertA>

OleUIEditLinksA PROTO :DWORD
OleUIEditLinks equ <OleUIEditLinksA>

OleUIInsertObjectA PROTO :DWORD
OleUIInsertObject equ <OleUIInsertObjectA>

OleUIObjectPropertiesA PROTO :DWORD
OleUIObjectProperties equ <OleUIObjectPropertiesA>

OleUIPasteSpecialA PROTO :DWORD
OleUIPasteSpecial equ <OleUIPasteSpecialA>

OleUIUpdateLinksA PROTO :DWORD,:DWORD,:DWORD,:DWORD
OleUIUpdateLinks equ <OleUIUpdateLinksA>


