; ..\LIB\STRMBASD.LIB PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

AMGetWideString PROTO :DWORD,:DWORD
AMovieDllRegisterServer PROTO
AMovieDllRegisterServer2 PROTO :DWORD
AMovieDllUnregisterServer PROTO
AMovieSetupRegisterFilter PROTO :DWORD,:DWORD,:DWORD
AMovieSetupRegisterFilter2 PROTO :DWORD,:DWORD,:DWORD
AMovieSetupRegisterServer PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
AMovieSetupUnregisterServer PROTO :DWORD,:DWORD,:DWORD,:DWORD
ContainsPalette PROTO :DWORD
CreateAudioMediaType PROTO :DWORD,:DWORD,:DWORD
CreateMemoryAllocator PROTO :DWORD
CreatePosPassThru PROTO :DWORD,:DWORD,:DWORD,:DWORD
DirectDrawCreateFromDevice PROTO :DWORD,:DWORD,:DWORD
DirectDrawCreateFromDeviceEx PROTO :DWORD,:DWORD,:DWORD
DllCanUnloadNow PROTO
DllEntryPoint PROTO :DWORD,:DWORD,:DWORD
DllGetClassObject PROTO :DWORD,:DWORD,:DWORD
EliminateSubKey PROTO :DWORD,:DWORD
FreeBSTR PROTO :DWORD
GetBitCount PROTO :DWORD
GetBitmapFormatSize PROTO :DWORD
GetBitmapPalette PROTO :DWORD
GetBitmapSize PROTO :DWORD
GetBitmapSubtype PROTO :DWORD
GetInterface PROTO :DWORD,:DWORD
GetSubtypeName PROTO :DWORD
GetTrueColorType PROTO :DWORD
ReadInt PROTO :DWORD,:DWORD
RegisterAllServers PROTO :DWORD,:DWORD
WriteBSTR PROTO :DWORD,:DWORD
WriteInt PROTO :DWORD,:DWORD
memmoveInternal PROTO :DWORD,:DWORD,:DWORD

